### ISSUE TITLE
sci-libs/pytorch-1.6.0-r1 fails to emerge, saying MKL library not found

### ISSUE THREAD

**Issue by jian-lin** [gentoo/sci#1011]
The errors are as follows:
```
CMake Error at cmake/Modules/FindMKL.cmake:398 (MESSAGE):
  MKL library not found.  Please specify library location by appending the
  root directory of the MKL installation to the environment variable
  CMAKE_PREFIX_PATH.
```

I set these USE flags in package.use for pytorch:
```
sci-libs/pytorch mkl -openblas ffmpeg cuda -gloo lmdb leveldb namedtensor -nnpack -opencv -observers -openmp -qnnpack
```

[build.log](https://github.com/gentoo/sci/files/5756711/build.log)

[emerge_info.txt](https://github.com/gentoo/sci/files/5756712/emerge_info.txt)

**Comment by ezzieyguywuf** [comment]
From the build output, it seems that perhaps this is missing a `sci-libs/mkl` dependency (this is currently available in `::gentoo`.

I'll take a stab at adding it and see if I can get the ebuild up and running - even without the `mkl` USE-flag, I'm getting a different error regarding a missing python module.

**Comment by heroxbd** [comment]
> From the build output, it seems that perhaps this is missing a `sci-libs/mkl` dependency (this is currently available in `::gentoo`.
> 
> I'll take a stab at adding it and see if I can get the ebuild up and running - even without the `mkl` USE-flag, I'm getting a different error regarding a missing python module.
> 
> Ah, nvm I see the dep is in there, but perhaps the `sci-libs/mkl` needs to be updated to install headers. Either way, I'll plan to work on this.

Thank you!  For the moment I am going to mask sci-libs/pytorch[mkl] until you have a solution.

**Comment by epsilon-0** [comment]
@heroxbd this error is because sci-libs/mkl does not install that FindMKL.cmake file, it never did even in the past.
I am unsure why pytorch has thought to use this file, unless they are the ones who are supplying it (such as CGAL, who supply a version of FindMKL.cmake which is installed). 
A proposed solution - we move the FindMKL.cmake from sci-mathematics/cgal to sci-libs/mkl. We already supply our own versions of pkg-config  files so this isn't that far-fetched.
I can do this, I am the maintainer of both packages CGAL and MKL. 
Does the plan sound good?

**Comment by heroxbd** [comment]
> @heroxbd this error is because sci-libs/mkl does not install that FindMKL.cmake file, it never did even in the past.
> I am unsure why pytorch has thought to use this file, unless they are the ones who are supplying it (such as CGAL, who supply a version of FindMKL.cmake which is installed).
> A proposed solution - we move the FindMKL.cmake from sci-mathematics/cgal to sci-libs/mkl. We already supply our own versions of pkg-config files so this isn't that far-fetched.
> I can do this, I am the maintainer of both packages CGAL and MKL.
> Does the plan sound good?

Sure, please go ahead to implement it of it works.  I am unsure whether providing mkl via blas runtime switch is enough.

**Comment by epsilon-0** [comment]
Will take a look at runtime switch possibility as well.

**Comment by heroxbd** [comment]
> Will take a look at runtime switch possibility as well.

The 1.7.1 version supports runtime switch.  I'd like to hear if you could confirm it.
