### ISSUE TITLE
torch_shm_manager rightful place

### ISSUE THREAD

**Issue by kenshin33** [gentoo/sci#1039]
shouldn't this be  /usr/lib/ instead of /usr/lib64
https://github.com/gentoo/sci/blob/1615cf4bf2d69b39cec4fe5b8926dc449f71ddbe/sci-libs/pytorch/pytorch-1.6.0-r1.ebuild#L266
?
affter emerging  pytorch trying to importing it fails while complaining about not finding torch_shm_manager in /usr/lib/${EPYTHON}/site-packages/torch/bin (using 17.1 profile)
The only thing presetn in /usr/lib64/python*/ is torch_shm_manager

    ~ # find  /usr/lib64/python3.*/
    /usr/lib64/python3.7/
    /usr/lib64/python3.7/site-packages
    /usr/lib64/python3.7/site-packages/torch
    /usr/lib64/python3.7/site-packages/torch/bin
    /usr/lib64/python3.7/site-packages/torch/bin/torch_shm_manager
    /usr/lib64/python3.8/
    /usr/lib64/python3.8/site-packages
    /usr/lib64/python3.8/site-packages/torch
    /usr/lib64/python3.8/site-packages/torch/bin
    /usr/lib64/python3.8/site-packages/torch/bin/torch_shm_manager

**Comment by AndrewAmmerlaan** [comment]
This should have fixed it: https://github.com/gentoo/sci/commit/3ada98e36e771cba1c7e4eb4833421b8f4fe745d

Let me know if it works now :smile:

**Comment by kenshin33** [comment]
Thanks!
build started  will report  back the result (I'm pretty sure it will work )

**Comment by heroxbd** [comment]
> This should have fixed it: [3ada98e](https://github.com/gentoo/sci/commit/3ada98e36e771cba1c7e4eb4833421b8f4fe745d)
> 
> Let me know if it works now smile

Thanks Andrew!
