### ISSUE TITLE
Remove sci-mathematics/lattE-macchiato

### ISSUE THREAD

**Issue by kiwifb** [gentoo/sci#1043]
The ebuild is outdated and has a number of issues. lattE-macchiato has been superseded by latte-int which is now hosted on github and is a much better behaved package. 

An ebuild for latte-int is currently in the sage-on-gentoo overlay https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/latte-int/latte-int-1.7.5.ebuild

**Comment by epsilon-0** [comment]
whoops sorry, forgot to add the close tag in d7395e24eaff4bfecacbca783f83dca3fc49b019
Please close the issue and thanks for bringing it to attention <3
