### ISSUE TITLE
dev-python/fslpy-3.4.0 file collisions

### ISSUE THREAD

**Issue by AbstractMethod** [gentoo/sci#1047]
dev-python/fslpy-3.4.0 has file collisions with sci-biology/fsl

```
 * Detected file collision(s):
 *
 * 	/usr/bin/fsl_abspath
 * 	/usr/bin/Text2Vest
 * 	/usr/bin/Vest2Text
 * 	/usr/bin/imrm
 * 	/usr/bin/imtest
 * 	/usr/bin/remove_ext
 * 	/usr/bin/imln
```

I suspect that the files in fslpy are the 'correct' ones sinces they are newer, but don't know the best way to resolve.  We could remove those files from fsl and add fslpy as a dependency?

@TheChymera any ideas?

Hi @pauldmccarthy: since you wrote the new Python scripts, what's the best way to resolve?  Or should we just wait until the new build system is all in place for fsl (which would presumably resolve all our woes?)

**Comment by TheChymera** [comment]
@AndrewAmmerlaan please don't update with packages with an active maintainer unless you are familiar with them or unless you hard mask the update. Particularly, don't delete old versions just in case your update might break something, as happened here. Also, even for packages you are familiar with, it's good practice to have at least 2 versions of a package available, to permit manual downgrade in case an update causes unforeseen issues.

What happened is that flspy is primarily used as an FSL dependency, with which it is developed in some synchrony. As it stands, your update collides with the package it's supposed to support.

@AbstractMethod fixed in https://gitweb.gentoo.org/proj/sci.git/commit/?id=309efaaf039e3b7f2502cc079450f46c66ed1678

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan please don't update packages with an active maintainer unless you are familiar with them or unless you hard mask the update. Particularly, don't delete old versions just in case your update might break something, as happened here. Also, even for packages you are familiar with, it's good practice to have at least 2 versions of a package available, to permit manual downgrade in case an update causes unforeseen issues.

Sorry about that, I should have checked the git log first.

**Comment by pauldmccarthy** [comment]
Yep, the `fslpy` versions supersede the FSL ones - the older FSL ones just haven't been removed yet. We're in the process of re-packaging all of FSL, so this collision should go away soon(ish).

**Comment by TheChymera** [comment]
@AndrewAmmerlaan 

> I should have checked the git log first.

I'm not sure that would have helped, your update wasn't broken per se, but it was broken as generally used. Sadly, I don't think this would have popped up on the radar unless you knew how it is generally used :( I think good policy is to prioritize packages without active maintainers. We still have packages 4-5 years out of date, without a maintainer at all, and some outright broken ones to boot. That should be a lot more pressing than me not having updated the FSL stack in half a year. As seen in the comment above, upstream is doing some major re-packaging, and we're waiting for that before we update again.

**Comment by TheChymera** [comment]
@pauldmccarthy do you plan to remove the source files for 6.0.2? We'd like to still distribute it for a while. Could you keep them online or should we mirror them?

**Comment by pauldmccarthy** [comment]
@TheChymera No, we only officially support the most recent version (6.0.4), and don't have any sort of backport mechanism, so 6.0.2 will remain as it currently is, and shouldn't be taken offline any time soon.  

The refactorings I have hinted at will probably be several months away - we're aiming for an interim release first half 2021, and then a major release second half 2021.

**Comment by TheChymera** [comment]
@pauldmccarthy sorry, slight misunderstanding. I was asking about whether the sources for 6.0.2 will remain hosted with you for a long time even after more future releases. A while ago I remember some fsl source code going missing :)

**Comment by pauldmccarthy** [comment]
No, there are no immediate plans to take the source downloads offline. We have limited space, so old versions will periodically be purged, but for 6.0.2 you're probably safe for a wee while yet.
