### ISSUE TITLE
sci-biology/salmon fails to build

### ISSUE THREAD

**Issue by jsmolic** [gentoo/sci#1058]
```
error: '/var/tmp/portage/sci-biology/salmon-0.10.2/work/salmon-0.10.2/external/install/lib/libstaden-read.a', needed by 'src/unitTests', missing and no known rule to make it
```
(also fails with [gcc-10](https://bugs.gentoo.org/755533)) 
I made some progress with `salmon-0.10.2`, after I reverted back to EAPI 6 and `cmake-utils.eclass`, but seems like it needs more work.

Version 1.4.0. is missing patches, needs keywords, and depends on `sci-biology/pufferfish` which also fails to compile

cc @AndrewAmmerlaan as you were the last one to work on these packages

**Comment by AndrewAmmerlaan** [comment]
> cc @AndrewAmmerlaan as you were the last one to work on these packages

I tried to get this working earlier, but pufferfish is being very difficult. The whole build system is a mess of things trying to fetch other things and was obviously not designed for packaging in distro's. Pufferfish *should* work (it has all the things it wants now) but still fails to compile, my guess is that if we get pufferfish to work, the version of salmon that is now masked will work too (it might need another dependency or two, but those are easy to package)

> I reverted back to EAPI 6 and `cmake-utils.eclass`

AFAIK `cmake` and `cmake-utils` are more or less the same thing with a different name, so it should work with `cmake` too. What is the error you're getting with `cmake` vs `cmake-utils`?

**Comment by jsmolic** [comment]
Sorry I forgot to reply. The first one mentioned in the issue is what I'm seeing with cmake. With cmake-utils it fails with -fno-common error. Did it work for you with cmake.eclass when you were updating it?

**Comment by AndrewAmmerlaan** [comment]
> Sorry I forgot to reply. The first one mentioned in the issue is what I'm seeing with cmake.

Is `sci-biology/staden` installed? If I remember correctly there was a missing dependency for the masked version that might also be required for the older version, it was staden-something, but I'm not sure if it is the same things as `sci-biology/staden`

**Comment by mmokrejs** [comment]
You probably mean:

```
# emerge -s io_lib
  
[ Results for search key : io_lib ]
Searching...

*  sci-libs/io_lib
      Latest version available: 1.14.7
      Latest version installed: 1.14.7
      Size of files: 2 127 KiB
      Homepage:      http://staden.sourceforge.net/
      Description:   General purpose trace and experiment file reading/writing interface
      License:       BSD
```

**Comment by AndrewAmmerlaan** [comment]
That might be the one, does installing that (with USE="static-libs") fix the issue?

**Comment by jsmolic** [comment]
> That might be the one, does installing that (with USE="static-libs") fix the issue?

Unfortunately no

**Comment by AndrewAmmerlaan** [comment]
> > That might be the one, does installing that (with USE="static-libs") fix the issue?
> 
> Unfortunately no

Than this might be a case of the build system explicitly wanting specific sources in specific locations, I had the exact same problem with pufferfish and had to patch out a lot of things, and download some additional sources (and than of course it still didn't work :cry: ).

**Comment by AndrewAmmerlaan** [comment]
I fixed this in https://github.com/gentoo/sci/commit/459e5c7233c8d8e9aae0946e5fef3279fdcd0ba2

Only to run into the next issue:
```
ninja -v -j12 -l12
ninja: error: '/usr/lib64/libbwa.so', needed by 'src/unitTests', missing and no known rule to make it
```
which seems to me like a library that should be provided by `sci-biology/bwa` but it isn't :(

**Comment by mmokrejs** [comment]
Maybe because Gentoo does not allow statis libs, we suck the static lib into the final binary instead?

```
x86_64-pc-linux-gnu-ar -csru libbwa.a utils.o kthread.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o QSufSort.o bwt_gen.o rope.o rle.o is.o bwtindex.o
x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -ftree-vectorize -Wall -Wno-unused-function -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS -Wl,-O1 -Wl,--as-needed bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
```

Salmo for sure used older `bwa` version but I think the `sci-biology/bwa-0.7.17::gentoo` is still doing the same thing, true, after patches, namely `bwa-0.7.17-Makefile.patch`.

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
