### ISSUE TITLE
dev-libs/boost-1.72 does not build

### ISSUE THREAD

**Issue by S-t-e-p-h-a-n** [gentoo/sci#1059]
The commit that brought back boost 1.72 did not bring back all patch files. As a consequence boost does not build. The following files are missing according to the ebuild:

"${FILESDIR}"/${PN}-1.71.0-disable_icu_rpath.patch
"${FILESDIR}"/${PN}-1.71.0-context-x32.patch
"${FILESDIR}"/${PN}-1.71.0-build-auto_index-tool.patch

Please bring back these patch files.

**Comment by thesamesam** [comment]
Thanks!
