### ISSUE TITLE
rocmBLAS compile failed

### ISSUE THREAD

**Issue by stelinux01** [gentoo/sci#1076]
I try to compile rocmBLAS on gfx 1010 but obtain the follow error:
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2_strided_batched.cpp:4:
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2.hpp:5:
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_reduction_template.hpp:6:
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/fetch_template.hpp:35:17: error: reference to __host__ function 'norm<float>' in __host__ __device__ function
    return std::norm(A);
                ^
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2.hpp:13:17: note: called by 'operator()<float>'
        return {fetch_abs2(x)};
                ^
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/reduction_strided_batched.hpp:223:19: note: called by 'rocblas_reduction_strided_batched_kernel_part1<512, rocblas_fetch_nrm2<float>, rocblas_reduce_sum, const float *, float>'
        tmp[tx] = FETCH{}(x[tid * incx], tid);
                  ^
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/complex:1866:5: note: 'norm<float>' declared here
    norm(_Tp __x)
    ^
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2_strided_batched.cpp:4:
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2.hpp:5:
In file included from /var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_reduction_template.hpp:6:
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/fetch_template.hpp:35:17: error: reference to __host__ function 'norm<double>' in __host__ __device__ function
    return std::norm(A);
                ^
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/rocblas_nrm2.hpp:13:17: note: called by 'operator()<double>'
        return {fetch_abs2(x)};
                ^
/var/tmp/portage/sci-libs/rocBLAS-4.0.0-r2/work/rocBLAS-rocm-4.0.0/library/src/blas1/reduction_strided_batched.hpp:223:19: note: called by 'rocblas_reduction_strided_batched_kernel_part1<512, rocblas_fetch_nrm2<double>, rocblas_reduce_sum, const double *, double>'
        tmp[tx] = FETCH{}(x[tid * incx], tid);
                  ^
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/complex:1866:5: note: 'norm<double>' declared here
    norm(_Tp __x)
    ^
2 errors generated when compiling for gfx1010.

attach my build log.
[rocmBLASbuild.log](https://github.com/gentoo/sci/files/6252648/rocmBLASbuild.log)

**Comment by AndrewAmmerlaan** [comment]
Closing because package has been removed
