### ISSUE TITLE
Numba 0.53.1 installation has horrible race conditions that non-deterministically blow up

### ISSUE THREAD

**Issue by leycec** [gentoo/sci#1080]
`dev-python/numba-0.53.1.ebuild` currently has an unversioned TBB requirement:

```
RDEPEND="
	...
	threads? ( dev-cpp/tbb )
"
```

Unfortunately, that's not quite right. Numba requires a minimum TBB version. Installation fails when the current TBB version is insufficient with compile-time errors like:

```
numba/np/ufunc/tbbpool.cpp:31:2: error: #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"
   31 | #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"
      |  ^~~~~
```

From that message, we can optimistically deduce this ebuild should instead require at least TBB >= 2019.5:

```
RDEPEND="
	...
	threads? ( >=dev-cpp/tbb-2019.5 )
"
```

Thanks as always for the extraordinary volunteerism, @AndrewAmmerlaan and crew! :+1:

**Comment by leycec** [comment]
**Addendum:** Numba also has a minimum requisite NumPy version, declared in `setup.py` via the `min_numpy_run_version` global. For Numba 0.53.1, this is:

```
min_numpy_run_version = "1.15"
```

This ebuild should thus also require at least NumPy >= 1.15.0:

```
RDEPEND="
	...
        >=dev-python/numpy-1.15.0[${PYTHON_USEDEP}]
	...
"
```

*Phew.*

**Comment by kiwifb** [comment]
I didn't really need to be reminded of those debugging sessions. Signed: a contributor to scipy/scipy#7112 and Gentoo.

**Comment by epsilon-0** [comment]
At some point in the past I had put -j1 for numba. I removed it thinking the error was related to something else and was fixed. Am willing to put it back in and/or just putting a message in pkg_pretend telling the user to be ready for this crap and put -j1 themselves if shit breaks.

**Comment by leycec** [comment]
Numba upstream: [*duly notified*](https://github.com/numba/numba/issues/7063).

@kiwifb: When someone signs off on [a commit message so epic we still discuss it more than a year later](https://github.com/gentoo/gentoo/commit/809afd4a24533311ced5ecfb2f022b539a3b6dd2) with mutual head-shaking at the next Auckland LUG (now with delicious Gentoo penguin on the barbie), you just know you've done good.

@epsilon-0: Yeah. Shit breaks, alright! Mostly on my machine. For the sake of all my `emerge @world`, let's just force `-j1` not only for Numba but *everything* across Python's scientific stack. Pandas also suffers the same exact issue with the same exact fix. (More on that below when we summon a little-known guy named Michał Górny into the chat.) I'm ~happy~ ~content~ begrudgingly willing to fix both this and the trivial dependency stuff above for Numba, so I'll just go ahead and submit a PR here. You've already suffered enough for us all.

@mgorny: I can't believe how much nonsensical shade Pandas developers threw all over your parallel make fix. I'm intentionally *not* linking there, as I'd rather toxic people stay well away from here. But when Pandas developer jreback snarkily asked "why is `j` more than like 4 actually useful?", I just about lost my ramdisk. I'm livid and I didn't even have a horse in that race. Sure, your PR was a little balls-crazy – but *at least you made a full-faith effort.* That thread confirmed deep suspicions that everyone just wants to use [Vaex](https://github.com/vaexio/vaex) instead.
