### ISSUE TITLE
check duplicates is comparing licenses names with packages names

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/sci#1087]
```
 	docs/proj::science possible duplicate of sci-libs/proj::gentoo
	licenses/AMD::science possible duplicate of sci-libs/amd::gentoo
	licenses/chimera::science possible duplicate of dev-haskell/chimera::gentoo
	licenses/merlin::science possible duplicate of dev-ml/merlin::gentoo
	licenses/netCDF::science possible duplicate of sci-libs/netcdf::gentoo
```

**Comment by AndrewAmmerlaan** [comment]
This is intentional, since there is no point in having identical licenses here that are already in ::gentoo

**Comment by waebbl** [comment]
None of these licenses is in ::gentoo. And the doc/proj contains project documentation for the Gentoo Science Project and has nothing to do with the sci-libs/proj package. Please do some basic checking before opening an issue:
```
waebbl$ ls /var/db/repos/gentoo/licenses/{AMD,chimera,merlin,netCDF}
ls: cannot access '/var/db/repos/gentoo/licenses/AMD': No such file or directory
ls: cannot access '/var/db/repos/gentoo/licenses/chimera': No such file or directory
ls: cannot access '/var/db/repos/gentoo/licenses/merlin': No such file or directory
ls: cannot access '/var/db/repos/gentoo/licenses/netCDF': No such file or directory
```

**Comment by Alessandro-Barbieri** [comment]
Now I'm more confused than before

**Comment by waebbl** [comment]
There are packages in ::gentoo with similar names as the licenses that were found. But those are packages as you can see from the category, not licenses.

**Comment by Alessandro-Barbieri** [comment]
That's what I'm trying to say from the start

**Comment by waebbl** [comment]
Oh I'm sorry, looks like I got you wrong.

**Comment by Alessandro-Barbieri** [comment]
Can you also checkout #1085 and #1086?

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
