### ISSUE TITLE
[Feature Request] CadQuery, the great CAD GUI destroyer

### ISSUE THREAD

**Issue by leycec** [gentoo/sci#1097]
This feature request is actually just me tracking the multiple PRs I'll be submitting shortly for [CadQuery 2.1](https://cadquery.readthedocs.io), the most recent stable release of a fairly revolutionary open-source Python framework.

CadQuery *kinda* single-handedly obsoletes proprietary CAD GUIs that literally cost millions in licensing fees like AutoCAD and SolidWorks, similar to how NumPy *kinda* single-handedly obsoleted proprietary math GUIs with similar costs like MATLAB. The killer idea here is that CadQuery programmatically generates Computer-Aided Design (CAD) files in obscure industry formats like STEP, DXF, STL, and OBG from Python one-liners like this:

```
import cadquery as cq
cq.Workplane("XY").box(length,height,thickness).faces(">Z").workplane().hole(bearing_diam)
        .faces(">Z").workplane()
        .rect(length-padding,height-padding,forConstruction=True)
        .vertices().cboreHole(2.4, 4.4, 2.1)
```

...which generates [this parametric bearing pillow block](https://cadquery.readthedocs.io/en/latest/quickstart.html):

![parametric bearing pillow block, yo](https://cadquery.readthedocs.io/en/latest/_images/000.png)

*Yeah.* That's hot.

Sadly, CadQuery's build system isn't. Thus this issue. For those familiar with PySide2 (i.e., the official Python bindings for Qt 5), CadQuery is fiendishly similar. And I should know; I authored the PySide2 family of ebuilds currently in Portage. <sup>*good times*</sup>

Just like PySide2, CadQuery implements its own C++-to-Python bindings generator called [pywrap](https://github.com/CadQuery/pywrap) for automagically generating Python bindings to humongously large C++ libraries – in this case, [Open Cascade, a C++ CAD library that's **1.5GB large**](https://en.wikipedia.org/wiki/Open_Cascade_Technology). Just like PySide2, CadQuery is split up into multiple components, each with multiple dependencies collectively taking over half-a-day to build on my ailing 2000-era AMD Athlon II X2 240. <sup>*good times*</sup>

So, here we go. These are the three main CadQuery pull requests I'll be submitting shortly (in order):

1. **[pywrap](https://github.com/CadQuery/pywrap),** CadQuery's aforementoined CLang-based binding generators. It's... pretty intense.
2. **[OCP](https://github.com/CadQuery/OCP),** a Python C++ extension providing the actual Python bindings to Open Cascade – dynamically generated by hurling pywrap at Open Cascade and hoping for the best.
3. **[CadQuery itself](https://github.com/CadQuery/cadquery),** a pure-Python 3 API importing from OCP at runtime to do most of the low-level CAD lifting.

I actually [just finished 1 and 2 at my overlay tonight](https://github.com/leycec/raiagent), so this should mostly go fast. **Let's do this.** :flying_saucer:

**Comment by kiwifb** [comment]
Sounds awesome. I can't wait to see this gets more traction. For the record I have a 2003 athlon machine in my garage (not 64bits capable) and it is well and truly retired now.

We've been there before with the build systems. A great time to plug https://www.youtube.com/watch?v=NSemlYagjIU&t=573s again.

**Comment by waebbl** [comment]
Sounds like a promising package.

**Comment by leycec** [comment]
> Sounds awesome. I can't wait to see this gets more traction.

> Sounds like a promising package.

I know, right? Even Canadian astronauts are excited! <sup>...i just made that up</sup> :astronaut: 

> A great time to plug https://www.youtube.com/watch?v=NSemlYagjIU&t=573s again.

Be still the beating anger in my heart. What a great talk that I immediately want to forget never happens on an hourly basis in my open-source "career."

Finally, let's hear a thunderous cheer for overlay masters @AndrewAmmerlaan and @waebbl! Thanks to their tireless efforts, **[CadQuery phase 1: pywrap](https://github.com/gentoo/sci/pull/1098)** has been successfully merged after receiving a bludgeoning review from which my fragile ego may never recover. We grimly death-march onto **CadQuery phase 2: OCP.**

We may fail – but at least we'll have tried. Doesn't that mean something?
