### ISSUE TITLE
sci-biology/tigmint: setup.py needs fix

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#1118]
Hi,
  would somebody have a look why the package places a read_fasta.py module file into /usr/bin/ instead of python site-packages?
Thank you

https://github.com/gentoo/sci/commit/6c45174a480dae72e147dbf764bda33b72404a56

**Comment by AndrewAmmerlaan** [comment]
This was fixed in: https://github.com/gentoo/sci/commit/9a13af8737903d7bb70f8667fa53e6056fd3d429#diff-cf81a261aafc9a535e5c7c922c602593e41224a31332d805daa9449020aac361
