### ISSUE TITLE
sci-libs/geom depends on opencascade-7.4.0

### ISSUE THREAD

**Issue by waebbl** [gentoo/sci#1119]
I will submit a PR to ::gentoo today to remove sci-libs/opencascade:7.4.0 and found the package sci-libs/geom::science depends on this version.

From what I can tell from the packages homepage URL, this seems to be a subpackage of salome, which is not available in Gentoo. Being that salome is currently in v9 and the geom package is of v6, this package could probably be quite outdated as well.

Please update the package to build against opencascade:7.5 or update the version or remove the package.

See also https://salome-platform.org/downloads/current-version

**Comment by AndrewAmmerlaan** [comment]
> From what I can tell from the packages homepage URL, this seems to be a subpackage of salome, which is not available in Gentoo. Being that salome is currently in v9 and the geom package is of v6, this package could probably be quite outdated as well.

It actually isn't, to cite the [sourceforge](https://sourceforge.net/projects/salomegeometry/) page:

> A complete OpenCascade - OCAF based CAD framework.Note that this is not the original SALOME GEOM project but an effort to create a standalone framework based on the existing one from SALOME project, with the addition of extra functionality.

Since it hasn't been touched upstream since 2011 and does not build with opencascade-7.5 I have masked it for removal.

**Comment by waebbl** [comment]
Thanks for researching deeper than I liked to do and clarifying things!
