### ISSUE TITLE
sci-biology/fsl: `ERROR::Could not install eddy successfully`

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#1122]
@Jimmy2027 and I are getting the following error for `USE="cuda" emerge -v =sci-biology/fsl-6.0.4`:

http://109.202.220.106:2095/ppb/build.log

The package builds fine with `USE="-cuda"`. @AbstractMethod I remember you worked on the [CUDA support](https://github.com/gentoo/sci/pull/973), specifically for eddy. Any idea what could be up?

**Comment by AbstractMethod** [comment]
@TheChymera : sorry, just getting this over a month late!

Could you repost the log?  The URL doesn't resolve for me.

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
