### ISSUE TITLE
Macaulay2

### ISSUE THREAD

**Issue by aureliocarlucci** [gentoo/sci#1124]
Dear developers of the Mathematics Project,

I understand that Macaulay2 was [removed](https://github.com/gentoo/sci/commit/1331916dfa9c5dfa3956973cdf12ad37c4c19634#diff-573cf62ee113f6db205c72d9ecacbd2c3185333be212702aed9f0e3fa1c854bc) from the Science Overlay, as it relied on a deprecated Python version.

On the official Macaulay2 [page](https://faculty.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Gentoo/index.html), Thomas Kahle is still designated as curator for Gentoo, but he confirmed via email that he stepped down from the role.

Since I am not aware of any current plan to update the Gentoo package and bring Macaulay2 back for Gentoo users, I had a go at writing an ebuild, starting from the one once available from the Science Overlay. It now compiles and installs well, at least on my system, and can be found on my [overlay](https://github.com/aureliocarlucci/AurOverlay/tree/master/sci-mathematics/Macaulay2).

I would greatly appreciate any suggestion or comment. In particular, I am keen to know if this ebuild compiles well on other Gentoo systems: for example, I have quite a number of mathematical utilities installed on my system, meaning that dependencies for Macaulay2 might be satisfied without me realising, hence omitting them from the ebuild.

Moreover, as Thomas explained, Macaulay2 bundles several accessory utilities and libraries, which would be good practice to disentangle into separate ebuilds. Many of the dependencies have their own Gentoo package already, but indeed some are left out: these are included as tarball sources in the ebuild.

I am happy to fork the Science Overlay and create an official pull request, but I would welcome your input and advice on the best way forward.

Many thanks in advance for your help.

**Comment by waebbl** [comment]
I appreciate the initiative to get this package back into ::science.

>I would greatly appreciate any suggestion or comment. In particular, I am keen to know if this ebuild compiles well on other Gentoo systems: for example, I have quite a number of mathematical utilities installed on my system, meaning that dependencies for Macaulay2 might be satisfied without me realising, hence omitting them from the ebuild.

You can easily test for required but missing dependencies if you emerge your ebuild in a chroot, which you have just setup with a stage 3.

Other suggestions on the ebuild:
- use the skel.ebuild from ::gentoo as a guide in the file's structure. Some things are not up-to-date wrt to the defined standard
- as there will most likely a versioned ebuild needed, you can add logic to work with both, live and versioned ebuild. This way, it's easier later on to copy the live ebuild into a versioned ebuild
- gtest is available in ::gentoo as dev-cpp/gtest and in DEPEND, but also added as third party package in your ebuild
- add a KEYWORD for the arch you are working with, most likely ~amd64
- use one style for functions, you have both styles `pkg_setup ()` and `pkg_setup()`. The latter is IMHO preferred
- do parallel builds fail with cmake too?
- check dependencies for sub slot operators. If a package has sub slots you need the `:=` operator to trigger automatic rebuild checking on updates of dependencies
- some of the dependencies are in the wrong class. Boost for example is most likely a RDEPEND, while gtest as a test requirement is BDEPEND, as well as pkgconfig. Those might not be the only ones, just the ones I noticed on a quick read. Check that these are all in the correct section
- How about EAPI 8?

The easiest way to get feedback, would IMO be to open a pull request with your ebuild.

**Comment by aureliocarlucci** [comment]
Many thanks for your reply, and for all the suggestions you list. I will try to implement them, and make a pull request (at least for a live ebuild) once all works reasonably well.

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
