### ISSUE TITLE
Cannot install sci-mathematics/freefem++ with USE flag mpi

### ISSUE THREAD

**Issue by bugalo** [gentoo/sci#1126]
When trying to install sci-mathematics/freefem++, it pulls sci-libs/hdf5 with USE flag cxx, but it conflicts with USE flag mpi. The only option available to compile it is to disable the USE flag mpi for sci-mathematics/freefem++.

Could you update the ebuild to install sci-mathematics/freefem++ with mpi support?

Thanks.

**Comment by AndrewAmmerlaan** [comment]
> The only option available to compile it is to disable the USE flag mpi for sci-mathematics/freefem++.

Setting `USE="unsupported"` overrides this, but as the name suggests this is unsupported by upstream. In any case, freefem++[mpi] seems to compile just fine with hfd5[-mpi] so I'll remove that dependency.
