### ISSUE TITLE
dev-python/cadquery-ocp - upcoming slotmove for opencascade

### ISSUE THREAD

**Issue by waebbl** [gentoo/sci#1129]
I want to inform of an upcoming slotmove of the sci-libs/opencascade package[1]. With the bump to 7.6.0, the package will only be available in a single slot 0, with added subslots 7.5, 7.6 to simplify the logic needed in revdeps to select the correct build time options wrt the installed version(s) of opencascade.

The cadquery-ocp package depends on opencascade and uses a slot specifier of `:7.5`, which needs to get updated, once the PR has been merged.

[1] https://github.com/gentoo/gentoo/pull/22834

**Comment by AndrewAmmerlaan** [comment]
Fixed per https://github.com/gentoo/sci/commit/506d5cbf440a2ddf92499f0daf2acdd86b92ae1e
