### ISSUE TITLE
sci-libs/mkl LAPACK settings causing various issues

### ISSUE THREAD

**Issue by lambda-tango** [gentoo/sci#152]
Okay, so I have mkl-11.1.0.080 installed, and eselect lapack set to 'mkl64-int64-intel-openmp'. I've encountered two issues today, both related to media-gfx/hugin from the main Gentoo overlay. Disclaimer: I have little experience with the science packages specifically, and their related compiler flags, etc. If any assumptions or actions of mine are erroneous please feel free to correct me.

First, hugin would not build with eselect LAPACK set to mkl64-int64-intel-openmp . Eselecting LAPACK to mkl64-int64-intel solved this. Further investigation revealed that in the file 

/etc/env.d/alternatives/lapack/mkl64-int64-intel-penmp/usr/lib64/pkgconfig/lapack.pc, 

on the line beginning with "Libs:", the flag "-openmp" was passed, which struck me as odd. Replacing "-openmp" with "-fopenmp" and switching LAPACK back to mkl64-int64-intel-openmp setting allowed hugin to build with OpenMP. So I believe that file should probably be corrected.

The second issue is that hugin's Lens Calibration GUI would not initially run. ~/.xsession-errors gave the line:

/usr/bin/calibrate_lens_gui: symbol lookup error: /opt/intel/composerxe-2013.0.080/mkl/lib/intel64/libmkl_intel_ilp64.so: undefined symbol: mkl_vsl_serv_threader_for

Googling for the symbol  gave the Intel forum thread at http://software.intel.com/en-us/forums/topic/351714. At least the temporary solution given (using LD_PRELOAD) allows the program to run correctly. The permanent solution does not fix the problem for me at this point; most likely I have not yet discerned the necessary use and ordering of -Wl flags, etc.

I have no idea if the lapack.pc file should be modified or a patch applied to hugin or what. Additionally a correct lasting fix for the second issue would be invaluable. Thank you.

**Comment by jlec** [comment]
@lambda-tango Did you test the latest version of mkl? Should be better there.

**Comment by heroxbd** [comment]
Obsolete by the eselect-ldso framework and sci-libs/mkl-rt::gentoo.
