### ISSUE TITLE
sci-mathematics/z3-4.3.1 fails to build with USE=-gmp

### ISSUE THREAD

**Issue by tecknicaltom** [gentoo/sci#189]
Firstly, the ebuild fails in the case of USE=-gmp:

```
42c42
<       -e "/LINK_EXTRA_FLAGS/s:@LDFLAGS@:-lrt $(usex gmp -lgmp ""):g" \

---
>       -e "/LINK_EXTRA_FLAGS/s:@LDFLAGS@:-lrt $(usex gmp -lgmp):g" \
```

Without that change, usex outputs "no", which adds the word no to the linker command line, resulting in an error.

Even with that fixed though, compiling results in many linker errors related to gmp. I believe that upstream's configure script is not properly handling the case of having gmp installed and being given --without-gmp

**Comment by TheChymera** [comment]
libatlas is no longer provided by Gentoo Science. If the package is still relevant, we could try to bring it back pending a PR.
