### ISSUE TITLE
R can't be built with openblas

### ISSUE THREAD

**Issue by lyarbean** [gentoo/sci#20]
I have successfully installed openblas from science overlay and eselect openblas-int64-threads as blas and cblas provider, and lapack provider is reference (lapack-reference-3.4.1). 

R is built with USEs "X cairo icu jpeg lapack nls openmp perl png readline tiff tk ", and seems fine to work, but it isn't linked to openblas, instead it uses its own and runs so slow on crossprod. I can check this from /proc/$Rpid/maps.

**Comment by heroxbd** [comment]
R does not support int64.
