### ISSUE TITLE
Removing the sys-cluster/condor fetch restriction

### ISSUE THREAD

**Issue by g2boojum** [gentoo/sci#219]
The condor source code is available directly from github as well as from the htcondor web site.  Only the latter requires clicking through.

Borrowing from Fedora, the download URL can be generated from the commit for the release (found from https://github.com/htcondor/htcondor/releases).

For example, for htcondor-8.1.4, the necessary changes to the ebuild would be:

```
COMMIT=e23e62fe73d71f3e09549a87d37de95651f08f02
SHORTCOMMIT="${COMMIT:0:7}"
SRC_URI="https://github.com/${PN}/${PN}/archive/${COMMIT}/${P}-${SHORTCOMMIT}.tar.gz"
S="${WORKDIR}/${PN}-${COMMIT}"
```

**Comment by jlec** [comment]
Could you please send a PR? Also there are many new versions.
