### ISSUE TITLE
sci-libs/plasma-2.6.0 - file collisions

### ISSUE THREAD

**Issue by HJarausch** [gentoo/sci#250]
sci-libs/plasma-2.6.0 does not install due to
- Detected file collision(s):
- 
-      /usr/include/plasma/plasma.h
-      /usr/lib64/libquark.so
- 
- Searching all installed packages for file collisions...
- 
- Press Ctrl-C to Stop
- 
- kde-base/kdelibs-4.13.3-r1:4::gentoo
-      /usr/include/plasma/plasma.h
- 
- sci-libs/xkaapi-2.1:0::gentoo
-      /usr/lib64/libquark.so
-

**Comment by TheChymera** [comment]
`sci-libs/plasma` is no longer provided by Gentoo Science, following a general clean-up of the overlay done in order to bring it up to scratch. If ithis package is still of interest, we would be very happy to bring it back pending a PR :)
