### ISSUE TITLE
sci-mathematics/scilab-5.5.1: javasci: undefined symbol (xcos)

### ISSUE THREAD

**Issue by maggu2810** [gentoo/sci#289]
Hello!

I would like to use javasci to access scilab / xcos within java.
As the same code is working using scilab in windows, this is perhaps related to #282, too <source>(but append-ldflags $(no-as-needed)</source> is already set.

<pre>
Warning: Could not find Java package '/usr/share/scilab/thirdparty/ecj.jar'.
Some problems during the loading of the Java libraries occurred.
This could lead to inconsistent behaviours.
Please check SCI/etc/classpath.xml.
Catched FileNotFoundException: /usr/share/gluegen-2.1/lib/gluegen-rt-natives-linux-amd64.jar (No such file or directory), while addNativeJarLibsImpl(classFromJavaJar class com.jogamp.common.os.Platform, classJarURI jar:file:/usr/share/gluegen-2.1/lib/gluegen-rt.jar!/com/jogamp/common/os/Platform.class, nativeJarBaseName gluegen-rt-natives-linux-amd64.jar): [ file:/usr/share/gluegen-2.1/lib/gluegen-rt.jar -> file:/usr/share/gluegen-2.1/lib/ ] + gluegen-rt-natives-linux-amd64.jar -> slim: jar:file:/usr/share/gluegen-2.1/lib/gluegen-rt-natives-linux-amd64.jar!/
Exception: A Scilab error occurred: Impossible to load libscixcos.so library: (null)
Code: 999
A previous error has been detected while loading libsciscicos.so: /usr/lib64/scilab/libsciscicos_blocks.so.5: undefined symbol: _ZN13GiwsException22JniCallMethodExceptionD1Ev
A previous error has been detected while loading libscixcos.so: /usr/lib64/scilab/libscixcos.so: undefined symbol: pvApiCtx
</pre>

**Comment by zoell** [comment]
@maggu2810 I have the same issue now:
/scilab-6.0.0/lib/scilab/libsciscicos_blocks.so.6: undefined symbol: _ZN13GiwsException12JniExceptionD1Ev

how did you manage to solve this? do you have the list of the linked libs?

**Comment by maggu2810** [comment]
> There were several bug reports about it but upstream is not spending any time on this. 

@zoell I stopped further investigation. I installed another linux distribution in a chroot env / container and also a scilab binary package. After that I started that scilab and forwarded the X DISPLAY.

**Comment by TheChymera** [comment]
@maggu2810 sorry to see you go! We are hard at work to get Gentoo Science back on par. The version detailed in this issue is no longer distributed in the overlay, but a newer version is. If there remains any interest in this package, could you have a look at that? Also, contributing to Gentoo Science is easy, and we are happy to mentor new maintainers. If you would like, bumping this package to an even newer version would make for a great intro!

**Comment by maggu2810** [comment]
I am no longer using Gentoo. Sorry.
