### ISSUE TITLE
sci-libs/mesquite source is unavailable

### ISSUE THREAD

**Issue by marbre** [gentoo/sci#321]
I intended to move mesquite to EAPI=5. Meanwhile I noticed that the source is not available via the the SRC_URI any more.
The [homepage](http://trilinos.org/packages/mesquite/) links to a separate [site](http://trilinos.org/oldsite/packages/mesquite/). The [download site](http://trilinos.org/oldsite/packages/mesquite/Software.htm) provided there, links to a [registration form](http://www.cs.sandia.gov/web1400/1400_download.html).

So, somehow the source has to be fetches or should we fetch restrict the ebuild?

**Comment by junghans** [comment]
If the license is *GPL*, it guarantees no restrictions on redistribution. Maybe you are able to see the URL in chrome's download tab after filling the registration form.

**Comment by marbre** [comment]
The license is *LPGL* ... Anyway if you *register*, the following notice appears on the download page:
> Register
> If you have reached this page without registering, please complete the registration form before downloading Mesquite.

**Comment by marbre** [comment]
I've just checked and version 2.1.2 isn't available anymore:

>Mesquite Source
>
>    Mesquite 1.1.7
>    Mesquite 2.0.2
>    Mesquite 2.1.4
>    Mesquite 2.2.0
>    Mesquite 2.3.0
>    Current Development Version (from Trilinos/packages/mesquite)

**Comment by marbre** [comment]
Not available in the repo anymore.
