### ISSUE TITLE
sys-cluster/htcondor fetches external libs during build

### ISSUE THREAD

**Issue by marbre** [gentoo/sci#343]
Within the compile phase of htcondor-8.3.2.ebuild the following packages are fetched:
- /var/tmp/portage/sys-cluster/htcondor-8.3.2/work/htcondor-8.3.2_build/bld_external/zlib-1.2.3/dl/zlib-1.2.3.tar.gz
- /var/tmp/portage/sys-cluster/htcondor-8.3.2/work/htcondor-8.3.2_build/bld_external/glibc-2.19-0ubuntu6/dl/glibc-2.19-0ubuntu6.tar.gz

The _CMakeLists.txt_ shows that we somehow get into the _if ( NOT CLIPPED )_ case for zlib and thus the external project is added. I assume this is equal for glibc.
Don't know if I can find enough time to fix this in the next weeks.

**Comment by AndrewAmmerlaan** [comment]
Closing because package has been removed
