### ISSUE TITLE
Concerns about the new blas/lapack infrastructure

### ISSUE THREAD

**Issue by gerddie** [gentoo/sci#38]
Hello, 

recently I updating to the new BLAS/LAPACK packages that no longer support the dynamic switching between implementations. I tried to search the net to find why this change was proposed and implemented, but I didn't find anything helpful. Hence, sorry if I bring up issues that have been discussed before. 

I have the following issues (I will always write BLAS, but i think the issues are the same for lapack and cblas): 

Considering that for some reason I want to use different implementations of BLAS for different packages that require it. how can I ensure that an "update world" keeps using the version I selected for each version? Wouldn't it be better if a package that requires a blas implementation selects the implementation based on use flags? At least then one would be sure that each package uses exactly what the user wants.  

Now consider that I have two packages that require BLAS and I want to link them together in a third software (e.g. it++ and the GNU scientific library that go into another project), and assume, that they are both compiled with different version of BLAS (say ATLAS and ACML), can one assume  that this is save or will it crash? If a certain function is called from both packages, which one will be called? 
Again, with a use-flags based selection, one could at least in an ebuild ensure that all libraries that make use of BLAS and are linked by a third package use the same BLAS implementation. (If a user just compiles some software then they are of course still on their own.)

The third point is that IMHO removing the ability of the user to switch the implementation dynamically by running a certain eselect is a step backwards: For instance a user could debug her software by using a FOSS implementation of BLAS and if this works fine, she could switch to a high performance implementation like MLK or ACML without recompiling anything. For this it would be nice if the eselect for the compile time dependency could provide the option to link to a generic library (like before) that can then be selected.  I'd imagine something like: 

```
eselect blas set blas-dynamic 
eselect blas-dynamic  set (acml|atlas|...)
```

This would bring back the  dynamic switching like it was available before, without removing the ability to set a certain library as it possible now. (Notwithstanding that I still think for this case a use-flag or similar mechanism would be better to make sure a certain package uses a given BLAS implementation). 

Many thanks, 
Gert

**Comment by heroxbd** [comment]
The BLAS/LAPACK dynamic switching is back.  Thanks!  https://wiki.gentoo.org/wiki/Blas-lapack-switch
