### ISSUE TITLE
sci-biology/biopieces depends on missing sci-biology/idba

### ISSUE THREAD

**Issue by marbre** [gentoo/sci#381]
> dependency.badmasked          2
>   sci-biology/biopieces/biopieces-0.51.ebuild: RDEPEND: \* *(empty profile) ['sci-biology/idba']
>   sci-biology/biopieces/biopieces-9999.ebuild: RDEPEND: \* *(empty profile) ['sci-biology/idba']

`sci-biology/idba` is neither available in the tree nor in the science overlay.

**Comment by jlec** [comment]
Drop keywords if something is broken

**Comment by mmokrejs** [comment]
Sorry for the mistake and long delay, I just pushed:

```
commit bae149ca5806b0db04206b0569f733a6c41a1007
Author: Martin Mokrejš <mmokrejs@fold.natur.cuni.cz>
Date:   Sat Sep 24 13:24:04 2016 +0200

    sci-biology/idba: new package, needed by biopieces, github issue #381


commit 0f38e9552bf34f6c99d9afd35af1290d005309b8
Author: Martin Mokrejš <mmokrejs@fold.natur.cuni.cz>
Date:   Sat Sep 24 13:26:40 2016 +0200

    sci-biology/biopieces: re-add just landed sci-biology/idba to DEPENDencies, github issue 381#
```

See also https://github.com/loneknightpy/idba/issues/23 .
