### ISSUE TITLE
Upcoming (?) Freesurfer ebuild

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#401]
Hi, I would like to write an ebuild for [Freesurfer](http://surfer.nmr.mgh.harvard.edu/). This software is needed as part of many neuroimaging pipelines. Sadly, it is only distributed as a binary **and** it [requires the user to register and manually copy](https://surfer.nmr.mgh.harvard.edu/fswiki/Registration) a `license.txt` file to a location that will presumably be a system directory.

How can I deal with the entire license download copy etc. bit in an ebuild?

**Comment by kiwifb** [comment]
That's not completely correct but my correction won't help much. There used to be source release tarballs (I have one for freesurfer 5.1). This seem to have been discontinued.

If you want recent source you need to pull them from CVS: https://surfer.nmr.mgh.harvard.edu/fswiki/ReadOnlyCVS and you can access the sources for a current release by requesting the appropriate tag. You still need to register to get a password to the CVS repo in read only mode. I don't know if the version compiled from source needs a license key either, I don't think our install does.

The stuff is full of shipped dependencies (a lot of which are quite uncommon and/or old).

**Comment by TheChymera** [comment]
Does portage support the bring-your-own-password CVS download thing? Or would we have to require users to manually get the sources? 

> The stuff is full of shipped dependencies (a lot of which are quite uncommon and/or old).

Do you think this would make it unfeasible or not worthwhile for packaging?

**Comment by kiwifb** [comment]
For CVS password the answer is yes. You should read the eclass documentation https://devmanual.gentoo.org/eclass-reference/cvs.eclass/index.html

For the rest one of my colleague has a cvs snapshot dated 140815 that I will inspect.

**Comment by kiwifb** [comment]
Hum... optional dep: sci-libs/itk

Other deps not in the tree:
 * mni (ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/src/mni.srcbuild.README.txt)
 * vxl (http://vxl.sourceforge.net/)

mni and vxl and freesurfer were a pain to install on ppc64 it is probably easier on x86_64 but that will not be a bed of roses.

**Comment by TheChymera** [comment]
sci-libs/itk is in the (science) tree, though. Are the other deps also optional? 

If not, I guess these things are included in the binary? If it's such a pain, maybe we can just ship it as a binary for the time being? How much would you be willing to help out with this? Based on the kind of work it took to make fsl compile, I still don't think I could deal with seriously messy stuff on my own....

**Comment by kiwifb** [comment]
mni and vxl are not in any way optional. And yes it is a bit like fsl all over again just an order of magnitude bigger. It is unclear if the preferred building method is cmake or autotools as both are shipped. With cmake itk doesn't seem to be optional but I could be wrong. That you have a standard build system instead of a build script is an improvement on fsl though.

**Comment by TheChymera** [comment]
So, where do we start? I am thinking I could start writing ebuilds for the deps (starting with [VXL](http://vxl.sourceforge.net/#download)) while you find out how to deal with Freesurfer itself? (and if there are any further deps). What do you think?

**Comment by kiwifb** [comment]
I am not promising anything on working on freesurfer. I have quite a lot on my plate caring for sage & sage-on-gentoo and its dependencies on top of my regular work. So this takes the back seat. I would rather improve fsl first.

**Comment by TheChymera** [comment]
I understand. I will try to work off the dependencies, and would welcome any support along the way from you. I am also quite busy with my regular work, and on top of that likely a lot less time-efficient than you in writing ebuilds. Still, Freesurfer is a rather big deal for neuroimaging, so it would be nice to have it at some point!

**Comment by TheChymera** [comment]
@kiwifb hi again! The [mni link you posted](ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/src/mni.srcbuild.README.txt) seems to link to a software bundle. Doyou recommend making an ebuild for that, or one for each of the individual software bits inside the bundle?

        NetCDF          v3.6.2
        MINC            v1.4.1
        MNI Perllib     v0.07
        N3              v1.10
        EBTKS           v1.4
        Getopt-Tabular  v0.3
        MNI autoreg     v0.98r
        MNI models      v1.03
        BICPL           v1.4.1
        Register        v1.3.5
        Display         v1.3.9

**Comment by kiwifb** [comment]
Tough question. Especially `NetCDF`, this is an outdated version. The question is whether or not you could use a newer `NetCDF`. In the first instance because nothing depends on it and because of `NetCDF` I would not unbundle the thing.

**Comment by TheChymera** [comment]
netcdf is already provided in portage, though. Maybe it would be best just to try that out? If this is so messy that it depends on outdated software, I guess maybe it's too complicated to manage it via portage anyway?

**Comment by kiwifb** [comment]
You are welcome to try one of the newer version in portage. But if it doesn't work there is no shame in using the bundled one in that case. Although everyone would prefer it if it was working with newer `NetCDF` but unless it is trivial (or you are working for upstream) porting to newer `NetCDF` is going in the too hard basket.

**Comment by TheChymera** [comment]
@kiwifb where should I install MNI to avoid conflicts with the newer NetCDF?

**Comment by kiwifb** [comment]
To be honest I am expecting libnetcdf to be linked statically in whatever MNI binaries and therefore not needing to be installed at all.

**Comment by TheChymera** [comment]
@kiwifb while the ebuild for minc seems to be working and was a breeze to write, I cannot say the same about all the other constituent packages of MNI...

So I am starting to think that even regardless of version incompatibilities, maybe I should write a package for all of MNI and then eventually unbundle some of the stuff..


Regarding the MNI instructions, how would I do this in an ebuild? `setenv MNI_INSTALL_DIR   /usr/pubsw/packages/mni/current` Also, is it a smart idea to put stuff there? The way the MNI install guide words it, Freesurfer is hard-coded to look under that path?

**Comment by kiwifb** [comment]
Certainly do not put it there. Install it properly. `freesurfer` hard coding will have to be removed or changed. You could think of `freesurfer` has acting as its own meta distribution of a bunch of software. It has the advantage of sort of working out of the box but it there is no provision to make a system wide install. That's a possibility that the authors put in the too hard basket because they don't think someone will or want to package for a system.

**Comment by TheChymera** [comment]
@kiwifb what does installing it properly mean? what should I set `MNI_INSTALL_DIR` to?

**Comment by kiwifb** [comment]
`/usr` ideally. It may need hand holding for `lib/lib64` stuff and proper location of everything.

**Comment by TheChymera** [comment]
@kiwifb ok, I am hoping soon enough minc-toolkit can be pulled, and then I am thinking I can move on to Freesurfer itself? I can't find any page specifying freesurfer's exact deps, and the ftp link you provided earlier does not work anymore. Do you know whether the dependency you listed as "MNI" is satisfiled by the minc-toolkit?

**Comment by kiwifb** [comment]
Sorry was cut from the internet since Wednesday for mni you can look here: ftp://surfer.nmr.mgh.harvard.edu/pub/dist/fs_supportlibs/src/
I don't know if minc provides it and I am still catching on one week leave and half of it without internet.

**Comment by TheChymera** [comment]
This has been put on indefinite hold on my part. For mesh plotting of neuroimaging figures, blender seems to be a much more accessible and reliable alternative: https://github.com/IBT-FMI/SAMRI/blob/master/samri/plotting/blender_visualization.py See figure examples e.g. here https://www.biorxiv.org/content/biorxiv/early/2020/04/04/2020.04.03.023648/F3.large.jpg
