### ISSUE TITLE
sci-misc/stanford-tagger and sci-misc/stanford-parser fail to build

### ISSUE THREAD

**Issue by brigadier** [gentoo/sci#402]
sci-misc/stanford-tagger and sci-misc/stanford-parser fail to build
the error is
`edu/stanford/nlp/math/ArrayMath.java:833: error: name clash: unbox(List<Double>) and unbox(List<Integer>) have the same erasure`

**Comment by marbre** [comment]
I cannot reproduce this for stanford-tagger-20060521 and stanford-parser-1.6. Which java implementation do you use, or rather what does `eselect java-vm list` tells? Here, I don't have trouble with ` [1]   icedtea-bin-6  system-vm user-vm`.

**Comment by brigadier** [comment]
[1]   icedtea-bin-7  system-vm

**Comment by TheChymera** [comment]
Packages are hard masked, denoting possible build failures. They are also quite outdated. If interest exists in them, please consider submitting PRs with ebuilds for more current versions.
