### ISSUE TITLE
sci-mathematics/netgen-5.3.1: version bump

### ISSUE THREAD

**Issue by Fat-Zer** [gentoo/sci#436]
There are several upstream releases available since the last version bump. The 5.3.1 is the latest one.

See the sourceforge download page: http://sourceforge.net/projects/netgen-mesher/files/netgen-mesher/

**Comment by jlec** [comment]
Could you provide a pullrequest for this?

**Comment by Fat-Zer** [comment]
may be later...

**Comment by apieum** [comment]
@update version 6.0-beta is out

**Comment by apieum** [comment]
see PR #584

**Comment by TheChymera** [comment]
`=sci-mathematics/netgen-5.3.1` is now available in Gentoo Science.
