### ISSUE TITLE
app-text/dgs breaks imagemagick emerge

### ISSUE THREAD

**Issue by kayvax** [gentoo/sci#440]
Hi,
I have had some problems with updating imagemagick on my other machine and narrowed it down to app-text/dgs. During emerge imagemagick looks for dps delegate and if app-text/dgs is installed includes:
DPS/dpsXclient.h
DPS/dpsXpreview.h
This results in error and imagemagick emerge fails.

Possible workarounds: remove USE="postscript" for imagemagick or remove app-text/dgs from system.

**Comment by TheChymera** [comment]
the dgs package has since been dropped.
