### ISSUE TITLE
libatlas: undefined reference to `ATL_SetAtomicCount` and more (version 3.10.1-r2)

### ISSUE THREAD

**Issue by Giels** [gentoo/sci#498]
the version 3.10.1-r2 of atlas cannot be linked against correctly as it's missing several symbols, namely
ATL_SetAtomicCount
ATL_DecAtomicCount
ATL_FreeAtmoicCount
ATL_ResetAtomicCount

**Comment by Giels** [comment]
This happens with USE="-thread", these symbols aren't defined in that case.

**Comment by kiwifb** [comment]
That issue has been known for a long time now. Atlas seem to do its own thread detection.

**Comment by Giels** [comment]
perhaps the use flag should be removed for the time being (and thus USE="thread" would be forced)?

**Comment by TheChymera** [comment]
libatlas is no longer provided by Gentoo Science. If the package is still relevant, we could try to bring it back pending a PR.
