### ISSUE TITLE
ugene-1.20.0 qmake fails to find QT5 even though it's installed

### ISSUE THREAD

**Issue by stharward** [gentoo/sci#561]
I have both qt-4.8.6-r4 (Qt4 stable) and qt-5.5.1 (Qt5 keyworded) installed on my system.  When trying to emerge ugene 1.20.0, build fails early with this error:

> Project MESSAGE: Cannot build Unipro UGENE with Qt version 4.8.6
> Project ERROR: Use at least Qt 5.2.1.

Somehow qmake needs to be told to look specifically for Qt5.

**Comment by TheChymera** [comment]
libatlas is no longer provided by Gentoo Science. If the package is still relevant, we could try to bring it back pending a PR.
