### ISSUE TITLE
Compile MRIcroGL with gtk3 support

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#597]
As seen [here](https://github.com/neurolabusc/MRIcroGL/issues/2), MRIcroGL looks horrid with gtk2 under GNOME3. Switching the theme and editing the font size does not do much to hep, it's the GUI elements which are hopelessly down-sclaed. I guess it has to do with me using a HIDPI sreen. 

In any case, I would like to offer optional gtk3 support via a USE flag.

Upstream (linked above) says that could be done by passing the `--ws=gtk3` option to `lazbuild`.

I tried doing that and I am getting [this crash](https://bpaste.net/show/41058b1a5479). Can you help me out? I guess this might also have to do with #596.

The above error I encounter when compiling with `lazarus-1.6.0`. Compiling with the earlier `lazarus-1.2.6` I get [this somewhat different error log](https://bpaste.net/show/3622f69e6168).

**Comment by jlec** [comment]
All should be reported upstream. I have no clue about this language.
