### ISSUE TITLE
blas-reference: abi_x86 incompatibility on prefix

### ISSUE THREAD

**Issue by mschubert** [gentoo/sci#600]
posting here as well for reference:

[[gentoo-users] blas/cblas/lapack do not work on prefix anymore](https://archives.gentoo.org/gentoo-user/message/f579b7160a1eb099e99490c86c48ea38)

```
I'm trying to install blas-reference from the science overlay. This worked
fine in the past, but with the last updates (portage, gcc) it does not pass
dependency checks anymore.

Do you have any pointers on what could be wrong here?

As far as I understand make.profile below, it should have the right IUSE
for the ABI.

Many thanks
Michael

$ emerge --ask -1 blas-reference
!!! The ebuild selected to satisfy "blas-reference" has unmet requirements.
- sci-libs/blas-reference-20151113-r1::science USE="(prefix) (prefix-guest)
-int64 -static-libs -test"

  The following REQUIRED_USE flag constraints are unsatisfied:
    any-of ( abi_x86_32 abi_x86_64 )

  The above constraints are a subset of the following complete expression:
    test? ( ) any-of ( abi_x86_32 abi_x86_64 )

$ eselect profile show
Current /software/prefix/etc/portage/make.profile symlink:
  gentoo_prefix:prefix/linux/amd64

$ eselect profile list
!!! Warning: Failed to determine ${ARCH}. Please submit a bug report.
!!! Error: Cannot determine architecture
!!! Error: Failed to get a list of valid profiles
exiting

$ tail -5 /software/prefix/etc/portage/make.profile/make.defaults
MULTILIB_ABIS="amd64"
DEFAULT_ABI="amd64"
ABI="amd64"
IUSE_IMPLICIT="abi_x86_64"
LIBDIR_amd64="lib"
```

**Comment by jlec** [comment]
Currently I have no chance to test in prefix. Perhaps someone else could see what is going on here.

**Comment by kiwifb** [comment]
I haven't been able to install a new prefix recently. I am trying to track down where that `abi_x86_64 abi_x86_32` thing is coming from.

**Comment by mschubert** [comment]
Just tried a new prefix as well, failed at `sys-apps/net-tools-1.60_p20151124144947`.

Not sure if related, but since the last `gcc` upgrade my system is completely broken (that was after the issue above).

**Comment by kiwifb** [comment]
On 03/03/16 11:00, Michael Schubert wrote:
> Just tried a new prefix as well, failed at
> |sys-apps/net-tools-1.60_p20151124144947|.
>
> Not sure if related, but since the last |gcc| upgrade my system is
> completely broken (that was after the issue above).
>

Not sure it is gcc related. It misses symbols
that should be provided by libiconv which is
supposed to be pre-loaded but it isn't happening.

Francois

**Comment by mschubert** [comment]
I'm missing symbols all over. It seems that the linker no longer sets `RPATH` right. (Just FYI, don't think it's the same reason as the ABI issues.)

**Comment by heroxbd** [comment]
Gentoo Prefix on Linux kernel has migrated into libc-based version. Closing.
