### ISSUE TITLE
FSL and graphviz cluster function

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#606]
It appears both `media-gfx/graphviz` and `sci-biology/fsl` try to install `/usr/bin/cluster`. Up until now I [removed the file from FSL](https://github.com/gentoo-science/sci/blob/6d2fe5739e0bf0478db40c4429215e78110b3326/sci-biology/fsl/fsl-5.0.8.ebuild#L131) as I thought it was the same thing coming bundled (since graphviz is an FSL dependency).

This turns out to not be the case. Unfortunately both packages decided to provide a binary with a rather collison-prone name. What's the standard/recommended/most elegant way to deal with this?

@kiwifb

**Comment by jlec** [comment]
The best is to rename ```cluster``` for FSL to e.g. ```cluster-fsl```.

**Comment by kiwifb** [comment]
I agree with jlec. But you may want to also check `fsl` scripts for calls to `cluster` and adjust them on the assumption that they want `cluster-fsl`.

**Comment by TheChymera** [comment]
I am actually thinking `fsl_cluster` would be a better name.

**Comment by kiwifb** [comment]
No objections to the name. I wouldn't think there are strict rules.

**Comment by TheChymera** [comment]
How can I actually rename the file before portage tries to put it into `/usr/bin` ?

I tried replacing [my previous fix](https://github.com/gentoo-science/sci/blob/6d2fe5739e0bf0478db40c4429215e78110b3326/sci-biology/fsl/fsl-5.0.8.ebuild#L131) with

`newbin "${ED}"/usr/bin/cluster fsl_cluster || die`

But now the build fails due to the collision.

**Comment by jlec** [comment]
> newbin "${ED}"/usr/bin/cluster fsl_cluster || die

That doesn't work as you expect. The resulting installation would have both files.

```ebuild
mv "${ED}"/usr/bin/{,fsl_}cluster || die
```

is what you are looking for.

**Comment by TheChymera** [comment]
Ok, so apparently this isnn't done yet. Upstream told me that at least main `featreg`, `slices_summary`, `easythresh`, and `autoaq` call cluster, and would have to be informed on the change - but that I also should try grepping for cluster in the entire source to find other packges which maybe also do that.

it trns out the name "cluster" is used all over the place in the fsl surces. Do you know how I can try to single out the places where this is in fact a function call?

**Comment by kiwifb** [comment]
I actually mentioned that you should do that. `grep -r cluster *` is your friend/enemy. You'll have to sort the hits.

**Comment by TheChymera** [comment]
We currently just rename the function and thus far no issues have been encountered or reported: https://gitweb.gentoo.org/proj/sci.git/tree/sci-biology/fsl/fsl-6.0.2.ebuild#n156
