### ISSUE TITLE
htcondor fails to build with "Error 2"

### ISSUE THREAD

**Issue by amputee-rex** [gentoo/sci#607]
Hi everybody, I am trying to install htcondor in order to enable parallelization for FSL.

I am getting [this build log](https://bpaste.net/show/4e6a36265ca5). Can you help me out?

**Comment by jlec** [comment]
it is downloading during build. That shouldn't happen. I will try to look into it over the weekend.

**Comment by marbre** [comment]
That is also documented in issue #343. I couldn't get rid of fetching external libs and as the make system is a real mess I actually gave up.

**Comment by TheChymera** [comment]
Any updates on this? I'd also be interested in using htcondor with `sci-libs/nipype`.
