### ISSUE TITLE
openblas-9999 fails to compile due to 0.2.11-gentoo.patch

### ISSUE THREAD

**Issue by xfim** [gentoo/sci#628]
It seems that openblas-0.1.11-gentoo.patch can not be appiled due to something related to CONTRIBUTORS.md.rej

``` bash
>>> Preparing source in /var/tmp/portage/sci-libs/openblas-9999/work/openblas-9999 ...
 * Applying openblas-0.2.11-gentoo.patch ...
 1 out of 1 hunk FAILED -- saving rejects to file CONTRIBUTORS.md.rej
  [ !! ]
   * ERROR: sci-libs/openblas-9999::science failed (prepare phase):
   *   patch -p1  failed with /var/tmp/portage/sci-libs/openblas-9999/distdir/openblas-0.2.11-gentoo.patch
   *
   * Call stack:
   *               ebuild.sh, line  133:  Called src_prepare
   *             environment, line 3533:  Called default
   *      phase-functions.sh, line  805:  Called default_src_prepare
   *      phase-functions.sh, line  870:  Called __eapi6_src_prepare
   *             environment, line  220:  Called eapply '/var/tmp/portage/sci-libs/openblas-9999/distdir/openblas-0.2.11-gentoo.patch'
   *             environment, line 1034:  Called _eapply_patch '/var/tmp/portage/sci-libs/openblas-9999/distdir/openblas-0.2.11-gentoo.patch'
   *             environment, line  972:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/sci-libs/openblas-9999/distdir/openblas-0.2.11-gentoo.patch'
   *   isolated-functions.sh, line  117:  Called die
   * The specific snippet of code:
   *              die "$@"
```

Thank you.

**Comment by jlec** [comment]
thanks for reporting. We need to fix the patch.

**Comment by CraigInches** [comment]
The contrib file has changed, you can actually just remove the lines from the patch inserting the contribution statements as they are now in there.

**Comment by xfim** [comment]
Dear @CraigInches. I am not sure if this has been solved with the pull request for the version bump. I am still having the same problem. And removing the lines does not solve it, as every time I try to emerge openblas-9999 a new version of the patch file is downloaded and the one with the deleted contributions overwriten.

So what is the status of the pull request?

Thank you.

**Comment by CraigInches** [comment]
@xfim you need to modify the build to NOT pull the script from the remote location untill that is patched or changed. Unfortunately the file is not in the ebuild so I am not able to patch using github. I am not a gentoo dev so dont have access to host a file for use in the ebuild.

**Comment by xfim** [comment]
OK, I see. Sorry for the misunderstanding. Now it is working, after having commented the PATCH-related sections in the ebuild. This is a temporary workaround but at least it works. Thank you @CraigInches .

**Comment by xfim** [comment]
In my last attempt a few days ago, the problem with 9999 was still there. The bug report can be closed but I am afraid that the problem has not fully been solved. But thank you anyway.

**Comment by heroxbd** [comment]
@xfim Thanks for reporting.  We have removed the -9999 ebuild to save maintenance work and focus on bumping to new versions more quickly.
