### ISSUE TITLE
sci-biology/plinkseq: src_prepare() must re-run protoc

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#648]
I realized the ebuild had a bundled protobuf-2.5.\* library, so I changed the ebuild to drop it, see below.

```
commit 27fe4b6568a7d820178adf8f7b963bfeb79f966e
Author: Martin Mokrejš <mmokrejs@fold.natur.cuni.cz>
Date:   Mon Jul 18 13:03:20 2016 +0200

    sci-biology/plinkseq: zap bundled dev-libs/protobuf; needs more fixes
```

However, I need somebody else to finish the code around

`protoc --cpp_out=. *.proto`

I tried to mimic sci-biology/goby-cpp but somewhat failed. Thank you.

**Comment by TheChymera** [comment]
@mmokrejs are you still interested in updating this ebuild? If not, as it simply will not build, and the ebuild is unlikely to provide good guidelines for current versions, we might have to remove it from the overlay outright.

**Comment by mmokrejs** [comment]
@TheChymera I cannot fix it myself and I think also some of its deps were removed too.

**Comment by TheChymera** [comment]
@mmokrejs I only see 2 deps, and both of them are available-

**Comment by mmokrejs** [comment]
@TheChymera OK, sorry then, I wrote it from top of my head. The goby-cpp thing is gone.

**Comment by TheChymera** [comment]
@mmokrejs np, I know how confusing it gets when spinning multiple ebuild stacks in parallel :)
