### ISSUE TITLE
Update avbin-bin

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#663]
It seems our newest avbin is ancient. Bumping won't help much either since, [after 8.1 avbin seems to no longer distribute tarballs](https://github.com/AVbin/AVbin/downloads). They now distribute an installer executable, which should be run with sudo. Is there any way to make that portage-compatible (run it in a sandbox)?

**Comment by jlec** [comment]
You can run it in an ebuild, but make sure it ends up in $D

**Comment by TheChymera** [comment]
So it seems they have a very strange build system that requires it to be run in a git repo, and that tries to pull stuff from git... over here it fails with:

```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Cleaning up...done
xargs: ./configure: No such file or directory
AVbin: Fatal error: Failed configuring backend.
```

I don't think it's worthwhile to patch it, especially seeing that upstream has ceased development. I think we're not missing out on much if we just continue distributing the binaries until such a time that avbin becomes completely deprecated.

**Comment by TheChymera** [comment]
avbin-bin is no longer distributed by Gentoo Science. If the package is still relevant we could bring it back pending a PR.
