### ISSUE TITLE
ACML Ebuild Broken (It's Bad, Guys)

### ISSUE THREAD

**Issue by leycec** [gentoo/sci#667]
This _is_ a third-party overlay. Functionality is expected to break and probably frequently does. But the valiant ship always sails on. We're all enormously indebted for the intrepid volunteer hours this community donates to the holy matrimony of Gentoo **+** Science.

Nonetheless, a modicum of testing doesn't seem unreasonable. The most recent ACML release on `::science` (`sci-libs/acml-6.1.0.31.ebuild`) is **fundamentally broken.** This ebuild _cannot_ have ever been tested by anyone; in its current decrepitude, it simply doesn't work. If healing these lethal gut wounds proves non-trivial, hard-masking this ebuild until sanitized might be the sound move.
## Breakage? Wut Breakage?

I don't even.
### ACML 5.3.1 Fell Down and Can't Get Up

Before we get to `sci-libs/acml-6.1.0.31.ebuild`, I noted a few suspicious code smells in its predecessor `sci-libs/acml-5.3.1.ebuild`. These are the `${SRC_URI}` and `${KEYWORD}` entries for the latter:

```
SRC_URI="
    amd64? ( ${FCOMP64}
        !gfortran? ( !ifort? ( !open64? ( !pgi? (
                ${URI}/${MYP}-gfortran-64bit.tgz
                int64? ( ${URI}/${MYP}-gfortran-64bit-int64.tgz ) ) ) ) ) )"
KEYWORDS="-* ~amd64 ~amd64-linux"
```

As written, this ebuild keyworded the experimental `~amd64-linux` but provided no corresponding download targets. Does it need to? I'm actually a bit unclear on this point. Documentation is always scarce where Prefix and Alt are concerned. It's likely that the `amd64-linux` profile inherits the `amd64` profile, in which case the test in `SRC_URI` for `amd64?` is merely superfluous rather than harmful. Removing either this keyword or this test seems sensible.

More critically, if the `gfortran` USE flag is disabled, the `gfortran`-specific tarball is downloaded and compiled against anyway. I can't particularly complain about that, however, as the Portage version of ACML suffers the same issue. <sup>_O.K., then._</sup>

A `${REQUIRED_USE}` entry mandating that at least one Fortran USE flag be enabled trivially fixes the latter issue, in which case the insane `!gfortran? ( !ifort? ( !open64? ( !pgi? (` clause above can be entirely eliminated: e.g.,

```
REQUIRED_USE="|| ( gfortran ifort open64 pgi )"
```

Assuming those two fixes are applied, these entries then reduce to:

```
SRC_URI="${FCOMP64}"
KEYWORDS="-* ~amd64 ~amd64-linux"
REQUIRED_USE="|| ( gfortran ifort open64 pgi )"
```

Or, we could just murder this ebuild entirely. :baby: 
### ACML 6.1.0.31: The Ebuild That Time Forgot

That's not _that_ bad. These are the `${SRC_URI}` and `${RESTRICT}` entries for `acml-6.1.0.31.ebuild`, however: 

```
SRC_URI="gfortran? ( ${P}-gfortran64.tgz )"
RESTRICT="strip mirror"
```

**Golly jee whillikers.** The ebuild apocalypse beckons!
- The `${RESTRICT}` entry neglected to include `fetch`, preventing Portage from calling the `pkg_nofetch` phase and hence warning the user that this package requires manual fetching. Unsurprisingly, this results in the following incoherent fatal error at installation time:
  
  ```
   * ERROR: sci-libs/acml-6.1.0.31::science failed (unpack phase):
   *   Nothing passed to the 'unpack' command
  ```
- The `${SRC_URI}` entry is effectively blank when the `gfortran` USE flag is disabled. _uh. wut?_ If ACML 6.1.0.31 hard-requires GNU Fortran, just mandate GNU Fortran by removing the `gfortran` USE flag entirely. I suspect the ebuild author conveniently "forgot" to support any other Fortran compiler, however.

So, what I'm saying is… it never worked.
## Git Blame – Where Are You When We Need You?

I'd submit a pull request addressing these issues – but excuses.

I'm not entirely clear how the development team prefers to handle these sorts of things. I'm also scarce on time, despite having enough to complain, heckle, and pester. <sup>_**Heckling:** the easy choice._</sup>

**Comment by kiwifb** [comment]
Fork the overlay, submit a PR, get it soundly reviewed (you'll get your heckling back) and then someone (i.e. not me) may merge it.

**Comment by marbre** [comment]
Thanks for the report. I assume ACML isn't used widely since it reached its EOL. I only bumped to 6.1 to have a reference if somebody wants to fix the test phase in the clblas ebuild. Anyway, since one has to download the sources to create the manifest, the sources were already present on my system before I could fully test the ebuild. Therefore, the fetch restriction was somehow lost.
As @kiwifb mentioned just send a PR in future, it might save time, since only two lines (three including the copyright) had to be changed.

**Comment by TheChymera** [comment]
ACML is no longer distributed by Gentoo Science. If the package is still relevant we could bring it back pending a PR.
