### ISSUE TITLE
sync is not picking up new virtuals ie blas, lapack etc

### ISSUE THREAD

**Issue by cwharlow** [gentoo/sci#686]
used maint sync -a, also layman -s science. Deleted and readded science overlay, also changed url from anongit.gentoo to the github one, none of which picked up the new virtuals so emerge update is trying to use the virtuals from the normal tree such as virtual/blas-3.6 and the new one from the overlay, virtual/blas-3.6-r100 is not showing up for me although it says my overlay is up to date

**Comment by kiwifb** [comment]
Can you check you have the file? I see you've already gone to the extent of changing the address of the overlay to the github one, Just to check go to `/var/lib/layman/science/` (or your own custom location) and check the output of `git remote -v` to check which git repo it is actually using.

**Comment by kiwifb** [comment]
I should add that I have added 
```
virtual/blas::gentoo
```
to my `package.mask` to avoid any intruder from the main tree on my system.

**Comment by cwharlow** [comment]
still showing 

> # git remote -v
origin  git://anongit.gentoo.org/proj/sci.git (fetch)                                                                                                                                        
origin  git://anongit.gentoo.org/proj/sci.git (push) 

but I guess nothing has changed yet so there has been no new sync? I don't know if that will change it or revert. Not sure how to readd with the github git url vs the anongit.gentoo one. I only know how to manually change it in the layman.conf file in /etc/portage/repos.conf

Thanks, I will mask that as well, thought about that myself

**Comment by cwharlow** [comment]
I could also manually put the ebuilds for virtual/blas, virtual/cblas and virtual/lapack in my local overlay until it gets picked up. I just watch those carefully because once I accidentally reverted one or more of them back (or possibly eselect package) to the regular gentoo tree and it borked the all my symlinks for the alternatives like openblas and atlas

**Comment by olifre** [comment]
Looking at the commit log here and https://gitweb.gentoo.org/proj/sci.git/log/ it seems the last successful sync was done by @jlec sometime around 21.9. . 
Both repos have seen commits since then, so I'd guess instead of switching repo URI manually and risking merge conflicts you are best off waiting a bit for the next sync (and until then use local repo / masking).
