### ISSUE TITLE
Selecting openblas as cblas provider creates no symlink

### ISSUE THREAD

**Issue by marbre** [gentoo/sci#704]
Selecting `cblas-reference` or `atlas` as cblas provider via `eselect cblas set ${num}` creates the symlink `/usr/include/cblas.h`, pointing to `/usr/include/refblas/cblas.h` and `/usr/include/atlas/cblas.h`, respectively. `openblas` doesn't, but therefore it is providing a _pkgconfig_ file. What is the indented behavior in this case? I have currently trouble when installing `arrayfire` on a system that is not using `atlas`.

**Comment by kiwifb** [comment]
There used to be a link in the past, but even with the link you needed `CFLAGS` from pkgconfig because `openblas`' `cblas.h` points to some other headers that are installed in `/usr/include/openblas`. The intended behavior is that you should use pkgconfig. If `arrayfre` supports building against `atlas` in a non standard location there should be way to coerce it.

**Comment by marbre** [comment]
Thanks for your reply. Actually, openblas is deteced using pkconfig with some code I added to arrayfire's `FindCBLAS.cmake` module some time ago. However, the path to the libraries is set correctly, but the path to the includes is not. Seems that I have to fix this.

I currently try to understand the intended behaviour, that is why I opened the issue. I assume for openblas it is clear that the pkconfig phase in the cmake module needs to be fixed. However, this is different `cblas-reference`. There is a symlink and no pkgconfig file is provided. The header is therefore found at `/usr/include/cblas.h` by some other logic. Including just `/usr/include/cblas.h` and adding `/usr/include` to the include path seems not sufficient, as the build fails. Actually `cblas.h` includes `"cblas_mangling.h"`, located at `/usr/include/refcblas`, which is not in the include path. Any suggestion how to handle this?

**Comment by kiwifb** [comment]
`cblas-reference` does have a `.pc` file and it should be linked to `cblas.pc` when eselected. You should have `/usr/lib{,64}/pkgconfig/refcblas.h` installed. If not there is an install problem.

Like for `openblas` this is a reason why `cblas.pc` needs to be used. If you are missing the `cblas.pc` file with any cblas implementation in Gentoo there is a problem.

**Comment by kiwifb** [comment]
Actually, is this cblas-reference from the overlay or the main tree?

**Comment by marbre** [comment]
20151113-r100 from the overlay.

**Comment by kiwifb** [comment]
I do have a `pc` file for it here and it is properly linked when I `eselect cblas set reference`.

**Comment by marbre** [comment]
Okay I finally fixed the FindCBLAS.cmake module in arrayfire. Changes will be merged upstream and are currently applied with commit https://github.com/gentoo-science/sci/commit/a2fd90ae05dcc27d04772022a8563de2a9da5ff0 to the ebuild in the overlay.

By now, I actually think it is even better to remove the `/usr/include/cblas.h` symlink. Using `cblas-reference`, the compilation of the code
```C
#include <cblas.h>

int main() {
	return 0;
}
```
results in
```
~/tmp $ gcc cblas-test.c -o cblas-test
In file included from cblas-test.c:1:0:
/usr/include/cblas.h:27:28: fatal error: cblas_mangling.h: No such file or directory
 #include "cblas_mangling.h"
                            ^
compilation terminated.
```
Thus you have to include `/usr/include/refcblas/` anyway.

**Comment by kiwifb** [comment]
Yes in most case you need the right include directory. `atlas` is an exception in that regard.

**Comment by marbre** [comment]
Thus should we drop the symlinks from `cblas-reference` and maybe also `openblas`?

**Comment by kiwifb** [comment]
I guess it depends on the amount of work involved. Yes removing the link make things consistent and insure we do not accidentally include `cblas.h` which can be bonus in some packages. But I am not sure we can make that decision, just the two of us.

**Comment by marbre** [comment]
To ask at least some of the sci members.. @SoapGentoo @jlec Your opinion on removing the symbolic link `/usr/include/cblas.h`?

**Comment by mmokrejs** [comment]
Please also check whether broken symlinks exist on your system after any test changes. I do have:

```
$ symlinks -r /apps/ | grep dangling 
dangling: /apps/gentoo/usr/lib64/libblas.a -> blas/reference/libblas.a
dangling: /apps/gentoo/usr/lib64/liblapack.a -> lapack/reference/liblapack.a
dangling: /apps/gentoo/usr/lib64/libcblas.so -> blas/reference/libcblas.so
dangling: /apps/gentoo/usr/lib64/libcblas.a -> blas/reference/libcblas.a 
dangling: /apps/gentoo/usr/include/cblas_test.h -> ../lib64/blas/reference/cblas_test.h
dangling: /apps/gentoo/usr/include/cblas_mangling.h -> ../lib64/blas/reference/cblas_mangling.h
dangling: /apps/gentoo/usr/include/cblas_f77.h -> ../lib64/blas/reference/cblas_f77.h
```

I have:
sci-libs/blas-reference-20151113-r100
sci-libs/cblas-reference-20151113-r100
