### ISSUE TITLE
shouldn't .pc files generated by the numeric eclass use ${include,lib}dir?

### ISSUE THREAD

**Issue by kiwifb** [gentoo/sci#709]
I was looking at .pc files generate by `create_pkgconfig` of the numeric eclass and I was a bit surprised to find
```
prefix="/usr"
exec_prefix="/usr"
libdir="/usr/lib64"
includedir="/usr/include"

Name: atlas-blas
Description: atlas atlas-blas
Version: 3.11.38
URL: http://math-atlas.sourceforge.net/
Requires: 
Requires.private: 
Conflicts: 
Libs: -L"/usr/lib64" -L${libdir} -lf77blas 
Libs.private: -L${libdir} -latlas -lm -lpthread
Cflags: -I"/usr/include" -I${includedir}/atlas
```
What I was expecting was
```
prefix="/usr"
exec_prefix="/usr"
libdir="/usr/lib64"
includedir="/usr/include"

Name: atlas-blas
Description: atlas atlas-blas
Version: 3.11.38
URL: http://math-atlas.sourceforge.net/
Requires: 
Requires.private: 
Conflicts: 
Libs: -L${libdir} -lf77blas 
Libs.private: -L${libdir} -latlas -lm -lpthread
Cflags: -I${includedir} -I${includedir}/atlas
```
There are two issues really:
* when calling `create_pkgconfig` the `libs` argument often contains `\${libdir}` when it shouldn't, there is a `libdir` argument for that. Atlas, openblas and gsl but not reference are guilty of this misuse at least.
* `create_pkgconfig` sets `libdir` and `includedir` at the top and then doesn't use the variables, it uses their values directly inside the .pc file which nullify the point of defining them.

**Comment by heroxbd** [comment]
What is the output of `pkg-config atlas-blas --libs`?  pkg-config should strip the default system search paths.  I don't think `--libdir` is usually defined by pkg-config.

**Comment by kiwifb** [comment]
Well, I changed hardware since then, and I don't have atlas currently installed. But you are correct, unless you set `PKG_CONFIG_ALLOW_SYSTEM_{CFLAGS,LIBS}` those are stripped. 
If you use autotools you can set any kind of autotools variables in the .pc file for free or almost. While `libdir` is not usually an output of `pkg-config` you can define all kinds of variables inside a .pc file to simplify your life. Of course you can ask `pkg-config` about any variable in a .pc file with `--variable=` and if it exists, you'll get an answer.

And while `--libdir` is not standard for `pkg-config`, `--libs-only-L` is.

I think the current implementation in the `numeric` eclass and its use in several ebuild is a bit ad hoc and has not been properly planned. While stuff like `/usr/lib64` is usually stripped, it doesn't hurt and is consistent with other well formatted .pc files.

**Comment by heroxbd** [comment]
Yes, indeed. Thanks a lot for your input.

**Comment by heroxbd** [comment]
Do you know how should .pc files be quoted?

How to deal with the case when libdir contains white space characters?

**Comment by kiwifb** [comment]
I am guessing variable names should be quoted if you are worried about space characters. But I haven't seen any generated .pc files (apart from the one generated by the numeric eclass) with quotes on variables. The man page avoids the subject completely.
Make me feel like conducting a scientific experiment to find out...

**Comment by heroxbd** [comment]
I have found from the [openBSD man page](http://man.openbsd.org/OpenBSD-5.3/man1/pkg-config.1) that

> pkg-config does not go to great lengths to try to fix whitespace abuse. Whitespace in Libs and Cflags lines that are escaped using \ are treated correctly. But strings enclosed in quotation marks that contain whitespaces are not.

**Comment by kiwifb** [comment]
That's rather more difficult to support. As far I can think, we only care about space for prefix. In that case since quotation marks do not work, we may already be in a broken situation unless prefix deals with it already, somehow.

**Comment by heroxbd** [comment]
Nod. I think we can move on to fix this issue and deal with extreme cases of Prefix later.

**Comment by mmokrejs** [comment]
BTW, would somebody have the time to investigate the pkg-config related issue here?
https://bugs.gentoo.org/show_bug.cgi?id=601366 Downstream apps do not detect properly CFLAGS because of this if I remeber right. I suspect some change in behavior in never version of pkg-config causing that.
