### ISSUE TITLE
sci-libs/libfac failing compile

### ISSUE THREAD

**Issue by soleera** [gentoo/sci#727]
Might just be an issue on my setup but it would be good if someone else could check just in case;

emerging libfac fails at the compilation phase:
`c++ ... -fno-implicit-templates -I./factor -I./charset -I. -I./factor -I/usr/include   -DHAVE_CONFIG_H  -c factor/Factor.cc -o OPTOBJ/Factor.o` 
is followed by 
`Fatal error: can't create OPTOBJ/Factor.o: No such file or directory`
this occurs for SqrFree.o as well.

I did manage to successfully emerge the package by manually issuing those commands and then continuing with the rest of the ebuild, so everything else seems ok.

**Comment by kiwifb** [comment]
This is a parallel make issue. The folder `OPTOBJ`  hasn't been created yet. Try to build with `MAKEOPTS="-j1"`.
This and `factory` are most likely clashing with `singular` 4 and over.

**Comment by soleera** [comment]
That makes sense, thanks for letting me know

**Comment by kiwifb** [comment]
If we keep libfac in the overlay the parallel build problem has to be addressed in the ebuild. This is a valid issue, I am re-opening.

**Comment by TheChymera** [comment]
@kiwifb the only currently available version of `sci-libs/libfac`, `3.1.1` is masked due to unavailable sources: https://gitweb.gentoo.org/proj/sci.git/tree/profiles/package.mask#n149

Is there any interest in bringing this or a more recent version back?

**Comment by kiwifb** [comment]
No. That, omalloc and factory are parts of singular. At some point there was some unbundled development of bits of singular upstream but this has stopped. All three should really be removed.

**Comment by TheChymera** [comment]
Thanks :) Removed as per https://gitweb.gentoo.org/proj/sci.git/commit/?id=5aa51d487d13d5cd22f5111f355c1814fa24e23b and preceding commits.
