### ISSUE TITLE
amdapp does not link libs and includes properly 

### ISSUE THREAD

**Issue by fab128** [gentoo/sci#729]
I've installed dev-util dev-util/amdapp-3.0-r1 on my system. However all the installed libs and includes are not seen by my other applications since they get installed under /opt/AMDAPP/ tree. 

They do not get linked from the standard /usr tree while they should according to eselect opencl:

# eselect opencl list
Available OpenCL implementations:
  [1]   amd *

All includes in /usr/include/CL are linked to /usr/lib64/OpenCL/global/include/CL provided by eselect-opencl instead of /opt/AMDAPP/include
All openCL libs in /usr/lib64 are linked to /usr/lib64/OpenCL/vendors/amd provided by ati-drivers instead of /opt/AMDAPP/lib/x64_64/

**Comment by TheChymera** [comment]
@fab128 sorry for the late reply. Gentoo Science has suffered a period of disrepair over the past 3 years, we're working hard to get it back up to scratch. Amdapp has currently been dropped, but we would be very happy to bring it back pending a PR from an interested mainatiner.
