### ISSUE TITLE
media-gfx/brlcad fails during configuration

### ISSUE THREAD

**Issue by ForceFaction** [gentoo/sci#748]
> Performing C SOURCE FILE Test QUNUSED_ARGUMENTS_C_FLAG_FOUND failed with the following output:
Change Dir: /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2_build/CMakeFiles/CMakeTmp

>Run Build Command:"/usr/bin/gmake" "cmTC_58086/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_58086.dir/build.make CMakeFiles/cmTC_58086.dir/build
gmake[1]: Entering directory '/var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2_build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_58086.dir/src.c.o
/usr/bin/x86_64-pc-linux-gnu-gcc   -I/usr/local/include   -march=native -O2 -pipe -w -pipe -fno-strict-aliasing -fno-common -fexceptions -DQUNUSED_ARGUMENTS_C_FLAG_FOUND   -Qunused-arguments -o CMakeFiles/cmTC_58086.dir/src.c.o -c /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2_build/CMakeFiles/CMakeTmp/src.c
x86_64-pc-linux-gnu-gcc: error: unrecognized command line option '-Qunused-arguments'
gmake[1]: *** [CMakeFiles/cmTC_58086.dir/build.make:66: CMakeFiles/cmTC_58086.dir/src.c.o] Error 1
gmake[1]: Leaving directory '/var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2_build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:126: cmTC_58086/fast] Error 2

>Source file was:
int main(void) { return 0; }
Performing C++ SOURCE FILE Test QUNUSED_ARGUMENTS_CXX_FLAG_FOUND failed with the following output:
Change Dir: /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2_build/CMakeFiles/CMakeTmp

That typo `unrecognized command line option '-Qunused-arguments'` comes 3-4 times in a row and lets the build fail ... how to solve this ?

**Comment by AndrewAmmerlaan** [comment]
Does this still occur in the latest version? If not please close this issue
