### ISSUE TITLE
There's both a sci-libs/libmed as well as a sci-lib/med package in this overlay

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo/sci#750]
See title, should probably not be the case :)

- libmed (newer) https://github.com/gentoo-science/sci/blob/master/sci-libs/libmed/
- med (older) https://github.com/gentoo-science/sci/blob/master/sci-libs/med/med-2.3.6.ebuild

**Comment by AndrewAmmerlaan** [comment]
This has been fixed in: https://github.com/gentoo/sci/commit/36e8e49dd334775b3ed1a5b5684a9fd94931969d#diff-f9184ace42cf4de36cb880e6c423614e4a6e138233869266132e089b10ef3f3b
