### ISSUE TITLE
update to app-admin/eselect-1.4.9-r100::science

### ISSUE THREAD

**Issue by hsk17** [gentoo/sci#761]
app-admin/eselect of main gentoo tree got an update to 1.4.9 (and prefix takes and installs that), so an update to app-admin/eselect-1.4.9-r100::science is needed

see attached eselect-1.4.9-r100.ebuild (sync'ed to main gentoo and patched to the needs of science overlay) and eselect-1.4.9-alternatives.patch (trivial changes to eselect-1.4.8-alternatives.patch so it fits eselect-1.4.9)

[eselect-1.4.9-r100.ebuild.txt](https://github.com/gentoo-science/sci/files/864865/eselect-1.4.9-r100.ebuild.txt)
[eselect-1.4.9-alternatives.patch.txt](https://github.com/gentoo-science/sci/files/864866/eselect-1.4.9-alternatives.patch.txt)

**Comment by gagern** [comment]
Got hit by this as well. Can we get the ebuilds which use `alternatives-2.eclass` to depend on the patched version of eselect? Perhaps put the patch behind a USE flag, enabled by default, and have the eclass add a dependency on this? That way portage would prevent eselect upgrades unless they included this USE flag.

**Comment by kiwifb** [comment]
We should really document and provide some `keyword` and `mask` files for the overlay, like the kde overlay does for example.
I don't hit anymore because I have put `app-admin/eselect::gentoo` in `package.mask` but we should provide a file to use.

**Comment by devurandom** [comment]
I think this is already fixed -- 1.4.10-r100 is available in the science overlay. However, in the meantime Gentoo progressed to 1.4.12, which is not yet available in the science overlay (#850). Would it maybe be possible to merge the science overlay changes upstream, in order to reduce these kind of issues in the future?

**Comment by heroxbd** [comment]
Please migrate to the eselect-ldso framework in ::gentoo.  cf. https://wiki.gentoo.org/wiki/Blas-lapack-switch
