### ISSUE TITLE
Multiple warnings, fatal error configuring media-gfx/brlcad-7.24.2 with dev-util/cmake-3.7.2

### ISSUE THREAD

**Issue by jhardin-impsec** [gentoo/sci#763]
Multiple warnings and one fatal error during configuration.
dev-util/cmake-3.7.2
media-gfx/brlcad-7.24.2

See attached build logs:
[build.log.gz](https://github.com/gentoo-science/sci/files/870994/build.log.gz)
[CMakeOutput.log.gz](https://github.com/gentoo-science/sci/files/870995/CMakeOutput.log.gz)
[CMakeError.log.gz](https://github.com/gentoo-science/sci/files/870996/CMakeError.log.gz)

Relevant bit:
```
...{snip}...
-- Found Threads: TRUE  
CMake Warning (dev) at CMakeLists.txt:386 (CMAKEFILES):
  A logical block opening on the line

    /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2/misc/CMake/BRLCAD_CMakeFiles.cmake:85 (if)

  closes on the line

    /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2/misc/CMake/BRLCAD_CMakeFiles.cmake:87 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindThreads.cmake:215 (add_library)
  CMakeLists.txt:1431 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:467 (_message):
  Attempting to ignore non-existent file INTERFACE, in directory
  /var/tmp/portage/media-gfx/brlcad-7.24.2/work/brlcad-7.24.2
Call Stack (most recent call first):
  misc/CMake/BRLCAD_CMakeFiles.cmake:141 (message)
  CMakeLists.txt:386 (CMAKEFILES)
  /usr/share/cmake/Modules/FindThreads.cmake:215 (add_library)
  CMakeLists.txt:1431 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by ArifRoktim** [comment]
I can confirm this. Anyone know any solutions?

**Comment by AndrewAmmerlaan** [comment]
Does this still occur in the latest version? If not please close this issue

**Comment by jhardin-impsec** [comment]
The current `media-gfx/brlcad-7.32.0::science` ebuild requires `<dev-lang/tcl-8.6:0/8.5`, and `dev-lang/tcl-8.5.17-r1::science` cannot be slotted with `dev-lang/tcl-8.6.11` from the main gentoo repo, which has no version of `dev-lang/tcl-8.5` available at all. (The same holds for tk, probably.)

From this, it looks to me like `media-gfx/brlcad` cannot be built on a current Gentoo install unless you mask tcl/tk from the main repo entirely.

I don't need brlcad badly enough to invest the time to chase those downgrades around however deeply they may cascade, or see whether brlcad will build and work with tcl/tk 8.6.x; sorry. Somebody else will have to report whether the current brlcad ebuild builds successfully if tcl/tk is downgraded, or try out brlcad with tcl/tk 8.6.

**Comment by jhardin-impsec** [comment]
The `media-gfx/brlcad-7.32.0` ebuild should be updated to use tcl/tk 8.6, as the 7.32 release notes state:

* upgraded Tcl/Tk from 8.5.19 to 8.6.10 - Cliff Yapp

see https://sourceforge.net/projects/brlcad/files/BRL-CAD%20Source/7.32.0/
