### ISSUE TITLE
dobin error of nwchem-6.6_p27746-r2

### ISSUE THREAD

**Issue by zhenghao87** [gentoo/sci#770]
=====Error message: START======
Output written on userpdf.pdf (318 pages, 161159 bytes).
Transcript written on userpdf.log.
make[1]: [GNUmakefile:48: pdf] Error 1 (ignored)
make[1]: Leaving directory '/var/tmp/portage/sci-chemistry/nwchem-6.6_p27746-r2/work/nwchem-6.6/doc/user'
>>> Source compiled.
>>> Test phase [not enabled]: sci-chemistry/nwchem-6.6_p27746-r2

>>> Install nwchem-6.6_p27746-r2 into /var/tmp/portage/sci-chemistry/nwchem-6.6_p27746-r2/image/ category sci-chemistry
!!! dobin: bin/LINUX64/nwchem does not exist
 ^[[31;01m*^[[0m ERROR: sci-chemistry/nwchem-6.6_p27746-r2::science failed (install phase):
 ^[[31;01m*^[[0m   dobin failed

=======Error message: END=====

output of emerge -pqv '=sci-chemistry/nwchem-6.6_p27746-r2::science'

[ebuild  N    ] sci-chemistry/nwchem-6.6_p27746-r2  USE="doc examples nwchem-tests openmp -blas -cuda -infiniband -int64 -lapack -mrcc -python -scalapack" PYTHON_TARGETS="python2_7"

[output of emerge info.txt](https://github.com/gentoo-science/sci/files/895563/output.of.emerge.info.txt)

**Comment by TheChymera** [comment]
newchem is no longer distributed by Gentoo Science. If the package is still relevant we could bring it back pending a PR.
