### ISSUE TITLE
sci-physics/abinit ebuild problems

### ISSUE THREAD

**Issue by mekosmowski** [gentoo/sci#811]
The most recent ebuild for abinit is version 7.10.4.  This ebuild failed with a fetch failure.  The only upstream 7.10 tarball available for download is 7.10.5.  Also, the expected upstream path to the tarball does not reflect current reality.  I was able to rectify the fetch error and build most of the package by changing the name of the ebuild file and fixing the path, as given here: https://paste.pound-python.org/show/DjfIDI9hLTHwT6CUuspA/

However, this led to a dodoc failure that I was unable to resolve.  Failed build details: https://paste.pound-python.org/show/N6Pmta9CCBHWSi8tWuOj/

Most, but not all, of the specified DOCS are in /var/tmp/portage/sci-physics/abinit-7.10.5/work/abinit-7.10.5/doc

Any assistance will be appreciated.

**Comment by TheChymera** [comment]
abinit is no longer distributed by Gentoo Science. If the package is still relevant we could bring it back pending a PR.
