### ISSUE TITLE
gsl-2.4 version bump

### ISSUE THREAD

**Issue by Telemin** [gentoo/sci#813]
Can we get a version bump to gsl-2.4 please?  This version provides new routines for fixed quadrature integration and hermite polynomials amongst other things (http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS).

As far as I can tell on my own machines, there are no ebuild changes needed.

**Comment by kiwifb** [comment]
Hum, documentation could be an issue I'll have to see if we were doing anything about it before. Happy that the way I patched previous gsl made it easy to go forward to 2.4 ^_^

**Comment by kiwifb** [comment]
PR #815 is now open for review.
