### ISSUE TITLE
Version bump: sci-misc/kaldi-5.2.125

### ISSUE THREAD

**Issue by lkraav** [gentoo/sci#817]
It looks like Kaldi has progressed somewhat http://kaldi-asr.org/doc/versions.html

**Comment by akreal** [comment]
I know but I'm busy with other stuff at the moment. Should find time for it in coming weeks.

**Comment by TheChymera** [comment]
@akreal @lkraav any interest in updating the package?

**Comment by lkraav** [comment]
> @akreal @lkraav any interest in updating the package?

Not enough bandwidth and skill with this ecosystem.

**Comment by akreal** [comment]
> @akreal @lkraav any interest in updating the package?

Not really, I'm not using this package anymore.
