### ISSUE TITLE
sci-geosciences/qgis-9999: update ebuild to use qt5

### ISSUE THREAD

**Issue by equaeghe** [gentoo/sci#819]
qgis is moving to qt5. A starting point for an updated ebuild can be found at https://github.com/a17r/a17rgentoo/tree/master/sci-geosciences/qgis, but at least the `TODO upstream` patches need to be removed or modified (they don't apply anymore). Furthermore, already >=sci-libs/gdal-2.1.3 is needed (cf. https://bugs.gentoo.org/615986). (This is as far as I managed to get.)

**Comment by fedeliallalinea** [comment]
With some change qgis-9999 build and run on my system
- Added **dev-libs/qtkeychain[qt5]** dependency
- Added **dev-python/owslib[${PYTHON_USEDEP}]** dependency ([ebuild in my overlay](https://github.com/fedeliallalinea/gallifrey/tree/master/dev-python/owslib))
- changed gdal dependency in **>=sci-libs/gdal-2.1.3:0=[geos,python?,${PYTHON_USEDEP}]**

Modified ebuild can be found in [my overlay](https://github.com/fedeliallalinea/gallifrey/tree/master/sci-geosciences/qgis)

**Comment by TheChymera** [comment]
`sci-geosciences/qgis` is now distributed by `::gentoo`.
