### ISSUE TITLE
sci-physics/root-9999 root-5.34.13-unuran.patch fails

### ISSUE THREAD

**Issue by nezumi1503** [gentoo/sci#820]
Application of root-5.34.13-unuran.patch fails. See attached files.
[root-5.34.13-unuran.patch.out.log](https://github.com/gentoo/sci/files/1366470/root-5.34.13-unuran.patch.out.log)
[emerge-info.txt](https://github.com/gentoo/sci/files/1366471/emerge-info.txt)

**Comment by olifre** [comment]
There's work on that in #784 , which has sadly not been merged yet.
