### ISSUE TITLE
sci-mathematics/gambit is very outdated

### ISSUE THREAD

**Issue by kiwifb** [gentoo/sci#823]
This is a place holder for me to remind me to work on this in this overlay rather than the sage-on-gentoo one.
gambit-15 (stable) and 16 (dev) should probably be provided.

**Comment by TheChymera** [comment]
@kiwifb is this still active? I see the latest contribution marked on it was in 2015 06c1654398405ecdf768023b65639c3dac7788c7 but it is no longer here. Is there enough interest to bring it back?

**Comment by kiwifb** [comment]
Don't know. Just clean it. If there is interest I can work on it in the sage-on-gentoo overlay then have it migrated in the main tree.
