### ISSUE TITLE
NWChem 6.6_p27746-r2 failed to compile  with cuda (nvidia-cuda-sdk/toolkit 9.0.176)

### ISSUE THREAD

**Issue by gmrandazzo** [gentoo/sci#830]
csd_t_kernels_omp.F:190:0: note: loop peeled for vectorization to enhance alignment
offl_ccsd_t_doubles_l.F:1535:0: note: loop versioned for vectorization because of possible aliasing
offl_ccsd_t_doubles_l.F:1535:0: note: loop peeled for vectorization to enhance alignment
/opt/cuda/bin/nvcc -c -arch=compute_20 -code=sm_20,compute_20 -c  -L/opt/cuda/lib64 -lcublas -lcufft -lcudart -lcuda -lstdc++ -o sd_t_total.o sd_t_total.cu
nvcc fatal   : Value 'compute_20' is not defined for option 'gpu-architecture'
make[3]: *** [../../config/makefile.h:2533: /var/tmp/portage/sci-chemistry/nwchem-6.6_p27746-r2/work/nwchem-6.6/lib/LINUX64/libtce.a(memory.o)] Error 1
make[3]: *** Waiting for unfinished jobs....
ccsd_t_neword.F:135:0: note: loop vectorized
ccsd_t_neword.F:148:0: note: loop vectorized

nvcc --help

--gpu-architecture <arch>                  (-arch)                           
............................................................................................................
............................................................................................................
        Allowed values for this option:  'compute_30','compute_32','compute_35',
        'compute_37','compute_50','compute_52','compute_53','compute_60','compute_61',
        'compute_62','compute_70','sm_30','sm_32','sm_35','sm_37','sm_50','sm_52',
        'sm_53','sm_60','sm_61','sm_62','sm_70'.

so... compute_20 does not exist.

emerge --info

Portage 2.3.13 (python 3.4.5-final-0, default/linux/amd64/13.0/no-multilib, gcc-6.4.0, glibc-2.25-r9, 4.12.12-gentoo x86_64)
=================================================================
System uname: Linux-4.12.12-gentoo-x86_64-AMD_Ryzen_7_1800X_Eight-Core_Processor-with-gentoo-2.4.1
KiB Mem:    32898880 total,  23516848 free
KiB Swap:   62499836 total,  62499836 free
Timestamp of repository gentoo: Fri, 17 Nov 2017 12:00:01 +0000
Head commit of repository gentoo: 116c20ee8fa701f8e9277cea22dd114348df351b
sh bash 4.3_p48-r1
ld GNU ld (Gentoo 2.28.1 p1.0) 2.28.1
app-shells/bash:          4.3_p48-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.3::gentoo
dev-lang/python:          2.7.14::gentoo, 3.4.5::gentoo
dev-util/cmake:           3.8.2::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.4.1-r2::gentoo
sys-apps/openrc:          0.34.7::gentoo
sys-apps/sandbox:         2.10-r4::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.28.1::gentoo
sys-devel/gcc:            6.4.0::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.25-r9::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-extra-opts: 

science
    location: /var/lib/layman/science
    sync-type: laymansync
    sync-uri: https://anongit.gentoo.org/git/proj/sci.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=znver1"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -march=znver1"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="ftp://mirror.switch.ch/mirror/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j16"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl alsa amd64 apng audiofile bash-completion berkdb bindist blas bluethoot bzip2 cairo cdparanoia cdr cli client cracklib crypt cscope css ctype cuda cups curl cxx dbus display-manager dri dv dvb dvd dvdr egl encode ewf ffmpeg fftw fontconfig fortran ftp gdbm giff gimp git glut gnuplot gnutls graphviz grub gsl gstreamer gtk handbook hddtemp iconv icu imagemagick imap imlib inotify ios ipfilter ipv6 java javascript jpeg jpeg2k json kde kdesu lame lapack latex libedit libkms libnotify lm_sensors lzma lzo m17n-lib mad mdnsresponder-compat memcached memlimit mhash minizip mmap mng modplug modules mono motif mozilla mp3 mp4 mpeg mpi mplayer mtp musepack mysql mysqli ncurses netcdf networkmanager nls nntp no-multilib nptl nsplugin ntfs offensive ogg openal openexr opengl openmp openssl pam pcap pch pcmcia pcntl pcre pcre16 pda pdf perl php pic plasma plotutils plymouth png policykit portaudio posix postscript python qt5 quicktime radius rar raw rdp readline recode reiserfs rss ruby samba sasl scanner scripttools sddm sdk sdl seccomp semantic-desktop session sharedmem smp sockets socks5 sound sox spoof-source sqlite ssl svg symlink syslog szip taglib tcl tcpd theora threads tiff tk tokenizer truetype udev udisks ulog unicode unwind upnp usb v4l vaapi vcd videos vim-syntax vnc vorbis wallpapers wavpack webkit webp wifi wmf wxwidgets x264 xattr xcomposite xinerama xkb xml xv xvid zeroconf zlib zsh-completion" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput keyboard mouse" KERNEL="linux" L10N="en" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" POSTGRES_TARGETS="postgres9_5" PYTHON_SINGLE_TARGET="python3_4" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby22" USERLAND="GNU" VIDEO_CARDS="nvidia vesa" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"

Best regards

**Comment by marbre** [comment]
There is no Fermi support in CUDA 9: http://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#unsupported-features
Therefore an older CUDA version has to be used if sm_2.x is desired.

**Comment by gmrandazzo** [comment]
Thanks marbre. i'm able to compile the software however i have some other issues.
