### ISSUE TITLE
sci-libs/libmed-3.1.0 multilib-strict check failed!

### ISSUE THREAD

**Issue by triffid** [gentoo/sci#832]
```
Files matching a file type that is not allowed:
   usr/lib/libmedimport.so
   usr/lib/libmed.so
   usr/lib/libmedC.so
```
Presumably portage wants them to go in /usr/lib64 ?

**Comment by kiwifb** [comment]
Yes.

**Comment by kiwifb** [comment]
cmake build system. There is a special variable to install the libraries in the right place, it is probably not used.
Ideally CMakeList.txt should load the GNUInstallDirs module and use CMAKE_INSTALL_LIBDIR to install libraries rather than CMAKE_INSTALL_PREFIX/lib or things like that.

**Comment by kiwifb** [comment]
Patch example from another project https://github.com/sagemath/sage/blob/master/build/pkgs/cryptominisat/patches/osx_install_nameQA.patch

**Comment by robertmbaker** [comment]
I ran into the issue and came up with a quick pull request with a solution:
https://github.com/gentoo/sci/pull/836

**Comment by the-mozart** [comment]
Hello, the same issue (multilib-strict check failed)  with sci-visualization/forge-3.2.2::science, sci-libs/arrayfire-9999::science.

What variables should I fix to get sweet compilation?

**Comment by kiwifb** [comment]
Well, it is all cmake based so it would be like the example I linked to. You need to patch `CMakeList.txt`, however sometimes the `CMakeList.txt` to patch is not always the top one but in one of the sub-folders.

**Comment by the-mozart** [comment]
OK. Found the solution for sci-visualization/forge-3.2.2::science. 
How could I add a patch to a message?

**Comment by Petross404** [comment]
One can also use the `get_libdir` from [multilib.eclass](https://devmanual.gentoo.org/eclass-reference/multilib.eclass/index.html)

Like this : `-DLIB_INSTALL_DIR=$(get_libdir)` under src_configure. Of course it's better if CMakeLists.txt uses `GNUInstallDirs` like [here](https://github.com/gentoo/sci/pull/836/commits/4bb6c999e7bff3cc739e5b5b5fb896aa2a359704).

**Comment by TheChymera** [comment]
This package has been superseded by sci-libs/med in ::gentoo and consequenty dropped from ::science.
