### ISSUE TITLE
sci-biology/quorum-1.1.1 - wrong bindir value pointing to "${S}"

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#833]
I contributed this ebuild in the past but I need some help improving it. I just found that executing the quorum binary on my Gentoo::RAP install host leads to execution of quorum_create_database which then fails with:

```
/apps/gentoo/usr/bin/quorum_create_database: symbol lookup error: /apps/gentoo/usr/bin/quorum_create_database: undefined symbol: _ZN4Json5ValueC1ERKSs
Creating the mer database failed. Most likely the size passed to the -s switch is too small. at /apps/gentoo/usr/bin/quorum line 155.
```
Inspecting the src_compile() output I came across evidently wrong bindir value being injected (pointing to "${S}"):

`sed -e 's|[@]JELLYFISH[@]|/apps/gentoo/usr/bin/jellyfish|g' -e 's|[@]bindir[@]|/apps/gentoo/var/tmp/portage/sci-biology/quorum-1.1.1/work/quorum-1.1.1|g' -e 's|[@]JF_LIB_PATH[@]||g' -e 's|[@]PACKAGE_VERSION[@]|1.1.1|g' -e 's|[@]JELLYFISH_VERSION[@]|2.2.6|g' < src/quorum.in > quorum && chmod a+x quorum`

I suspect it could be caused by configure using EPREFIX instead of $(DESTDIR)/$(PREFIX) somewhere? @heroxbd , what do you think? Could this error be triggered on Prefix installs? I am just guessing and am not sure I can fix this properly. Please help. Thank you.

**Comment by mmokrejs** [comment]
[build.log.txt](https://github.com/gentoo/sci/files/1502316/build.log.txt)
[config.log](https://github.com/gentoo/sci/files/1502317/config.log)
[config.status.txt](https://github.com/gentoo/sci/files/1502318/config.status.txt)

**Comment by kiwifb** [comment]
It looks like you are missing a library, possibly because you forgot a dependency, or it has been updated. I would think this symbol would have to come from `jsoncpp`. Can you enter the prefix and do `ldd -r /apps/gentoo/usr/bin/quorum_create_database` and post the output. Also when you installed the library would have had to be there I think, since you cannot link unresolved executables.

If you try to emerge it again, does it succeed?

**Comment by mmokrejs** [comment]
```
$ ldd -r /apps/gentoo/usr/bin/quorum_create_database
	linux-vdso.so.1 (0x00007ffff7ffb000)
	libjellyfish-2.0.so.2 => /apps/gentoo/usr/lib64/libjellyfish-2.0.so.2 (0x00007ffff7bad000)
	libpthread.so.0 => /apps/gentoo/lib64/libpthread.so.0 (0x00007ffff7991000)
	libstdc++.so.6 => /apps/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/libstdc++.so.6 (0x00007ffff7592000)
	libgcc_s.so.1 => /apps/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.0/libgcc_s.so.1 (0x00007ffff737b000)
	libc.so.6 => /apps/gentoo/lib64/libc.so.6 (0x00007ffff6fdf000)
	/apps/gentoo/lib64/ld-linux-x86-64.so.2 (0x00007ffff7dda000)
	libm.so.6 => /apps/gentoo/lib64/libm.so.6 (0x00007ffff6cda000)
$
```

I posted the whole build.log but anyway, here are the linking-related lines:

```
/apps/gentoo/bin/bash ./libtool  --tag=CXX   --mode=link x86_64-pc-linux-gnu-g++ -Wall -g -O2 -std=c++0x -O2 -pipe -O2 -pipe -march=native -ftree-vectorize  -Wl,-O1 -Wl,--as-needed -o quorum_create_database src/create_database.o -ljellyfish-2.0 -lpthread -lrt -lpthread 
libtool: link: x86_64-pc-linux-gnu-g++ -Wall -g -O2 -std=c++0x -O2 -pipe -O2 -pipe -march=native -ftree-vectorize -Wl,-O1 -Wl,--as-needed -o quorum_create_database src/create_database.o  /apps/gentoo/usr/lib64/libjellyfish-2.0.so -lrt -lpthread -Wl,-rpath -Wl,/apps/gentoo/usr/lib64 -Wl,-rpath -Wl,/apps/gentoo/usr/lib64
  /apps/gentoo/bin/bash ./libtool   --mode=install /apps/gentoo/usr/bin/install -c quorum_error_correct_reads quorum_create_database merge_mate_pairs split_mate_pairs '/apps/gentoo/var/tmp/portage/sci-biology/quorum-1.1.1/image//apps/gentoo/usr/bin'
```

I think the error message came from some child process, because the tool itself executes, for example:

`quorum_create_database -t 1 -s 10 -b 7 -m 24 -q 10 -o quorum_mer_db.jf file.fastq`

I suspect the cause in perl wrapper called quorum which should give out at least more detailed error messages.
