### ISSUE TITLE
libmed build issue

### ISSUE THREAD

**Issue by j000** [gentoo/sci#842]
Is it just me, or libmed didn't build on new profile?

My fix:
```
diff -Naur med-3.1.0_SRC/src/2.3.6/ci/MEDequivInfo.c med-3.1.0_SRC.fixed/src/2.3.6/ci/MEDequivInfo.c
--- med-3.1.0_SRC/src/2.3.6/ci/MEDequivInfo.c   2015-09-07 18:55:38.000000000 +0200
+++ med-3.1.0_SRC.fixed/src/2.3.6/ci/MEDequivInfo.c     2017-12-16 15:15:23.698832161 +0100
@@ -24,7 +24,7 @@
 #include <stdlib.h>

 int
-MEDequivInfo(int fid, char *maa, int ind, char *eq, char *des)
+MEDequivInfo(med_idt fid, char *maa, int ind, char *eq, char *des)
 {
   med_idt eqid;
   med_err ret;
```

**Comment by TheChymera** [comment]
@j000 apologies for the late reply. Gentoo Science has experienced a lack of access rights for proper maintainership over the past 2 years. We are hard at work trying to get it up to scratch.

The current version of libmed is `3.1.0` and this patch does not apply cleanly. Also, the version without the patch, does not build with the following [build.log](https://github.com/gentoo/sci/files/5332290/build.log).

Would you consider bumping the package to a newer version? Given constrained manpower and an increased impetus to keep the repo in shape, we may need to drop packages which are outdated and/or not easily fixed.

**Comment by TheChymera** [comment]
This package has been superseded by sci-libs/med in ::gentoo and consequenty dropped from ::science.
