### ISSUE TITLE
sci-libs/lapack-reference depends on sys-devel/gcc[fortran] ABI (libgfortran.so.X)

### ISSUE THREAD

**Issue by devurandom** [gentoo/sci#843]
Building sci-libs/arpack, I see the following in config.log:
```
configure:6491: checking for cheev_ in -lreflapack -leigen_blas
configure:6519: x86_64-pc-linux-gnu-gcc -o conftest -pipe -O2 -march=bdver3  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu conftest.c -lreflapack -leigen_blas -leigen_blas   -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../.. -lgfortran -lm -lquadmath >&5
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: libgfortran.so.3, needed by /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_string_len_trim@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_transfer_integer_write@GFORTRAN_1.4'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_stop_string@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_1.4'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_st_write_done@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_st_write@GFORTRAN_1.0'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/libreflapack.so: undefined reference to `_gfortran_etime@GFORTRAN_1.0'
collect2: error: ld returned 1 exit status
```

Apparently sci-libs/lapack-reference depends on sys-devel/gcc[fortran] and was not rebuild when the latter changed ABIs (upgrade from 6.4.0 to 7.2.0).

* [config.log](https://github.com/gentoo/sci/files/1564934/config.log)
* [build.log](https://github.com/gentoo/sci/files/1564938/build.log)

**Comment by kiwifb** [comment]
Yes it happened to a lot of people who reported on bugzilla. If you didn't remove gcc-6.4.0 the installed stuff probably still works at runtime. But that was the same thing at the change of C++ ABI. And I recommend the same solution, put out a message to use revdep-rebuild:
```
revdep-rebuild --library 'libgfortran.so.3' -- --exclude gcc
```

**Comment by kiwifb** [comment]
`arpack` was actually the first package with reported breakage in bugzilla https://bugs.gentoo.org/638384

**Comment by devurandom** [comment]
> Yes it happened to a lot of people who reported on bugzilla. If you didn't remove gcc-6.4.0 the installed stuff probably still works at runtime. But that was the same thing at the change of C++ ABI. And I recommend the same solution, put out a message to use revdep-rebuild:
> 
> ```
> revdep-rebuild --library 'libgfortran.so.3' -- --exclude gcc
> ```

Should this warning go into sys-devel/gcc-7?

**Comment by kiwifb** [comment]
In my opinion yes. Of course, the problem is that not everyone needs fortran.

**Comment by devurandom** [comment]
Well, if we update sys-devel/gcc[fortran], we have to assume that someone might have been using Fortran at some time... If someone would be very picky about not using Fortran, they would set USE=-fortran, wouldn't they?

**Comment by kiwifb** [comment]
Oh, you meant in the ebuild. I thought in "news". Of course a bit of `ewarn` in the ebuild is appropriate

**Comment by devurandom** [comment]
What's required to move this forward?

**Comment by heroxbd** [comment]
This is duplication of https://bugs.gentoo.org/646090.
