### ISSUE TITLE
sci-libs/gmsh-2.16.0 multilib-strict failed

### ISSUE THREAD

**Issue by multiwave** [gentoo/sci#847]
Like many other packages, it also has that multilib (trying to put it in lib instead of lib64) problem with recent portage versions:

```
Files matching a file type that is not allowed:
   usr/lib/libGmsh.so.2.16.0
 * ERROR: sci-libs/gmsh-2.16.0::science failed:
 *   multilib-strict check failed!```

**Comment by kiwifb** [comment]
cmake based, so this can be easily patched as I explained for another package. It is unfortunate that the general fix cannot be included in the generic gentoo cmake definitions.

**Comment by TheChymera** [comment]
This package has been superseded by `sci-libs/gmsh` (currently `4.6.9`) in `::gentoo` and has thus been removed from `::science`. Please check whether this much newer version works and submit a bug via bugzilla if it does not.
