### ISSUE TITLE
sci-libs/tensorflow: new package, ebuilds with IUSE="cuda mpi" need improvements

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#849]
Hi,
  I tried to come up with an ebuild for https://github.com/gentoo/sci/tree/master/sci-libs/tensorflow which is needed by sci-biology/chiron. I added both to science overlay. Would anybody coming across this try to improve them? Seems tensorflow users either have to decide whether they install CPU-capable or GPU-capable executables ... which I assume could be tweaked so that both can coexist. Thank you.

**Comment by markwright** [comment]
Thanks, I improved it in the tensorflow-1.8.0.ebuild to install the C API, optionally the C++ API (not tested), and to build with FEATURES=network-sandbox

**Comment by mmokrejs** [comment]
@markwright Thank you for your efforts but it fails for me. 
[build.log.txt](https://github.com/gentoo/sci/files/1964973/build.log.txt)

**Comment by markwright** [comment]
I wonder if your dev-python/wheel is not built with all the Python versions that
sci-libs/tensorflow is being built with.  I fixed tensorflow-1.8.0 to require
dev-python/wheel[${PYTHON_USEDEP}]

**Comment by mmokrejs** [comment]
I have

```
# emerge -pv dev-python/wheel

[ebuild   R    ] dev-python/wheel-0.30.0::gentoo  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_5 python3_6* -pypy -pypy3 -python3_4" 0 KiB
```

I will update to your new ebuild now.

**Comment by mmokrejs** [comment]
Update to new ebuild triggered:

```
[ebuild   R    ] dev-python/namespace-google-1::gentoo  PYTHON_TARGETS="python2_7 python3_5 python3_6 -pypy -python3_4" 0 KiB
[ebuild     U  ] dev-python/protobuf-python-3.5.2-r1:0/15::gentoo [3.5.2:0/15::gentoo] PYTHON_TARGETS="python2_7 python3_5 python3_6* -python3_4" 0 KiB
[ebuild   R    ] dev-python/absl-py-0.1.13::science  USE="(-test%)" PYTHON_TARGETS="python2_7 python3_5 python3_6* -python3_4" 0 KiB
[ebuild   R    ] dev-python/wheel-0.30.0::gentoo  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_5 python3_6* -pypy -pypy3 -python3_4" 0 KiB
[ebuild     U  ] sci-libs/tensorflow-1.8.0::science [1.7.0::science] USE="cxx%* -cuda -mpi (-opencl%)" PYTHON_TARGETS="python2_7 python3_5 python3_6* -python3_4" 0 KiB
```

**Comment by mmokrejs** [comment]
@markwright Good, it installed successfully. Thank you.

**Comment by TheChymera** [comment]
TF is now provided by the Main Gentoo overlay.
