### ISSUE TITLE
Update patched app-admin/eselect

### ISSUE THREAD

**Issue by Kagami** [gentoo/sci#850]
Gentoo has 1.4.11 in stable and 1.4.12 in testing now so overlay's package version should be bumped too.
Related: https://github.com/gentoo/sci/issues/761

**Comment by devurandom** [comment]
Either this is a duplicate of #761, or #761 should be closed in favour of this. In any case, I suggest to change the summary to a more Gentoo-standard style.

**Comment by Kagami** [comment]
Fixed by https://github.com/gentoo/sci/commit/ac70acdea0ea072525ac9d64ba1b55e8939008cb
