### ISSUE TITLE
setup.py not found when emerging tensorflow

### ISSUE THREAD

**Issue by MalcolmMielle** [gentoo/sci#851]
I'm trying to install tensorflow and I'm hit by the following problem:

```
>>> Emerging (17 of 17) sci-libs/tensorflow-1.5.0::science
 * tensorflow-1.5.0.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                     [ ok ]
>>> Unpacking source...
>>> Unpacking tensorflow-1.5.0.tar.gz to /var/tmp/portage/sci-libs/tensorflow-1.5.0/work
>>> Source unpacked in /var/tmp/portage/sci-libs/tensorflow-1.5.0/work
>>> Preparing source in /var/tmp/portage/sci-libs/tensorflow-1.5.0/work/tensorflow-1.5.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/tensorflow-1.5.0/work/tensorflow-1.5.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/tensorflow-1.5.0/work/tensorflow-1.5.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
/usr/bin/python2.7: can't open file 'setup.py': [Errno 2] No such file or directory
```

Not sure what is happening here

**Comment by mmokrejs** [comment]
Sorry, see https://github.com/gentoo/sci/issues/849

**Comment by MalcolmMielle** [comment]
Don't be sorry :). I quickly looked at the ebuild but I'm not an expert and I can't see anything wrong :/
Does it work on your machine ?

**Comment by mmokrejs** [comment]
It is difficult to me to read through the https://www.tensorflow.org/install/install_sources so I am evidently doing something wrong in the ebuild. Some progress appened thanks to #857.

**Comment by gyroninja** [comment]
Maybe you can complete this one I made from modifying yours: https://paste.pound-python.org/show/3K7F6rlPBWtGUuaw1Whp/
All that is missing is getting it to copy tensorflow_pkg/tensorflow.data/purelib/tensorflow into the sites directory. I tried doing it with python_domodule, but it didn't work since I'm probably doing it wrong. This should be close enough for you to figure out that last detail and get a version to compile. After that you can hook up the use flags to the variables I am exporting before running configure.

**Comment by mmokrejs** [comment]
So you say it needs https://github.com/abseil/abseil-py and https://pypi.python.org/pypi/absl-py ? I do not see any package in portage tree using bazel to learn from the ebuild and I am not really keen on learning this weird build system.

I also saw in "${S}"/BUILD file that by default static libs are created and saw some comments on what arguments users should provide to a linker later on. Somebody more familiar with setuptools (to mimick their behavior) with bazel should step in.

I do not see a tutorial for a python application build either. See https://docs.bazel.build/versions/master/tutorial/cpp.html for some other example.

```
commit d4716dbcfa408f14649ecf58d015c167cb57ded0 (HEAD -> master, origin/master, origin/HEAD)
Author: Martin Mokrejs <mmokrejs@xx>
Date:   Mon Apr 9 18:55:42 2018 +0200

    sci-libs/tensorflow: more tweaks to use bazel build system
    
    It does not build for me and later runs in sandbox violation error.
    Possibly the build system could respect USE=mkl too.
    The autogenerated? BUILD file speaks of static libs being output
    instead of shared libs. It also mentions how to call linker when
    linking 3rd-party apps against these libs.
    
    Package-Manager: Portage-2.3.27, Repoman-2.3.9
```

**Comment by gyroninja** [comment]
It's a trivial ebuild. Here is my dev-python/absl-py/absl-py-0.1.13.ebuild https://paste.pound-python.org/show/n5WxoMgCAdtMAYPDlsfl/

**Comment by gyroninja** [comment]
I am not sure. Make sure that bazel-bin/tensorflow/tools/pip_package/build_pip_package is created. If so maybe it can't find it for some reason.

**Comment by markwright** [comment]
Please try sci-libs/tensorflow-1.8.0, thanks.

**Comment by gyroninja** [comment]
Installed correctly for me. Thanks

**Comment by TheChymera** [comment]
TF is now provided by the Main Gentoo overlay.
