### ISSUE TITLE
sci-biology/amos: bring ebuilds in main tree in sync with overlay

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#854]
Seems there were changes due to qt4 use flags by Andreas Sturmlechner in Mar 2018. The ebuilds in sci overlay should be moved to the main tree and modified to be in sync with those changes.

Does hawkeye still compile after the qt changes/updates? It used to require qt3-support so I wonder if it broke or not.

amos requires gcc-5.4.0, I failed to compile it with 6.3.0 and 7.3.0.

**Comment by TheChymera** [comment]
as per 435cdfbb48bf8efd38cb3198230758bd599aeac3 mosstack was recently removed from Gentoo Science. It seems it has not seen active development for 9 years, and unless this is incorrect, or unless we improve support for legacy software dependency management, it's unlikely to come back.
