### ISSUE TITLE
After installing OpenBLAS, i can't compile mxnet

### ISSUE THREAD

**Issue by lutel** [gentoo/sci#859]
Although I have cblas selected to openblas:
#eselect cblas list
Available providers for cblas:
  [1]   openblas-threads *
  [2]   reference

There are no links to cblas.h created:
#eselect cblas files
/usr/lib64/pkgconfig/cblas.pc

After I switch to "reference", i get symlink /usr/include/cblas.h, but I can't compile mxnet anyway, it throws me an error:

/usr/include/cblas.h:27:28: fatal error: cblas_mangling.h: No such file or directory
 #include "cblas_mangling.h"

With "openblas":
/root/incubator-mxnet/3rdparty/mshadow/mshadow/./base.h:147:23: fatal error: cblas.h: No such file or directory
     #include <cblas.h>

How can I fix this?

**Comment by kiwifb** [comment]
Some header needed by various implementation ar not in `/usr/include/` but a subfolder inside it. cblas.pc should provide you with the necessary cflags to find the headers. If not, that's a bug. What does `pkg-config cblas --cflags` return in both cases?

**Comment by lutel** [comment]
select cblas set reference
-DARCH_X86_64=1 -DOPENBLAS___64BIT__=1 -I/usr/include/refcblas -I/usr/include/openblas

eselect cblas set openblas-threads
-DARCH_X86_64=1 -DOPENBLAS___64BIT__=1 -I/usr/include/openblas

I've added links manually to /usr/lib, after that I could compile mxnet:

# ls -l /usr/lib64/ | grep blas
lrwxrwxrwx  1 root root        25 Mar 19 22:34 libcblas.a -> blas/reference/libcblas.a
lrwxrwxrwx  1 root root        26 Mar 19 22:34 libcblas.so -> blas/reference/libcblas.so
lrwxrwxrwx  1 root root        21 Apr  3 22:59 libopenblas.a -> libopenblas_threads.a
lrwxrwxrwx  1 root root        33 Apr  3 22:58 libopenblas.so -> /usr/lib64/libopenblas_threads.so
lrwxrwxrwx  1 root root        38 Apr  3 19:42 libopenblas_threads.a -> libopenblas_threads_haswellp-r0.2.20.a
lrwxrwxrwx  1 root root        39 Apr  3 19:42 libopenblas_threads.so -> libopenblas_threads_haswellp-r0.2.20.so
lrwxrwxrwx  1 root root        39 Apr  3 19:42 libopenblas_threads.so.0 -> libopenblas_threads_haswellp-r0.2.20.so
-rw-r--r--  1 root root   9214618 Apr  3 19:43 libopenblas_threads_haswellp-r0.2.20.a
-rwxr-xr-x  1 root root   5204136 Apr  3 19:43 libopenblas_threads_haswellp-r0.2.20.so
-rwxr-xr-x  1 root root    112336 Apr  3 13:37 librefcblas.so

**Comment by kiwifb** [comment]
`mxnet` that's not a package in the main tree, is it in the overlay? If not where do you find it?

**Comment by lutel** [comment]
Its not in the portage, currently it could be installed with pip or from sources:

https://mxnet.incubator.apache.org/install/index.html

**Comment by kiwifb** [comment]
The main problem is to find a way for pip to know about the compile flags needed in gentoo. It is not obvious from what I can see and the default assume that you are on ubuntu/debian and ignore any other possibilities.

Looking at the github repo I am also afraid that stuff could be just hard coded.

**Comment by kiwifb** [comment]
I would recommend to get the source with git and try to use cmake to configure and build the thing. Their recommendation is to to use the shipped Makefile but we know from experience that such a Makefile is limited to a number of well tested platforms by upstream - and Gentoo is not one of them.

**Comment by leezu** [comment]
From my experience the cmake mxnet build is not well supported and may have some bugs. This might have changed in the last months, but I suggest you to check the [issues](https://github.com/apache/incubator-mxnet/issues) if you decide to use the cmake build. Also you should open an issue at the mxnet project and we may get the Makefile fixed. I didn't have issues with a mxnet+mkl build on gentoo using the Makefile.
