### ISSUE TITLE
genometools-1.5.7 fails to build

### ISSUE THREAD

**Issue by ghost** [gentoo/sci#860]
...

[compile bool_matrix.o]
src/core/encseq.c: In function ‘gt_specialrangeiterator_reinit_with_startpos’:
src/core/encseq.c:3290:3: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
   if (sri->esr != NULL)
   ^~
src/core/encseq.c:3292:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     sri->esr = gt_encseq_create_reader_with_readmode(encseq,
     ^~~

...

make: *** [Makefile:767: obj/src/core/encseq.o] Error 1

**Comment by mmokrejs** [comment]
Please test the 1.5.10 version added to sci overlay. It should compile with gcc-7 and earlier.

**Comment by Sanrrone** [comment]
Hi, the version 1.5.10 cause the same error for me

**Comment by TheChymera** [comment]
@mmokrejs genometools has been dropped by one of our maintainers, being considered “dead”: https://gitweb.gentoo.org/proj/sci.git/commit/?id=8135299eca5f87441e95d0fdebcc45077f2315a0

Was this by mistake? If so, would you be willing to submit a PR for a working ebuild?
