### ISSUE TITLE
Working tensorflow ebuild

### ISSUE THREAD

**Issue by Barracuda72** [gentoo/sci#862]
This ebuild is based on the one written by gironinja (https://paste.pound-python.org/show/3K7F6rlPBWtGUuaw1Whp/). It's very hackish, uses direct copy command instead of something more clever and DOESN'T provide multi-python installation, it has hardcoded python version (3.6, as seen in resulting wheel filename), doesn't specify dependencies (absl etc) and their versions (>=bazel-0.10.0 etc). It just godmotherdamn WORKS at the end of this all, and that's fine by me.
I'm too lazy to clone repo, make changes, send pull req just for this thing, so I will attach it here. Hope it helps somebody or maybe will be included in overlay after some refinement.
https://pastebin.com/iBaU1u3P

**Comment by mmokrejs** [comment]
```
commit d3e2915edd509df1b98cd0fb8ef70b259af9f9a0 (HEAD -> master, origin/master, origin/HEAD)
Author: Martin Mokrejs <mmokrejs@xx>
Date:   Wed Apr 18 18:52:50 2018 +0200

    sci-libs/tensorflow: more ebuild tweaks (still not working)
    
    - partially incorporate changes from https://github.com/gentoo/sci/issues/862
    
    - respect more USE flags: cuda mpi
    
    - similar addition of opencl use flag doe snot work for me, repoman
      complains with:
    
      IUSE.invalid [fatal]          1
       sci-libs/tensorflow/tensorflow-1.7.0.ebuild: opencl
    
    - try to install into python's site-packages properly (cannot test it)
    
    - the ebuild does not work for me still (SANDBOX VIOLATION due to
      /proc/self/setgroups access)
    
    Package-Manager: Portage-2.3.28, Repoman-2.3.9
```

**Comment by mmokrejs** [comment]
Hi @Barracuda72 Would you mind re-checking if the current ebuild still needs some fixes from your original attempt? Thank you.

**Comment by TheChymera** [comment]
TensorFlow is not provided by the Main Gentoo overlay.
