### ISSUE TITLE
sci-libs/keras ebuild

### ISSUE THREAD

**Issue by Barracuda72** [gentoo/sci#863]
Very simple and another hackish ebuild for Keras (https://keras.io, https://github.com/keras-team/keras). I provided it only with TensorFlow backend, but it can work with Theano (available from main Gentoo repo) or CNTK (some Microsoft sh*t).
https://pastebin.com/RccW5QPu

**Comment by TheChymera** [comment]
keras is now distributed via `sci-libs/tensorflow`.
