### ISSUE TITLE
dev-lang/terra is at release 2015-03-13, but current is 2016-03-25

### ISSUE THREAD

**Issue by kozross** [gentoo/sci#865]
This is several releases behind. Would it be possible to update it a bit?

**Comment by TheChymera** [comment]
The current release is now `1.0.0-beta2`, and the package is being actively developed. While we have recently seen a rise in manpower and better access rights for managing the overlay, we remain spread thin over a large number of packages.

@kozross would you consider taking on maintainership for this package and testing your know-how by attempting a version bump? We are happy to mentor you for this.

**Comment by kozross** [comment]
I'm afraid I'm no longer a daily user of Gentoo at this point.
