### ISSUE TITLE
sci-libs/smart_open and sci-libs/gensim ebuilds

### ISSUE THREAD

**Issue by Barracuda72** [gentoo/sci#866]
Another bunch of simple ebuilds. gensim (https://github.com/RaRe-Technologies/gensim) is an interesting ML library, and smart_open (https://github.com/RaRe-Technologies/smart_open) is it's dependency.

gensim: https://pastebin.com/avViP8H4

smart_open: https://pastebin.com/Yfwe4jMY

**Comment by Barracuda72** [comment]
@TheChymera Thanks for your reply anyway! And thanks for the generous offer.
I'm very sad to hear that you're understaffed. Unfortunately, I'm too busy myself to support this stuff. That ebuild I wrote back two years ago still serves me well (although last time I updated Gensim was in the April this year), so I think you could use it as a starting point.

**Comment by Barracuda72** [comment]
Ah, I forgot. Here's also a patch that removes Cython pinning:
https://pastebin.com/0PzmHEyj
I've used it as a user patch, but it should be probably included in tree with the ebuild.

**Comment by TheChymera** [comment]
@Barracuda72 could you submit a PR with your ebuild? It might be a lot easier than it appears :)
