### ISSUE TITLE
dev-java/jogl-2.2.4: Incorrect bytecode version found

### ISSUE THREAD

**Issue by anaveragehuman** [gentoo/sci#874]
[build.log using oracle-jdk-bin-1.8](https://ptpb.pw/CemK)
[build.log using icedtea-bin-8](https://ptpb.pw/fjcu)

Contents of class-version-verify.log:
```
Bad: 1.8 build/jar/jogl-all-android-natives-linux-amd64.jar jogamp/nativetag/opengl/linux/amd64/TAG.class
CVV: 5
Checked: 1 Good: 0 Bad: 1
```

The issue does not occur if RDEPEND and DEPEND are set to:
```
RDEPEND="${CDEPEND}
        >=virtual/jre-1.8"
DEPEND="${CDEPEND}
        >=virtual/jdk-1.8"
```

**Comment by AndrewAmmerlaan** [comment]
Package masked for removal because last dependency is also masked for removal. Please re-open this Issue if we should keep this package.
