### ISSUE TITLE
Cannot perform BLAS/LAPACK migration

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#878]
For a while now, on multiple machines, I have been unable to perform the [science migration](https://wiki.gentoo.org/wiki/User_talk:Houseofsuns). The process always fails at the same point, namely:

```
FEATURES="-preserve-libs" emerge --oneshot --ask --verbose sci-libs/cblas-reference::science
```

with [this log](http://bpaste.net/show/5ec65825fcd7). 
[Here's an example configuration](http://bpaste.net/show/d00c10097a5a) from one machine.

This is strange because it's not some new package version --- something else must have broken in the stack. Can you help me out? @kiwifb @heroxbd @sfabbro @Doeme

**Comment by Doeme** [comment]
Did you try playing around with `eselect blas`?
Also, might there be interference with the 17.1 gentoo profile? What profile are you using?

**Comment by TheChymera** [comment]
eselect blas list has only one option, I also tried re-selecting it but that did nothing:

```
hioanas@bartholin ~/src/NeuroGentooProject/SharedPrefix $ eselect blas list
Available providers for blas:
  [1]   reference *
```

One of my machines is indeed `17.1`, but all others are not, the machine for which I previously posted `emerge --info`, shows on the first line it is `17.0`, eselect confirms:

```
hioanas@bartholin ~/src/NeuroGentooProject/SharedPrefix $ eselect profile list
Available profile symlink targets:
  [1]   prefix/linux/amd64 (exp)
  [2]   prefix/linux-standalone/amd64 (exp)
  [3]   prefix/linux-standalone/amd64/legacy (exp)
  [4]   default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+ (exp) *
  [5]   default/linux/amd64/17.0/no-multilib/prefix/kernel-2.6.32+ (exp)
  [6]   default/linux/amd64/17.0/no-multilib/prefix/kernel-2.6.16+ (exp)
```

**Comment by Doeme** [comment]
Uh, the same question for LAPACK? Is that properly installed?

**Comment by Doeme** [comment]
Is there a legit reason why emerging sci-libs/cblas-reference::science should pull in anything besides cblas-reference? If not, I'd suggest emerging it with the -O flag.

**Comment by TheChymera** [comment]
`lapack-reference` is not installed, it comes later in the guide. I dod go ahead and installed it. That worked, but it doesn't do aynthing to help with `cblas-reference`.

**Comment by TheChymera** [comment]
It also seems I'm not the first to get [this mysterious error](https://github.com/gentoo/sci/issues/734). What's interesting is that it now happens on all my machines, much as it did to @mmokrejs . And just like for @suhr , the proposed `MAKEOPTS=-j1` fix does not work for me :-/

**Comment by kiwifb** [comment]
In the case of issue #734 we can a left over of an installation of blas from the main tree. This would be why your command has `-preserve-libs`, to remove those. Nevertheless it would be a good idea to check, in particular for left over dead link from eselect-blas.

Next, I would like to know what `pkg-config --libs blas` reports on your system.

**Comment by TheChymera** [comment]
@kiwifb I tried removing all the relevant packages with `emerge -C cblas cblas-reference lapack lapack-referenceblas blas blas-reference`

Also:

```
hioanas@bartholin ~/src/NeuroGentooProject/SharedPrefix $ pkg-config --libs blas-lrefblas
```

**Comment by kiwifb** [comment]
Have you checked for dead symlinks in `usr/lib64`?

**Comment by TheChymera** [comment]
@kiwifb they [all seem to be in working order](http://bpaste.net/show/9809e5fa8ce2).

**Comment by kiwifb** [comment]
I see neither `cblas` or `lapack`. You need both of these for `scipy` that explains how your build fails. The instructions may need tweaking. I would do the unmerge first, then get blas, cblas and lapack (and others if used) installed. And only then I would rebuild the dependencies. That may need a little bit of massaging to put in an actual script.

**Comment by TheChymera** [comment]
ok, I wiped everything `emerge -C cblas cblas-reference lapack lapack-reference blas blas blas-reference eselect eselect-blas eselect-cblas eselect-lapack` again, and followed the guide again, and it fails the exact same way again, but now `blas` and `cblas` libs are indeed present: http://bpaste.net/show/7ee193114943 

there does however seem to be one broken link. You probably can't tell from the pastebin, but both the link and the target here are displayed with white text on a red background:

```
lrwxrwxrwx   1 root root    13 Aug 17 02:51 libcblas.a -> libgslcblas.a
```

**Comment by kiwifb** [comment]
1) that link needs to go
2) `scipy` will still fail to build until you have a lapack again - which is currently absent.

**Comment by TheChymera** [comment]
@kiwifb this has nothing to do with scipy, I'm trying to follow [the well-known migration guide](https://wiki.gentoo.org/wiki/User_talk:Houseofsuns), what I cannot accomplish is:

```
FEATURES="-preserve-libs" emerge --oneshot --ask --verbose sci-libs/cblas-reference::science
```

**Comment by kiwifb** [comment]
Yes that link is a remnant of `eselect-cblas` and may need manual removal. 

As I said the migration guide may need changing. I don't think it is fool-proof. Your original log is for scipy, and it won't ever emerge while lapack is absent.

**Comment by TheChymera** [comment]
oh my, I messed up, it was supposed to be for `cblas-reference` :-/ so much fail. That's probably also why @Doeme  asked regarding something else. Updated now.

**Comment by kiwifb** [comment]
Oh that's different from the original post. Apologies for that. It looks like a problem during cmake configuration phase. It shouldn't look like that. 

Is this still on a prefix? It could be some interference with blas from the host. In `/var/tmp/portage/sci-libs/cblas-reference-20161223-r101/work/lapack-3.7.0-abi_x86_64.amd64_int32/CMakeFiles` I'll need to see the 2 `.log` files and everything in `CMakeTmp` if anything is in there.

**Comment by TheChymera** [comment]
This is on a non-prefix machine (which is, however using a `17.1`) everything before https://github.com/gentoo/sci/issues/878#issuecomment-413733399 was from a prefix machine with a `17.0` profile. I doubt this is related to either, though.

What 2 log files should I show you?

```
localhost ~ # ls /var/tmp/portage/sci-libs/cblas-reference-20161223-r101/work/lapack-3.7.0-abi_x86_64.amd64_int32/CMakeFiles -lah
total 132K
drwxr-xr-x 6 portage portage 4.0K Aug 17 04:16 .
drwxr-xr-x 9 portage portage 4.0K Aug 17 04:16 ..
drwxr-xr-x 4 portage portage 4.0K Aug 17 04:16 3.12.0
-rw-r--r-- 1 portage portage   85 Aug 17 04:16 cmake.check_cache
-rw-r--r-- 1 portage portage  745 Aug 17 04:16 CMakeDirectoryInformation.cmake
-rw-r--r-- 1 portage portage 2.0K Aug 17 04:16 CMakeError.log
-rw-r--r-- 1 portage portage  50K Aug 17 04:16 CMakeOutput.log
drwxr-xr-x 2 portage portage 4.0K Aug 17 04:16 CMakeTmp
drwxr-xr-x 3 portage portage 4.0K Aug 17 04:16 Export
-rwxr-xr-x 1 portage portage 7.7K Aug 17 04:16 feature_tests.bin
-rw-r--r-- 1 portage portage  688 Aug 17 04:16 feature_tests.c
drwxr-xr-x 5 portage portage 4.0K Aug 17 04:16 FortranCInterface
-rw-r--r-- 1 portage portage  529 Aug 17 04:16 lapack-config.cmake
-rw-r--r-- 1 portage portage 9.9K Aug 17 04:16 Makefile2
-rw-r--r-- 1 portage portage 9.3K Aug 17 04:16 Makefile.cmake
-rw-r--r-- 1 portage portage    4 Aug 17 04:16 progress.marks
localhost ~ # ls /var/tmp/portage/sci-libs/cblas-reference-20161223-r101/work/lapack-3.7.0-abi_x86_64.amd64_int32/CMakeFiles/CMakeTmp/ -lah
total 8.0K
drwxr-xr-x 2 portage portage 4.0K Aug 17 04:16 .
drwxr-xr-x 6 portage portage 4.0K Aug 17 04:16 ..
```

**Comment by kiwifb** [comment]
I meant `CMakeError.log` and `CMakeOutput.log`.

**Comment by TheChymera** [comment]
[CMakeError.log](http://bpaste.net/show/03cb85712e23) and [CMakeOutput.log](http://bpaste.net/show/1df36ba37e71)

**Comment by kiwifb** [comment]
Hum... Not much in there in the same folder can you post `lapack-config.cmake` and `Export/lib64/cmake/lapack-3.7.0/lapack-targets-gentoo.cmake`. CMake logs are not quite as verbose as autoconf which makes finding the issue harder, even though I know where things started to go off rails.

**Comment by kiwifb** [comment]
And `CMakeCache.txt` in the parent directory while we are at it.

**Comment by kiwifb** [comment]
There is a distinct possibility that `FindBLAS.cmake`  from cmake 3.12.0 has changed its behavior. I may have to upgrade to check.

**Comment by kiwifb** [comment]
Bingo, `FindBLAS.cmake` from cmake 3.12.x is broken or has changed behavior in a way that breaks the build. This is a much bigger problem than your migration. Packages using that module may need patching.

**Comment by kiwifb** [comment]
Broken I say from the module's own documentation
```
# This module sets the following variables:
#
# ::
#
#   BLAS_FOUND - set to true if a library implementing the BLAS interface
#     is found
#   BLAS_LINKER_FLAGS - uncached list of required linker flags (excluding -l
#     and -L).
#   BLAS_LIBRARIES - uncached list of libraries (using full path name) to
#     link against to use BLAS
#   BLAS95_LIBRARIES - uncached list of libraries (using full path name)
#     to link against to use BLAS95 interface
#   BLAS95_FOUND - set to true if a library implementing the BLAS f95 interface
#     is found
```
But when found via pkg-config
```
if(BLA_PREFER_PKGCONFIG)
  find_package(PkgConfig)
  pkg_check_modules(PKGC_BLAS blas)
  if(PKGC_BLAS_FOUND)
    set(BLAS_LIBRARIES "${PKGC_BLAS_LINK_LIBRARIES}")
    return()
  endif()
endif()
```
It looks like `BLAS_FOUND` is not set. Looking at the code it doesn't look like it is ever set.
On the other hand `CMakeList.txt` for cblas-reference (and lapack-reference since it is the same sources) requires `BLAS_FOUND` 
```
# User did not provide a BLAS Library but specified to search for one
elseif(USE_OPTIMIZED_BLAS)
  find_package(BLAS)
endif()

# Neither user specified or optimized BLAS libraries can be used
if(NOT BLAS_FOUND)
  message(STATUS "Using supplied NETLIB BLAS implementation")
  add_subdirectory(BLAS)
  set(BLAS_LIBRARIES ${LIBNAME})
else()
```
I recommend patching cmake.

**Comment by kiwifb** [comment]
Related https://bugs.gentoo.org/653936

**Comment by kiwifb** [comment]
By the way, I revising my advice from "patching cmake-3.12.x" to "masking >=dev-utils/cmake-3.12.0" until upstream gets its act together.

**Comment by TheChymera** [comment]
@kiwifb ok, `FEATURES="-preserve-libs" emerge --oneshot --ask --verbose sci-libs/cblas-reference::science` now works. Should `>=dev-utils/cmake-3.12.0` be hard masked globally, or is this bug only relevant for science migration? (if the latter, it should be included in the mask list at the start).

**Comment by kiwifb** [comment]
Anything that use FindBLAS from cmake is potentially affected. Not just in this overlay, in the main tree as well most likely. I would hope the mask can be reduced to 
```
=dev-utils/cmake-3.12*
```
and that it will be fixed in the future.

**Comment by TheChymera** [comment]
@kiwifb in any case, I have updated the scripts which me and @Doeme use across multiple machines to include this fix, and on my end they have gotten all the machines which were experencing issues back and running again.

While [a permanent fix remains in limbo](https://github.com/gentoo/sci/issues/805) and seeing that the [original solution](https://wiki.gentoo.org/wiki/User_talk:Houseofsuns) is now no longer working, I think we need to make our scripts available and visible to users and potential users of the overlay. That's [easily done](https://github.com/gentoo/sci#blas-and-lapack-migration) --- but for security and developer accessibility reasons, it would be better to distribute these scripts along with the overlay, rather than link them from somewhere else. Any suggestion regarding where they should be placed in the directory tree?

**Comment by TheChymera** [comment]
Turns out we already have a [scripts folder](https://github.com/gentoo/sci/tree/master/scripts), which seems like a good place to put the [updated and automated LAPACK migration guide](https://github.com/gentoo/sci/blob/master/scripts/lapack-migration.sh).

**Comment by TheChymera** [comment]
@kiwifb any idea if the cmake issue is still active?

**Comment by kiwifb** [comment]
I don't know. I'll add to my growing TODO list.
