### ISSUE TITLE
scilab uses dev-java/batik 1.8

### ISSUE THREAD

**Issue by mehowdude** [gentoo/sci#879]
Basically the issue is that gentoo's repository has dev-java/batik 1.9, but the scilab's ebuild uses only dev-java/batik 1.8.

**Comment by heroxbd** [comment]
Do we need to make a new SLOT for dev-java/batik?

**Comment by cnd** [comment]
current scilab lacks batik:1.8
it's removed from portage here: https://github.com/gentoo/gentoo/commit/559cca9d8919f426d7cb1f7998c8d4e9fa3ee476#diff-fe1fb14a550ca4844dc6fdf71f00003d

either update scilab to newer version and target batik 1.9 or update current ebuild to work with 1.9 or (easiest) add 1.8 removed in mentioned commit to overlay (but 1.8 seems like had some problems) so at least users will be able to build that package.
