### ISSUE TITLE
path_exists is banned

### ISSUE THREAD

**Issue by yusinv** [gentoo/sci#880]
intel common and mkl failed to build

path_exists has been removed.  Please see the following post
 * for a replacement snippet:
 * https://blogs.gentoo.org/mgorny/2018/08/09/inlining-path_exists/
 * ERROR: dev-libs/intel-common-18.0.2.199-r1::science failed (install phase):
 *   path_exists is banned
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_install
 *   environment, line 2947:  Called intel-sdp-r1_src_install
 *   environment, line 1725:  Called path_exists 'opt/intel/documentation_2018'

**Comment by TheChymera** [comment]
This appears to have been fixed in ae4963d44f80465b8f31aab5d8656d00293f5e2f .
