### ISSUE TITLE
gsl from gentoo repository is newer than that in science

### ISSUE THREAD

**Issue by asaparov** [gentoo/sci#883]
gsl from gentoo repository is newer than in this repository, so portage is pulling that in, which pulls in app-eselect/eselect-cblas and conflicts with all my packages installed from this repository.

Is gsl out of date in this repository?

**Comment by kiwifb** [comment]
It seems to be. You should consider using the following instructions https://wiki.gentoo.org/wiki/User_talk:Houseofsuns if you are using blas/lapack from the overlay. In particular you should mask duplicate packages from the main tree. This includes `gsl`. Do you have a particular reason for wanting the latest, apart from it being the latest?

**Comment by asaparov** [comment]
Thanks for the quick response! I'll take a look.

No other reason for me, its just inkscape pulling it in. It would be nice to have the latest versions in this overlay though, especially for people who work with gsl more directly.

**Comment by asaparov** [comment]
The recent update to the gsl package here resolves this issue.
