### ISSUE TITLE
openblas lapack

### ISSUE THREAD

**Issue by leezu** [gentoo/sci#888]
[openblas contains a version of lapack-reference, replacing some of the functions with optimized versions](https://github.com/xianyi/OpenBLAS/issues/203#issuecomment-15296123). It seems that `sci-libs/openblas` does not expose the lapack functions properly. At least I cannot find them in the output of `nm -D /usr/lib64/libopenblas_threads.so`.

Is this intentional? If so, why?

**Comment by kiwifb** [comment]
Yes. Optimized lapack function (similarly to atlas) is a "relatively" new thing in openblas. So right now, no lapack stuff is provided. It also involves non trivial change not just to the openblas ebuild but virtual/lapack and possibly a few other spots. There is also the reLapack thing which is interesting but could be provided to generic lapack as well.
