### ISSUE TITLE
Problems installing =sci-mathematics/petsc-3.10.0

### ISSUE THREAD

**Issue by waebbl** [gentoo/sci#892]
I'm having issues with configuring petsc-3.10.0 as it doesn't find lapack. See https://bugs.gentoo.org/669040

Using blas / lapack from science overlay, as well as the virtuals for them: `=virtual/lapack-3.7-r100` with `=sci-libs/lapack-reference-3.8.0-r100` and `=virtual/blas-3.7-r100` with `=sci-libs/blas-reference-20171112-r100`.

The pointers in `/etc/env.d/alternatives` are all set, no dangling symlink there, the output of `eselect lapack list` and `eselect blas list` both list the reference implementations with no other alternatives to choose from.
`pkg-config --libs lapack` returns `-lreflapack`.

**Comment by ycoudier** [comment]
Hello,
I had the same problem. I think it's because it needs blas in addition to lapack. I added blas to the corresponding pkg-config line
