### ISSUE TITLE
=sci-libs/trilinos-12.12.1-r1 can not be fetched

### ISSUE THREAD

**Issue by waebbl** [gentoo/sci#893]
```
>>> Downloading 'http://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz'
--2018-10-20 00:57:18--  http://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz
Resolving trilinos.org (trilinos.org)... 207.211.63.18
Connecting to trilinos.org (trilinos.org)|207.211.63.18|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz [following]
--2018-10-20 00:57:18--  https://trilinos.org/oldsite/download/files/trilinos-12.12.1-Source.tar.gz
Connecting to trilinos.org (trilinos.org)|207.211.63.18|:443... connected.
ERROR: cannot verify trilinos.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
To connect to trilinos.org insecurely, use `--no-check-certificate'.
!!! Couldn't download 'trilinos-12.12.1-Source.tar.gz'. Aborting.
 * Fetch failed for 'sci-libs/trilinos-12.12.1-r1', Log file:
```

Not sure whether it's a problem on their side, or an issue with gentoo certificates. Couldn't find any reference to "Lets' Encrypt" CA in the certificates. However, when I request the cert with firefox, it say's the certificate is ok, no need to add an exception and I can download and save the cert. Saving it in `/usr/share/ca-certificates` and calling `update-ca-certificates` or directly in `/etc/ssl/certs` does not solve the issue.
Another point which might belong to this. The certificate is new, it was not valid before September 3rd, but the trilinos package was last updated at August 31st.

**Comment by TheChymera** [comment]
@waebbl The current versions of `sci-libs/trilinos` distributed by Gentoo Science are `12.14.1` and `12.18.1`, and the fetch works.
