### ISSUE TITLE
FSLeyes

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#894]
FSLeyes is the new viewer complementing FMRIB's FSL. It depends on a somewhat larger depenency stack of which a number of packages are best tracked in Gentoo proper. The good news is that everything you need to build and run FSLeyes can be obtained from Gentoo proper + Gentoo science + [my overlay](https://github.com/TheChymera/overlay). The bad news is that getting everything up to scratch (and Python3* compatible) still requires a number of things:

- [x] An Rtree bump https://github.com/gentoo/gentoo/pull/10049
- [x] A Python3-compatible wxpython https://bugs.gentoo.org/667318
- [x] Trimesh https://github.com/gentoo/sci/commit/36e8875f19048a64a2cbeacfc020103464f012dc
- [x] fslpy https://github.com/TheChymera/overlay/tree/master/dev-python/fslpy
- [x] fsleyes-props https://github.com/TheChymera/overlay/tree/master/sci-visualization/fsleyes-props
- [x] fsleyes https://github.com/TheChymera/overlay/tree/master/sci-visualization/fsleyes

**Comment by TheChymera** [comment]
@KoalaPulp If you want to help out, depending on your level of expertise (from most difficult to easiest) I would recommend:

* Trying to bump wxpython to 4.0.3. See [the bugzilla discussion](https://bugs.gentoo.org/667318), and [my moxt up-to-date ebuild draft](https://github.com/TheChymera/overlay/tree/master/dev-python/wxpython). The issues here are that the tests do not pass and a lot of the USE flag functionality from the current version has not been ported because I don't understand it.
* Figuring out whether the test suite for fsleyes-widgets [can be run selectively only if gtk2 is available](https://github.com/pauldmccarthy/fsleyes-widgets/issues/1).
* Pull [my overlay](https://github.com/TheChymera/overlay) and test out the currently available fsleyes.

**Comment by TheChymera** [comment]
At long last, the dependencies of FSLeyes have been added to Gentoo Science. @kiwifb would you be interested in testing/reviewing [FSLeyes from my overlay](https://github.com/TheChymera/overlay/tree/master/sci-visualization/fsleyes) before I merge it? There's still [some tests which fail](https://github.com/pauldmccarthy/fsleyes/issues/38) but at least on my machines, the package appears to work ok.

**Comment by kiwifb** [comment]
I cannot do something like that before Monday. That would be just running the test suite.

**Comment by TheChymera** [comment]
@kiwifb no problems, let me know if you find any issues. It's already available to me and my colleagues via my overlay, so next week is perfectly fine, other than the general problem with delays, namely that we both forget about it :)

**Comment by kiwifb** [comment]
Testing this is more involved than I thought because several moving parts have to be installed and tested. I looked at the tests logs you are linking to, I think you are using a newer numpy and possibly matplotlib than were used by the dev. Quite likely a higher version python as well. There is not much you can do apart from really fixing the incriminated code for forward support. Which is not obvious.

**Comment by TheChymera** [comment]
@kiwifb you mean the tests which are skipped in the ebuild? Did you actually encounter issues with usage of the software resulting from this? I am thinking of leaving it as is, if no other tests fail other than the ones already reported to upstream...

**Comment by kiwifb** [comment]
I am not test driving this. I don't have any data or workflow to test. 

I was looking at the logs https://github.com/pauldmccarthy/fsleyes/files/4109518/build.log here and you should provide your version of matplotlib to Paul. If they have automated tests you can ask to see the list of software they install and how.

**Comment by TheChymera** [comment]
We now have FSLeyes.
