### ISSUE TITLE
sci-libs/lapack-reference-3.8.0-r100 installs conflicting /usr/lib64/pkgconfig/blas.pc

### ISSUE THREAD

**Issue by gagern** [gentoo/sci#899]
I have `FEATURES=collision-protect` enabled by default, so even unowned files won't get overwritten. This causes sci-libs/lapack-reference-3.8.0-r100 to fail for me:

```
 * package sci-libs/lapack-reference-3.8.0-r100 NOT merged
 * 
 * Detected file collision(s):
 * 
 *      /usr/lib64/pkgconfig/blas.pc
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * None of the installed packages claim the file(s).
 * 
 * Package 'sci-libs/lapack-reference-3.8.0-r100' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.
```

I tried deleting that file first, but then it fails even earlier:

```
>>> Preparing source in /var/tmp/portage/sci-libs/lapack-reference-3.8.0-r100/work/lapack-3.8.0 ...
!!! Error: /usr/lib64/pkgconfig/blas.pc does not exist
 * ERROR: sci-libs/lapack-reference-3.8.0-r100::science failed (prepare phase):
 *   lapack-reference requires the pkgbuild module blas
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_prepare
 *   environment, line 4684:  Called numeric-int64_ensure_blas_int_support
 *   environment, line 3483:  Called die
 * The specific snippet of code:
 *           $(tc-getPKG_CONFIG) --exists "${blas_module_name}" || die "${PN} requires the pkgbuild module ${blas_module_name}";
```

So I re-merged sci-libs/blas-reference-20171112-r100 and was back to the first error message again. Looking at the files in question:

```diff
--- /usr/lib64/pkgconfig/blas.pc
+++ /var/tmp/portage/sci-libs/lapack-reference-3.8.0-r100/image/usr/lib64/pkgconfig/blas.pc
@@ -1,8 +1,8 @@
 libdir=/usr/lib64
 includedir=/usr/include
 
 Name: BLAS
 Description: FORTRAN reference implementation of BLAS Basic Linear Algebra Subprograms
 Version: 3.8.0
 URL: http://www.netlib.org/blas/
-Libs: -L${libdir} -lrefblas
+Libs: -L${libdir} -lblas
```

Sounds like installing the file lapack-reference wants to install would be inferior to what is already installed. And it feels very confusing that lapack would try to install a package config for blas at all. I guess I'll resolve this for myself by running ebuild manually, and removing the file between install and merge steps.

I've read some similar reports getting directed at https://wiki.gentoo.org/wiki/User_talk:Houseofsuns. I don't have those masks in place, so I checked my system against the packages mentioned therein to confirm I'm not violating any of those, but everything checks out:

* app-admin/eselect-1.4.13-r101::science
* app-eselect/eselect-blas not installed at all
* app-eselect/eselect-cblas not installed at all
* app-eselect/eselect-lapack not installed at all
* virtual/blas-3.7-r100::science
* virtual/cblas-3.7-r100::science
* virtual/lapack-3.7-r100::science
* sci-libs/gsl-2.5::science
* app-doc/blas-docs-3.3::science
* app-doc/lapack-docs-3.3-r1::science
* sci-libs/blas-reference-20171112-r100::science
* sci-libs/cblas-reference-20161223-r101::science
* sci-libs/lapack-reference-3.7.0-r100::science scheduled for update to 3.8.0-r100
* sci-libs/mkl not installed at all

**Comment by gagern** [comment]
I found sci-libs/lapack-reference-3.8.0-r100 did install /usr/lib64/libblas.so as well, despite https://wiki.gentoo.org/wiki/User_talk:Houseofsuns writing it should not exist.

**Comment by gagern** [comment]
I found that since https://github.com/Reference-LAPACK/lapack/commit/5817812eb2aa6fae9a570a3dfc914f083eab228d the replacement in https://github.com/gentoo/sci/blob/fb5df65b4a85dd6450a2a93b454147888eec6a1e/sci-libs/lapack-reference/lapack-reference-3.8.0-r100.ebuild#L56 no longer has the desired effect, since [the line](https://github.com/Reference-LAPACK/lapack/blob/49d96839bce3a70e88d1d241bdc0971ca0331f6d/lapack.pc.in#L9) now starts with `Requires.private:` instead of plain `Requires:`. I guess this might be (part of) the reason why the lapack build compiles and installs its own blas.

I would recommend using patch instead of sed to ensure the desired changes actually apply as intended.

Ping @jlec who [created](https://github.com/gentoo/sci/commit/c4d9ac48f18eab5d44da15e8e8b36eca9d1353de) `lapack-reference-3.8.0-r100.ebuild`.

**Comment by gagern** [comment]
It would seem that this issue here might be related to https://github.com/gentoo/sci/issues/734#issuecomment-439682201 caused by CMake FindBLAS not setting BLAS_FOUND as expected. The fact that the `Requires.private` line does not get edited remains, but the installation of libblas.so as part of lapack-reference disappears once I fix my local CMake.

**Comment by heroxbd** [comment]
Please migrate to sci-libs/lapack from ::gentoo.  cf. https://wiki.gentoo.org/wiki/Blas-lapack-switch
