### ISSUE TITLE
PMASKED packages

### ISSUE THREAD

**Issue by waebbl** [gentoo/sci#900]
Maybe you already noticed, there are a few packages PMASKED this week which are used in some of the science overlay ebuilds.
The packages in question are:
`sci-libs/suitesparse` with an rdep on `sci-mathematics/petsc[sparse]` and `sci-libs/spqr` with an rdep on `sci-libs/suitesparse`. There might be other packages than petsc needing any of them, this is only what I have installed.
Just in case, you want to save the ebuilds before they are gone.

>  Pacho Ramos <pacho@gentoo.org> (11 Nov 2018)
> Completely broken for a long time and uninstallable (#492484, #585516, #586582, #627094, #654548). 
> sci-libs/spqr
> dev-lang/julia
> sci-libs/suitesparse

**Comment by TheChymera** [comment]
These packages are both no longer PMASKED in ::gentoo, which now distributes them instead of ::science. Further, they are no longer dependencies of packages in Gentoo Science.
