### ISSUE TITLE
sci-mathematics/tisean-3.0.1 - file collision with 

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#906]
```
 * Detected file collision(s):
 * 
 * 	/usr/bin/compare
 * 	/usr/bin/cluster
...
 * media-gfx/imagemagick-7.0.8.23:0::gentoo
 * 	/usr/bin/compare
 * 
 * media-gfx/graphviz-2.40.1-r1:0::gentoo
 * 	/usr/bin/cluster
 * 
```

**Comment by TheChymera** [comment]
uh, you don't know half of it. I've seen too many neuroimaging packages which have a `cluster` executable. Generally the way to fix this is to change the name for the function from the lesser-used of the two packages (within reason, at your discretion ^^ ), and always sumbitting an issue to upstream notifying them of the conflict and suggesting the rename be upstreamed.

In any case, again, this package was dropped: https://gitweb.gentoo.org/proj/sci.git/commit/?id=937e76f417b041cc5fb9a9bb92d1849846420c3d Is it worth bringing it back, and if so, would you like to submit a PR for a working ebuild?
