### ISSUE TITLE
Travis CI acts on outdated tree (actually a mix of old+current)

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#909]
Hi,
  when you look into recent Travis CI results you can eventually realize it complains about ebuilds which are either not present anymore in the sci overlay or that it complains about their outdated copies. Well, third, in some case it speaks of current ebuilds, true.

1. For example, `sci-chemistry/burrow-owl/burrow-owl-9999.ebuild` contains no `prefix` so the error

```
 dependency.syntax [fatal]     1
sci-chemistry/burrow-owl/burrow-owl-9999.ebuild: DEPEND: USE flag 'prefix' referenced in conditional '!prefix?' is not in IUSE
```
is plain wrong.

2. The following ebuilds do not exist in current tree:

```
IUSE.missing [fatal]          6
   media-libs/avbin-bin/avbin-bin-7.ebuild: SRC_URI: USE flag 'amd64' referenced in conditional 
'amd64?' is not in IUSE
   sci-astronomy/galfit-bin/galfit-bin-3.0.5.ebuild: SRC_URI: USE flag 'amd64' referenced in conditional 'amd64?' is not in IUSE
   sci-astronomy/starlink-bin/starlink-bin-20130413.ebuild: SRC_URI: USE flag 'amd64' referenced in conditional 'amd64?' is not in IUSE
```

Probably you can find more cases.

**Comment by TheChymera** [comment]
@mmokrejs CI has now been fixed, sadly, as discussed previously, at the cost of losing quite a few packages. Apologies for that, but it was the only solution given the availability of manpower :(
