### ISSUE TITLE
OpenMPI 4.0.0+ breaks sci-libs/scalapack

### ISSUE THREAD

**Issue by JM1** [gentoo/sci#911]
Scalapack 2.0.2 fails to compile with OpenMPI 4.0+ (from science overlay) because [`MPI_Type_struct` has been removed and replaced by `MPI_Type_create_struct`](https://www.open-mpi.org/faq/?category=mpi-removed#mpi-1-mpi-type-struct). Please add this [patch](https://github.com/gentoo/sci/files/3058318/replace-removed-MPI_Type_struct.patch.txt) to [scalapack-2.0.2-r1.ebuild](https://github.com/gentoo/sci/blob/master/sci-libs/scalapack/scalapack-2.0.2-r1.ebuild). Thanks :)

**Comment by JM1** [comment]
Or maybe add `--enable-mpi1-compatibility` to [OpenMPI 4.0.x ebuild](https://github.com/gentoo/sci/blob/master/sys-cluster/openmpi/openmpi-4.0.1.ebuild)? 

BTW: valgrind (+mpi flag) also does not build without MPI1..

**Comment by TheChymera** [comment]
@JM1 OpenMPI is now provided by `::gentoo`.
