### ISSUE TITLE
sci-libs/scalapack:  cmake-utils_src_prepare has not been run

### ISSUE THREAD

**Issue by JM1** [gentoo/sci#912]
`emerge --ask --verbose sci-libs/scalapack` prints a warning:
```
* cmake-utils_src_prepare has not been run, please open a bug on https://bugs.gentoo.org/
```

Due to this, [user patches](https://wiki.gentoo.org/wiki//etc/portage/patches) are not applied during build. This [patch](https://github.com/gentoo/sci/files/3058337/sci-libs_scalapack_scalapack-2.0.2-r1.ebuild.patch.txt) adds the required statement.

**Comment by TheChymera** [comment]
@JM1 with the current version distributed by Gentoo Science, `=sci-libs/scalapack-2.1.0`, this warning no longer appears.
