### ISSUE TITLE
sys-cluster/openmpi-4.0.1: Header checksum mismatch

### ISSUE THREAD

**Issue by atomsymbol** [gentoo/sci#913]
Hi. I encountered the following error:

     * Header files have changed between ABIs.
     * --- /var/tmp/portage/sys-cluster/openmpi-4.0.1/temp/.multilib_header_cksum   2019-04-09 04:13:47.156024997 +0200
     * +++ /var/tmp/portage/sys-cluster/openmpi-4.0.1/temp/.multilib_header_cksum.new       2019-04-09 04:14:30.293592642 +0200
     * @@ -24,7 +24,7 @@
     *  3178862774 4923 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/ompi/mpi/cxx/functions_inln.h
     *  3626854394 5101 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/ompi/mpi/cxx/topology_inln.h
     *  2015540287 5156 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/ompi/mpi/cxx/intracomm.h
     * -4004980956 575 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/mpiext/mpiext_cuda_c.h
     * +2315801159 575 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/mpiext/mpiext_cuda_c.h
     *  2247402274 597 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/mpi-ext.h
     *  35712708 6242 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/ompi/mpi/cxx/request.h
     *  3043828648 6550 /var/tmp/portage/sys-cluster/openmpi-4.0.1/image/usr/include/openmpi/ompi/mpi/cxx/intracomm_inln.h
     * ERROR: sys-cluster/openmpi-4.0.1::science failed (install phase):
     *   Header checksum mismatch, aborting

[sys-cluster:openmpi-4.0.1:20190409-020427.log.gz](https://github.com/gentoo/sci/files/3058992/sys-cluster.openmpi-4.0.1.20190409-020427.log.gz)

**Comment by naturomics** [comment]
Came across the same error (version 4.0.2), and solved by adding `java` and removing `abi_x86_32` USE flag.

In my file `/etc/portage/package.use`:
```
sys-cluster/openmpi -abi_x86_32 java
```

Not sure which part makes it work, -abs_x86_32 or java flag. Maybe only java flag is enough, test it yourself.

**Comment by heroxbd** [comment]
What seems to be the problem?  Shall we mask `sys-cluster/openmpi[abi_x86_32]`?

**Comment by TheChymera** [comment]
Closing as per https://github.com/gentoo/sci/issues/911#issuecomment-706483082
