### ISSUE TITLE
sci-libs/lapack-reference-3.8.0-r100: Action files unknown, etc

### ISSUE THREAD

**Issue by atomsymbol** [gentoo/sci#914]
Hi. I encountered the following error:

    !!! Error: Action files unknown
    exiting
    readlink: missing operand
    Try 'readlink --help' for more information.
    Must specify package names on the command line

[sci-libs:lapack-reference-3.8.0-r100:20190409-014858.log.gz](https://github.com/gentoo/sci/files/3059008/sci-libs.lapack-reference-3.8.0-r100.20190409-014858.log.gz)

**Comment by heroxbd** [comment]
Please migrate to sci-libs/lapack in ::gentoo.  cf. https://wiki.gentoo.org/wiki/Blas-lapack-switch
