### ISSUE TITLE
Unable to build sci-libs/itk since dev-cpp/gccxml has been removed from gentoo repository

### ISSUE THREAD

**Issue by ahilke** [gentoo/sci#916]
Emerging sci-libs/itk (e.g. version 5.0_rc1) fails with error "there are no ebuilds to satisfy ">=dev-cpp/gccxml-0.9.0_pre20120309". dev-cpp/gccxml has been removed from the main gentoo repository a few days ago.

Commit: https://github.com/gentoo/gentoo/commit/845ca5ddfdc7ab6fc4e3ade9add108e9d5656531
Bug Ticket: https://bugs.gentoo.org/683748

The ebuild should probably be changed to use dev-cpp/castxml instead (cf. bug ticket or https://github.com/gccxml/gccxml). Here is a ebuild from another repository using castxml: https://github.com/gerddie/gentoo-imaging/blob/master/sci-libs/itk/itk-4.13.0-r1.ebuild

**Comment by TheChymera** [comment]
@ahilke this has been resolved in the current ITK version we distribute, as well as the previous one.
