### ISSUE TITLE
fsl-5.0.11 eddy doesn't build

### ISSUE THREAD

**Issue by AbstractMethod** [gentoo/sci#928]
The 'eddy' build project doesn't build because the project's Makefile has an undefined reference to ${CXX11}.  Fortunately, the patch is minor and works for me in a local overlay:

--

    diff -Naur fsl.orig/src/eddy/Makefile fsl/src/eddy/Makefile
    --- fsl.orig/src/eddy/Makefile	2019-09-26 00:40:07.102990550 -0400
    +++ fsl/src/eddy/Makefile	2019-09-26 00:40:43.037990852 -0400
    @@ -23,6 +23,7 @@
     include ${FSLCONFDIR}/default.mk
 
     PROJNAME=eddy
    +CXX11=${CXX}
     debug=a
     USRCXXFLAGS=-std=c++11
     TMPCXXFLAGS_1=
--

**Comment by TheChymera** [comment]
@AbstractMethod apologies for only catching this now. `fsl-5.0.11` is now no longer in the tree. Does `fsl-6.0.2` work for you?

**Comment by AbstractMethod** [comment]
Yes, it does thanks -- but actually have another issue (more of an enhancement really) that I'll open in a new issue.
