### ISSUE TITLE
sci-libs/gotoblas2-1.13-r1 package downloiad 404's

### ISSUE THREAD

**Issue by jokleinn** [gentoo/sci#931]
Hi! I think this is just an issue of mirrors being moved around. The gotoblas2 package references a file stored under [~bicatali](https://dev.gentoo.org/~bicatali), but attempting to navigate to it 404's for me. As a result, it's impossible to install the package using portage currently without manual intervention. Could we possibly stick the package on a new mirror?

Thanks, 
j

**Comment by heroxbd** [comment]
Hi, I might be wrong.  Does OpenBLAS obsoletes gotoblas2?  If so, we can remove gotoblas2 from the overlay.

**Comment by kiwifb** [comment]
Yes, definitely. I don't see why you would want gotoblas2 over openblas. I need to have the case made to me. The only thing I can think of is obsolete hardware dropped from openblas.

**Comment by TheChymera** [comment]
gotoblas has been removed in favour of openblas.
