### ISSUE TITLE
sci-chemistry/ambertools cannot be merged due to missing dep 

### ISSUE THREAD

**Issue by pacho2** [gentoo/sci#933]
It seems a dep is missing:
# emerge ambertools 

 * IMPORTANT: 1 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "sci-chemistry/reduce".
(dependency required by "sci-chemistry/ambertools-15_p6::science" [ebuild])
(dependency required by "ambertools" [argument])

https://bugs.gentoo.org/698904

**Comment by TheChymera** [comment]
@pacho2 as part of a recent overhaul, we have discontinued ambertools. The maintainer marked it as dead: https://gitweb.gentoo.org/proj/sci.git/commit/?id=3f82bedc598954b453b33eda83de53c47dd30ed0

If this is not the case, we would be happy to bring it back pending a PR.
