### ISSUE TITLE
Problems with PYTHON_COMPAT

### ISSUE THREAD

**Issue by linux923344** [gentoo/sci#938]
Hi! When I update the repo I have error with PYTHON_COMPAT. Also I tried update the some packeges but the QA Tester has error no connection with my pull ;) 
Link to pull request: https://github.com/gentoo/sci/pull/935

**Comment by linux923344** [comment]
Also added test and error: https://travis-ci.org/gentoo/sci/builds/631314323?utm_source=github_status&utm_medium=notification

**Comment by TheChymera** [comment]
see the comment in the PR
