### ISSUE TITLE
FSL bet: imglob command not found

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#939]
There seems to be something wrong with out newest FSL version bump (`6.0.2`):

`/usr/bin/bet` fails with:

```
/usr/bin/bet: line 403: imglob: command not found
```

@kiwifb any ideas, is this something we don't install?

**Comment by kiwifb** [comment]
Must be, this is apparently part of FSL after quick googling. But I don't know if it is because it fails to build silently or just lost in the install.

Have you checked `equery f fsl | grep imglob` to see if it is actually installed in an unexpected place?

**Comment by kiwifb** [comment]
I fell like something may be missing from the tarball. `imglob` is used in quite a few scripts. But there is no such file in the tarball. The only mention of it, is in fslio
```
fbissey@moonloop ~/sandbox/git-fork/overlay/sci-biology/fsl $ cat /dev/shm/portage/sci-biology/fsl-6.0.2/work/fsl/src/fslio/Makefile
include ${FSLCONFDIR}/default.mk

PROJNAME = fslio

USRINCFLAGS = -I${INC_ZLIB}

OBJS=fslio.o

SCRIPTS = remove_ext fsloutputtype imtest imglob imcp imln imrm immv

all: 


fbissey@moonloop ~/sandbox/git-fork/overlay/sci-biology/fsl $ ll /dev/shm/portage/sci-biology/fsl-6.0.2/work/fsl/src/fslio/
total 52K
drwxr-xr-x  2 fbissey fbissey  200 Sep 12 01:23 .
drwxr-xr-x 82 fbissey fbissey 1.7K Sep 12 01:22 ..
-rw-r--r--  1 fbissey fbissey  136 Jan 17  2015 CMakeLists.txt
-rw-r--r--  1 fbissey fbissey 4.6K Jan 17  2015 dbh.h
-rwxr-xr-x  1 fbissey fbissey 4.8K Sep 12 01:23 fslio.tcl
-rwxr-xr-x  1 fbissey fbissey 4.2K Sep 12 01:23 imln
-rw-r--r--  1 fbissey fbissey 3.8K Sep 12 01:23 imrm
-rwxr-xr-x  1 fbissey fbissey 4.3K Sep 12 01:23 imtest
-rw-r--r--  1 fbissey fbissey  173 Jan 17  2015 Makefile
-rwxr-xr-x  1 fbissey fbissey 4.1K Sep 12 01:23 remove_ext
```
I suspect it is more than just `imglob` missing because there are other scripts missing beside it defined in the variable `SCRIPTS`.

**Comment by TheChymera** [comment]
@kiwifb I think I found it, it's in fslpy:

```
chymera@quiethost ~/src/sci $ equery f fslpy | ag imglob
/usr/bin/imglob
/usr/lib/python-exec/python3.6/imglob
/usr/lib64/python3.6/site-packages/fsl/scripts/__pycache__/imglob.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/fsl/scripts/__pycache__/imglob.cpython-36.opt-2.pyc
/usr/lib64/python3.6/site-packages/fsl/scripts/__pycache__/imglob.cpython-36.pyc
/usr/lib64/python3.6/site-packages/fsl/scripts/imglob.py
```

We need to make fsl depend on fslpy, no idea why I had not done this yet. Also, I only just notice that `fsl-6.0.2` is still only on my overlay. Did you test this on 6* or 5*?

Would you help me have a look at it again (e.g. for the other missing scripts) before I merge it here?

**Comment by kiwifb** [comment]
I only looked at 6.0.2 from your overlay.

I guess I could give you a hand if necessary.

**Comment by TheChymera** [comment]
Dear @kiwifb, could you have another look at the newest version of the ebuild, and tell me if you're satisfied with it for your use cases? Not having a test suite, it's pretty difficult to determine if it fully works. For my work it works, but as seen above there's always new issues we could stumble upon.

I also notice there's an old commented-out matlab flag, do you think that's still relevant?

**Comment by kiwifb** [comment]
I don't really have a use case. I used to support someone at the NZBRI (New Zealand Brain Research Institute) which is how I became interested in the first place but I don't really have a use for it these days. Just an inherited responsibility from the work I already put in it :)

I'll have a look at the matlab stuff.

**Comment by kiwifb** [comment]
There are a number of octave/matlab `.m` files in some places of the source tree. I have no idea what state of maintenance they are in. If we discard the few that are part of other software shipped in fsl we have the following left
```
./etc/matlab/read_avw_hdr.m
./etc/matlab/save_avw_img.m
./etc/matlab/read_avw_img_slice.m
./etc/matlab/prepare_read_avw_img_slice.m
./etc/matlab/call_fsl.m
./etc/matlab/save_avw_hdr.m
./etc/matlab/save_avw_complex.m
./etc/matlab/read_avw.m
./etc/matlab/read_avw_img.m
./etc/matlab/cleanup_read_avw_img_slice.m
./etc/matlab/save_avw.m
./etc/matlab/read_avw_complex.m
```
`etc` is not exactly a usual spot for such files either. I guess we could ship them but I am not sure where to install them. Probably `/usr/share/fsl/matlab`.

**Comment by TheChymera** [comment]
Hey, @pauldmccarthy, is the matlab stuff still relevant? I actually had no idea there are parts of FSL which depend on matlab.

@kiwifb I think our choices are to reinstate the matlab USE flag, or drop them (preemptively) if Paul says they're deprecated or soon to become so.

**Comment by kiwifb** [comment]
No parts of fsl depends on matlab, those files are to use parts of fsl from matlab. Possibly for easy visualization as this is one thing matlab users love about it.

**Comment by pauldmccarthy** [comment]
Yep, as @kiwifb says, these files are not used by anything that is "officially" in FSL. They are used by some optional extras such as [FSLNets](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLNets), which perform call-outs to FSL commands. The `read`/`save` functions are horrendously out of date, and are an endless source of orientation mis-matches (as, having been written in ANALYZE times, they don't preserve NIFTI sform/qform affines).

**Comment by TheChymera** [comment]
@pauldmccarthy do you plan to drop them in the forseeable future? do the files listed [above](https://github.com/gentoo/sci/issues/939#issuecomment-574485816) overlap 1-to-1 with FSLnets? i.e. if we decide to support installing these files, would it make more sense to call the feature "FSLnets" rather than matlab?

@kiwifb do any of your users need this?

**Comment by TheChymera** [comment]
@kiwifb unless your users need this, I propose we drop that section and reinstate it only if we ever decide to provide FSLnets in full (which requires more than just these files, from what I read on the package page). As it stands these files are useless on their own.

**Comment by kiwifb** [comment]
I have no users left and they never used matlab :)

**Comment by pauldmccarthy** [comment]
The FSL team has no plans to drop these scripts in the future - in addition to their use by (e.g.) FSLNets, we do have users who work in MATLAB, and thus rely on the I/O routines, and call-outs to FSL via `call_fsl`. It would be your call as to whether you want to support this use-case.

**Comment by TheChymera** [comment]
Ok, I'm dropping this for the time being, we can always add them back if anybody ends up needing them :)

@kiwifb any other issues you see with the ebuild? Also, how should I best credit you for the ebuild, I wouldn't feel very confident about pulling in the entire commit history of the file, since technically that would have required revbumps.

**Comment by kiwifb** [comment]
I guess I should make sure I get some credit somehow. I will give you a header to put on all my current patches. For the ebuild itself, I am satisfied with an acknowledgement in the full log.

**Comment by TheChymera** [comment]
can you send me a PR on my overlay with your patch haders?

**Comment by kiwifb** [comment]
In your overlay?

**Comment by njfreesurfer** [comment]
> There seems to be something wrong with out newest FSL version bump (`6.0.2`):
> 
> `/usr/bin/bet` fails with:
> 
> ```
> /usr/bin/bet: line 403: imglob: command not found
> ```
> 
> @kiwifb any ideas, is this something we don't install?

I had the same issue. you should check if you have fslpython installed $FSLDIR/fslpython if not, follow this link:
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind2004&L=FSL&D=0&P=73952
This might fix your issues. 

Tony

**Comment by TheChymera** [comment]
@njfreesurfer this has been solved for a while:
https://gitweb.gentoo.org/proj/sci.git/tree/sci-biology/fsl/fsl-6.0.2.ebuild?id=a5c0e85c0b92a96ebc391eafe31361f2ad797187#n19

 Gentoo's FSL package depends on fslpy, meaning that fslpy will always be present if FSL is installed. Sorry for forgetting to close this.
