### ISSUE TITLE
sci-biology/bowtie-2.4.0: add ppc64le arch and missing python3 dep

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#942]
Hi,
  I do not have the hardware to test, but somebody may want to add the new arch. In 2.4.0 NEWS I see:

```
* Added preliminary support for ppc64le architectures with the help of
  SIMDE project see [#271](https://github.com/BenLangmead/bowtie2/issues/271) for details.
```

  All utility scripts were migrated to python3. Somewhat, the ebuild doe snot define any dependency on python, which I do not personally mind, as I think the python dependency is just nuisance in cases of tools, which are primarily C/C++ based and compiled. Feel free to fix that too.

  Please move the ebuild to the main tree too. bowtie-1.2.x series has still consumers although 2.x series is the current approach.

**Comment by AndrewAmmerlaan** [comment]
This package is in the main gentoo repository. Please move this issue to bugs.gentoo.org.
