### ISSUE TITLE
package request: torchvision

### ISSUE THREAD

**Issue by jorgicio** [gentoo/sci#943]
Hi!

I noted the existence of a package called torchvision, which is an extension of pytorch but it works with images. I think this package is very necessary for the training of images classifiers using Torch.

I hope this may be considered.

Thank you!

**Comment by heroxbd** [comment]
https://github.com/gentoo/sci/pull/941 @aclex is working on torchvision.   You are welcome to join the effort.

**Comment by jorgicio** [comment]
Thank you, I just watched this.

Anyways, I just sent a PR just in case. Hope it helps.
