### ISSUE TITLE
g-octave-9999.ebuild

### ISSUE THREAD

**Issue by kenshin33** [gentoo/sci#945]
EGIT_REPO_URI="git://git.overlays.gentoo.org/proj/g-octave.git"
no longer works.

https://www.gentoo.org/news/2015/04/25/anongit-overlays.html

**Comment by heroxbd** [comment]
Thank you for the report!  You are welcomed to submit a patch for pull request.

**Comment by AndrewAmmerlaan** [comment]
Closing as obsolete since the live ebuild was dropped.
