### ISSUE TITLE
ERROR: sci-biology/ncbi-blast+-2.8.1::science failed (configure phase)

### ISSUE THREAD

**Issue by Alteroldis** [gentoo/sci#950]
Error configuring ncbi-blast+ package. Occuring during generation Makefile.flat and only with root user. I try configure package locally in home directory and the error occur only with root.
[ncbi-blast+-2.8.1.logs.zip](https://github.com/gentoo/sci/files/4419801/ncbi-blast%2B-2.8.1.logs.zip)

**Comment by Alteroldis** [comment]
patch for src/util/random_gen.cpp
`diff -urNd ncbi-blast-2.8.1+-src/c++/src/util/random_gen.cpp ncbi-blast-2.8.1+-src-fixrandom/c++/src/util/random_gen.cpp
--- ncbi-blast-2.8.1+-src/c++/src/util/random_gen.cpp	2015-02-13 01:18:36.000000000 +1000
+++ ncbi-blast-2.8.1+-src-fixrandom/c++/src/util/random_gen.cpp	2020-04-03 11:49:04.353332781 +1000
@@ -109,6 +109,19 @@
             m_Fd(-1)
         {
             m_Fd = open(kHardwareGeneratorDevice, O_RDONLY);
+            if (m_Fd != -1) {
+                CRandom::TValue tval;
+                for ( ; ; ) {
+                    if (read(m_Fd, &tval, sizeof(tval)) ==
+                                            sizeof(tval))
+                        return;
+                    if (errno != EINTR) {
+                           close(m_Fd);
+                           m_FD = -1;
+                           break;
+                    }
+                }
+            }
             if (m_Fd == -1)
                 m_Fd = open(kSoftwareGeneratorDevice, O_RDONLY);
         }
`

**Comment by AndrewAmmerlaan** [comment]
Is this still an issue with version 2.11?

**Comment by mmokrejs** [comment]
@Alteroldis It is best to subscribe to NLM/NCBI List cpp cpp _a.t_ ncbi.nlm.nih.gov mailing list. The developers are very responsive and can answer you back quickly.

Note that ncbi-blast is released at a different pace compared to ncbi-tools++, which is a much more larger bundle.

**Comment by AndrewAmmerlaan** [comment]
Closing, this was fixed by restricting versions of ncbi-blast older than 2.11 to use gcc older then 10
