### ISSUE TITLE
sci-libs/pytorch: Cannot handle gcc linker args

### ISSUE THREAD

**Issue by Uroc327** [gentoo/sci#953]
See pytorch/pytorch#37510

The pytorch build system seems to be unable to handle arguments of the form `-Wl,--sort-common,-z,now`, as it splits the argument string at each comma.

Depending on the speed, this gets fixed upstream, one could think about filtering those flags out, I guess?

**Comment by heroxbd** [comment]
Patches welcome.

**Comment by Uroc327** [comment]
I'd like to. But with every failure I fix, I find a new one during compilation :/
