### ISSUE TITLE
FSL 6.0.2 won't build with GCC 10

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#957]
I just updated GCC to 10 and `=fsl-6.0.2` fails to build with the following [build.log](https://github.com/gentoo/sci/files/4705270/build.log).

It seems like it's an undefined reference issue:

```
/var/tmp/portage/sci-biology/fsl-6.0.2/work/fsl/include/newimage/newimageio.h:127: undefined reference to `int NEWIMAGE::readGeneralVolume<double>(NEWIMAGE::volume<double>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, short&, bool, long, long, long, long, long, long, long, long, long, long, long, long, long, long, bool)'
```

Building it with `CC=/usr/x86_64-pc-linux-gnu/gcc-bin/9.3.0/gcc CXX=/usr/x86_64-pc-linux-gnu/gcc-bin/9.3.0/g++` solves the issue.

@kiwifb @pauldmccarthy --- any ideas how we could most easily patch this so that we can continue to support it?

**Comment by kiwifb** [comment]
Hum, I am guessing from https://gcc.gnu.org/gcc-10/porting_to.html (look in the C++ section) that `< stdexcept>` is not included. Your long line includes `std::allocator` which would fit that reasoning. Including near the top of the file should fix it if I am not mistaken.

**Comment by kiwifb** [comment]
Do you need more info or help?

**Comment by TheChymera** [comment]
@kiwifb sorry for putting this off so long, tried to figure it out for a while, and then got stuck. So the place where I got stuck was pretty early --- so I assume I should be injecting a line saying `include stdexcept`, but where? `std::allocator` seems to [pop up all over the place](https://chymera.eu/ppb/5cf751.html).

**Comment by kiwifb** [comment]
Did I not eliminate almost totally the stuff in `extra`? `nlopt` and `boost` are definitely available in the main tree, and I wouldn't boost shipped by `fsl` unless there was a particular reason. `armwrap` is different, it is a complicated custom beast.

Digging...

**Comment by kiwifb** [comment]
In `src/newimage/newimageio.h` insert it after the other system headers and before the nifty one 
```
#include <string>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <sstream>
->insert me here<-
#include "NewNifti/NewNifti.h"
#include "newmatio.h"
#include "newimage.h"
#include "complexvolume.h"
#include "miscmaths/miscmaths.h"
```

**Comment by TheChymera** [comment]
> Did I not eliminate almost totally the stuff in `extra`? `nlopt` and `boost` are definitely available in the main tree, and I wouldn't use boost shipped by `fsl` unless there was a particular reason. `armwrap` is different, it is a complicated custom beast.

Ooops, I broke the build before any patches were applied, so that lookup was from the raw source code.

**Comment by TheChymera** [comment]
@kiwifb ok, it worked, thank you :) Merge coming up soon.

**Comment by TheChymera** [comment]
Thanks again for your help. Feel free to test :) https://gitweb.gentoo.org/proj/sci.git/commit/?id=bb46a3101c02d7fa039c78fa666d4d35d5e32989
