### ISSUE TITLE
sci-biology/deeptools-9999: git-2.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by mschilli87** [gentoo/sci#958]
It looks like the git-2 eclass [does not exist (anymore)](https://devmanual.gentoo.org/eclass-reference/git-2.eclass/). I assume it was superseded by the [git-r3 eclass](https://devmanual.gentoo.org/eclass-reference/git-r3.eclass/).
A quick search brought up [this commit](https://github.com/wichtounet/wichtounet-overlay/commit/1133fe5b82b2b0728d3ab141ebde9aee88832046) indicating it can be used as a simple drop-in replacement.
Also, I came across [this list](https://gentooqa.levelnine.at/results/science/stats/ECS-STA-ebuild_eclass_statistics/sort-by-filter/git-2.eclass/) which seems to call out `sci-biology/deeptools-9999` as an isolated case of using this eclass.

**Comment by mmokrejs** [comment]
Hi, I guess it was because git-r3 never really worked for me with git sources, due to depth level forced to 0 (is it termed shallow checkout?). I think you can find discussion of this in main bugzilla or gentoo sci to which I was Cc-ed or was even a reporter.

**Comment by mschilli87** [comment]
Well, I guess now is the time to either find a solution or remove the package then. :wink:
I'll give it a try and open a PR if I succeed.

**Comment by AndrewAmmerlaan** [comment]
Closing as obsolete since live ebuild has been removed
