### ISSUE TITLE
sci-biology/libBigWig: multilib-strict check failed!

### ISSUE THREAD

**Issue by mschilli87** [gentoo/sci#959]
While working on an attempted fix for https://github.com/gentoo/sci/issues/958, I ran into yet another issue while trying to install a dependency:

```
 * QA Notice: The following shared libraries lack a SONAME
 * /usr/lib/libBigWig.so

removing executable bit: /usr/lib/libBigWig.a
Files matching a file type that is not allowed:
   usr/lib/libBigWig.so
 * ERROR: sci-biology/libBigWig-0.4.0::science failed:
 *   multilib-strict check failed!
```

At this point I'm giving up trying to fix this myself.
Once I can build `sci-biology/libBigWig-0.4.0`, I'm happy to continue working on https://github.com/gentoo/sci/issues/958 but this was not what I signed up for when I simply tried to update my system today. :wink:

**Comment by TheChymera** [comment]
@mschilli87 this issue seems to be fixed in the current libBigWig version, which we distribute `0.4.4`: https://ppb.chymera.eu/ddb75c.log .

**Comment by mmokrejs** [comment]
I see only 

```
 * QA Notice: The following shared libraries lack a SONAME
 * /usr/lib64/libBigWig.so
```

with the live ebuild. Do not know who will fix the soname issue.

**Comment by TheChymera** [comment]
@mmokrejs ah, ok, that would be a different issue, though. This referred to `0.4.0`, which is now superseded by `0.4.4`, and builds fine.
