### ISSUE TITLE
sci-mathematics/dolfin ebuild using PYTHON_USEDEP outside of python_gen_cond_dep

### ISSUE THREAD

**Issue by typograph** [gentoo/sci#960]
Since the recent change in python-single-r1 eclass building sci-mathematics/dolfin fails with the message:

``sci-mathematics/dolfin-2017.1.0::science (masked by: invalid: DEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-NEEDS-TO-BE-USED-IN-PYTHON_GEN_COND_DEP%'), token 10``

**Comment by TheChymera** [comment]
@typograph dolfin has recently been removed due to fatal errors in the dependency stack ( https://gitweb.gentoo.org/proj/sci.git/commit/?id=d51c2ced7b3d8950894746f66da1c07712a00feb ). If you are interested in it, we would be happy to bring back a more recent version pending a PR.
