### ISSUE TITLE
sci-libs/rdkit-9999 not building

### ISSUE THREAD

**Issue by michalsta** [gentoo/sci#961]
Hi

The rdkit ebuild seems to need a few updates:
- It needs to be updated to depend on Boost built with numpy USE flag, otherwise it fails complaining about missing headers
- It needs FEATURES="-network-sandbox", otherwise the build crashes with access violation (dunno how to handle that in a clean way).
- It should probably be ported to depend on the new, split ebuilds for numpy (Py2/3)

**Comment by TheChymera** [comment]
@michalsta we have a new package which we're trying to make build in the network sandbox. It should be done soon: https://github.com/rdkit/rdkit/issues/3444

Do you use this package regularly, and/or would you be interested in maintaining it in the future?

**Comment by AndrewAmmerlaan** [comment]
Closing because live ebuild has been removed
