### ISSUE TITLE
sci-biology/fsl-6 cuda support

### ISSUE THREAD

**Issue by AbstractMethod** [gentoo/sci#969]
Really more of an enhancement, but it would be highly useful to add cuda support to fsl, especially for the "eddy" commands which can drastically cut down on processing times.

To that end, I've created a cuda patch in a local overlay.  I attach here three files (1 patch to modify the ebuild, 2 others to modify the fsl code).  I literally only tested these on my overlay, so they may need to be modified to increase robustness, etc.

**ebuild.patch**
```
--- fsl-6.0.2-r1.orig	2020-08-31 14:07:34.898332004 -0400
+++ fsl-6.0.2-r1.ebuild	2020-08-31 14:14:53.674321768 -0400
@@ -3,7 +3,7 @@
 
 EAPI=7
 
-inherit flag-o-matic toolchain-funcs prefix
+inherit cuda flag-o-matic toolchain-funcs prefix
 
 DESCRIPTION="Analysis of functional, structural, and diffusion MRI brain imaging data"
 HOMEPAGE="http://www.fmrib.ox.ac.uk/fsl"
@@ -12,7 +12,7 @@
 LICENSE="FSL BSD-2 newmat"
 SLOT="0"
 KEYWORDS="~amd64"
-IUSE=""
+IUSE="cuda"
 
 DEPEND="
 	dev-libs/boost
@@ -28,6 +28,13 @@
 	dev-lang/tk:0=
 	>=virtual/lapack-3.8
 	>=virtual/blas-3.8
+
+	cuda? (
+		|| (
+			( <dev-util/nvidia-cuda-toolkit-11 <sys-devel/gcc-9 )
+			( =dev-util/nvidia-cuda-toolkit-11* =sys-devel/gcc-9* )
+		   )
+	)
 	"
 RDEPEND="${DEPEND}"
 
@@ -106,6 +113,30 @@
 	# script wanting to have access to flsversion at buildtime
 	sed -e "s:/etc/fslversion:${S}/etc/fslversion:g" \
 		-i ${makefilelist} || die
+
+	if use cuda; then
+		einfo
+		
+		gcc_ver=`gcc-fullversion`
+		einfo "GCC version: ${gcc_ver}"
+
+		cuda_gcc=`cuda_gccdir`
+		cuda_NVCC_flags=`cuda_gccdir -f`
+		einfo "CUDA GCC path: ${cuda_gcc}"
+		einfo "  ${cuda_NVCC_flags}"
+
+		CUDA_INSTALLATION="/opt/cuda"
+		CUDAVER=`cuda_toolkit_version`
+
+		eapply "${FILESDIR}/${PN}-6-eddy_cuda.patch"
+		eapply "${FILESDIR}/${PN}-6-cuda_buildsettings.patch"
+
+		sed -i \
+			-e "s:@@GENTOO_NVCC_FLAGS@@:${cuda_NVCC_flags}:" \
+			src/eddy/Makefile || die
+	
+		cuda_sanitize
+	fi
 }
 
 src_compile() {
@@ -120,6 +151,11 @@
 	export CIFTICFLAGS="$($(tc-getPKG_CONFIG) --cflags CiftiLib)"
 	export CIFTILIBS="$($(tc-getPKG_CONFIG) --libs-only-l CiftiLib)"
 
+	if use cuda; then
+		einfo "CUDA_INSTALLATION: ${CUDA_INSTALLATION}"
+		einfo "CUDAVER: ${CUDAVER}"
+	fi
+
 	./build || die
 }
``` 

**fsl-6-cuda_buildsettings.patch:**
```
diff -Naur fsl.orig/config/buildSettings.mk fsl/config/buildSettings.mk
--- fsl.orig/config/buildSettings.mk	2020-07-23 15:43:42.277064365 -0400
+++ fsl/config/buildSettings.mk	2020-07-23 15:45:17.705069496 -0400
@@ -141,7 +141,7 @@
 # CUDA development environment
 CUDAVER := $(or $(CUDAVER),9.1)
 #$(info $$CUDAVER is [${CUDAVER}])
-CUDA_INSTALLATION = /opt/cuda-${CUDAVER}
+CUDA_INSTALLATION = /opt/cuda
 GENCODE_FLAGS = $(shell ${FSLDIR}/config/common/supportedGencodes.sh ${CUDA_INSTALLATION})
 LIB_CUDA = ${CUDA_INSTALLATION}/lib64
 INC_CUDA = ${CUDA_INSTALLATION}/include
```

**fsl-6-eddy_cuda.patch:**
```
diff -Naur fsl.orig/src/eddy/Makefile fsl/src/eddy/Makefile
--- fsl.orig/src/eddy/Makefile	2020-07-30 14:30:06.414884410 -0400
+++ fsl/src/eddy/Makefile	2020-07-30 14:33:03.400889914 -0400
@@ -29,6 +29,8 @@
 TMPCXXFLAGS_2=
 TMPNAME_1=
 TMPNAME_2=
+cuda=1
+cpu=1
 
 ifndef cuda
    ifndef cpu #Default single cpu, no threading
@@ -74,7 +75,7 @@
 ifdef NVCC11
 	NVCC=${NVCC11}
 endif
-NVCCFLAGS=-c -DCOMPILE_GPU -O3 -m 64 -std=c++11
+NVCCFLAGS=-c -DCOMPILE_GPU -O3 -m 64 -std=c++11 @@GENTOO_NVCC_FLAGS@@
 ifeq ($(CLOBBER_CLANG),1)
    NVCCFLAGS+= -DCLOBBER_CLANG
 endif
```

**Comment by TheChymera** [comment]
So you have already tested it on a workflow which you have and makes use of the CUDA features? Sadly, I work mostly on remote headless machines, so I don't really have much experience with CUDA. Perhaps @Jimmy2027 could help re-test this on another machine which is not yours. Should that be the case, can you provide a MWE for some code using the functionality?

Lastls, and perhaps a better approach: does FSL have a test suite? If so, does it cover CUDA and can you add it to the ebuild?

**Comment by pauldmccarthy** [comment]
The only CUDA-capable FSL tools are `eddy_cuda`, `probtrackx_gpu`, and `bedpostx_gpu`. Compliation is configured in `buildSettings.mk`, and in the eddy `Makefile`, so this looks like the way to go.

There is a test suite for eddy, but it depends on internally hosted benchmark data, so is not easty to run outside of our internal cluster environment. We are working on this, so it may be possible in the future.

The fslpy library doesn't have any CUDA-capable functionality (except for a wrapper function which calls out to `eddy_cuda`)

**Comment by AbstractMethod** [comment]
@TheChymera : to answer your questions in order:

Yes, I've tested on a workflow that "works", at least for eddy_cuda (have not used it for the extended DTI/tractography tools given above).  It takes my processing time for eddy from 12+ hours (!) to < 1 hour, even on my fairly average desktop machine (not dedicated computational).

I can provide a working example, although a minimal one will require some more thought from me.  I've only used it on a couple of real DTI datasets, but the results seem identical to using the non-CUDA eddy, so certainly worth considering adding to the ebuild.

@pauldmccarthy : any advice in help creating a MWE?

**Comment by TheChymera** [comment]
@AbstractMethod a MWE would really be best, but in the absence of that, you can just create a PR, and I'll test it for emerging, and push it.

Also, could you please close this issue? https://github.com/gentoo/sci/pull/891 We have finished setting up FSLeyes for a while now, but we're in this weird situation where I have push access to the overlay but no maintainer access to close issues on GH :-/

**Comment by AbstractMethod** [comment]
@TheChymera `eddy` takes a number of inputs to work correctly, both the DTI acquisition and the output from the `topup` command used previously.  From `eddy --help` :
  
    Usage: 
    eddy --monsoon

    Compulsory arguments (You MUST set one or more of):
        --imain File containing all the images to estimate distortions for
        --mask  Mask to indicate brain
        --index File containing indices for all volumes in --imain into --acqp and --topup
        --acqp  File containing acquisition parameters
        --bvecs File containing the b-vectors for all volumes in --imain
        --bvals File containing the b-values for all volumes in --imain
        --out   Basename for output

I can package the inputs up for in a tarball and give a README to run the command if you like.  I don't know any other way to provide a MWE for you.  `eddy` requires the outputs from the `topup` command, so that has to be run initially on the data.

**Comment by TheChymera** [comment]
@AbstractMethod It's ok, I'll just see if it builds, and pull your PR. But please submit a PR. If there are issues, I assume somebody will let us know :) Do you have any other colleagues who are also using FSL on Gentoo, or is it just you?

**Comment by AbstractMethod** [comment]
OK created PR #973 

Don't have any other colleagues using FSL on Gentoo unfortunately.  But everything implemented with a 'cuda' flag, so if something is broken user can just disable it.
