### ISSUE TITLE
dev-util/amdapp has dependencies that are masked and blocked

### ISSUE THREAD

**Issue by Prism019** [gentoo/sci#970]
Trying to emerge the AMD APP SDK will result in being warned that ``app-eselect/eselect-opencl`` and ``app-eselect/eselect-opengl`` are both masked and will be removed soon. The functionality is replaced with ``virtual/opencl`` and ``media-libs/libglvnd``. Manually unmasking them results in blocking ``x11-libs/xorg-server``, ``media-libs/mesa``, ``dev-util/opencl-headers``, and ``virtual/opencl`` when trying to emerge.

**Comment by TheChymera** [comment]
@Prism019 

```
chymera@silenthost ~/src/sci $ git log | ag amdapp -B 9 | head -10

commit 4db0a635a463e6a2b4a641d240a28a30d9985f53
Merge: 33a7c2222 662cee61a
Author: Justin Lecher <jlec@gentoo.org>
Date:   Sun Mar 26 15:45:54 2017 +0100

    Merge remote-tracking branch 'github/master'

    * github/master:
      dev-util/amdapp: Added release and manifest for new AMD download v3.0.130.136 (#605)
```

The package seems to not have been updated since 2017, so it is entirely possible that certain dependencies no longer conform to the current version of the tree. We tend to not remove old ebuilds, lest we remove work that could reasonably still be reused.

Are you sure the package is still developed upstream? If so, I would be happy to work with you on updating the ebuild.

**Comment by Prism019** [comment]
The AMD APP SDK has been discontinued since 2017. Any future updates to the ebuild will be just our changes to keep it working on gentoo systems.

**Comment by TheChymera** [comment]
If you have any suggestions on how to update the ebuild, I'd be happy to review them for you :)

**Comment by epsilon-0** [comment]
Do we still want it?
What does amdapp provide that we need and are there any other providers?
Basically, is there any benefit for this work other than keeping a dead software running?
If upstream has abandoned it, it makes little sense for us to continue keeping it, unless there are reverse dependencies.

**Comment by Prism019** [comment]
The current AMD GPU compute toolchain is called ROCm, which only supports Radeon GPUs from the RX 300 series (June 2015) and higher, so any compute applications needing to compile for the RX 200 series require using AMD APP.

**Comment by epsilon-0** [comment]
Got it.
That sounds reasonable enough to keep.

**Comment by epsilon-0** [comment]
Hmmm, seems like I killed it off because it wasn't building and the upstream is dead - https://github.com/gentoo/sci/commit/0614260b17229537554dbac08af8dcaecd43cbdf#diff-ae69476b8fb86c558dfc8eb861ac7efe

This will have to be readded, can you make a PR for readding this?
