### ISSUE TITLE
dev-util/nvidia-cuda-gdk-352.79 does not merge

### ISSUE THREAD

**Issue by YuriyRusinov** [gentoo/sci#971]
I try to emerge dev-util/nvidia-cuda-gdk from overlay. All compile was ok, but the package don't merge due to conflict with dev-util/nvidia-cuda-toolkit from main portage tree. If I try to remove dev-util/nvidia-cuda-toolkit and re-emerge dev-util/nvidia-cuda-gdk I got that dev-util/nvidia-cuda-toolkit has to be merged as dependence.

**Comment by epsilon-0** [comment]
@YuriyRusinov 
Thanks for bringing this to attention. 
This package is going to be removed soon as the newer versions are part of the CUDA Toolkit in ::gentoo.

**Comment by TheChymera** [comment]
@YuriyRusinov does the newer package from ::gentoo fulfill your requirements? If so, please consider closing the issue.
