### ISSUE TITLE
sci-biology/fsl-6 Feat and Melodic errors

### ISSUE THREAD

**Issue by AbstractMethod** [gentoo/sci#974]
Commands `Feat` and `Melodic` give similar errors when invoked from the command line:

    Error in startup script: can't read "env(FSLDIR)": no such variable
        while executing
    "set FSLDIR        $env(FSLDIR)"
        (file "/etc/fslconf/fslstart.tcl" line 1)
        invoked from within
    "source [ file dirname [ info script ] ]/fslstart.tcl"
        (file "/etc/fslconf/feat.tcl" line 70)
        invoked from within
    "source /etc/fslconf/feat.tcl"
        (procedure "feat5:setupdefaults" line 10)
        invoked from within
    "feat5:setupdefaults"
        (procedure "feat5" line 6)
        invoked from within
    "feat5 .r"
        (file "/usr/libexec/fsl/feat.tcl" line 524)
        invoked from within
    "source /usr/libexec/fsl/${origname}.tcl"
        (file "/usr/bin/Feat" line 22)

Note this only applies to the GUI / Tcltk commands, not to `feat` or `melodic` commands.  Also things Tcltk `Flirt` etc. seem to work OK -- so it only seems to apply to `Feat` and `Melodic` that I've found so far.

@TheChymera I can attempt to investigate further on my set up.  IIRC you were running `fsl` on a headless machine, and thus you probably don't use these commands directly.

**Comment by TheChymera** [comment]
@AbstractMethod yes, I use FSL exclusively without the GUI, as do all of my collaborators. Sadly I don't have much input on this :( Perhaps @kiwifb or @pauldmccarthy (apologies for involving you so often, but it seems Gentoo is finally becoming a more popular distribution channel for FSL) might have better input.

**Comment by pauldmccarthy** [comment]
I don't know how your version of FSL works, but in a normal FSL installation, many programs expect an environment variable called `FSLDIR` to be set, pointing to the location of the FSL installation.

**Comment by kiwifb** [comment]
We have a couple of choice. Setting `FSLDIR` in `env.d` so it is always defined once fsl is installed or making sure all those script file start with appropriate sourcing of an environment file. The way this fails suggests that putting something in `env.d` is the easiest way to get something working.

**Comment by kiwifb** [comment]
Reading the ebuild again, it is quite possible that in fact we want to remove all such lines altogether. Various invocation of FSLDIR/somedir have been replaced with appropriate thing all over the place. 

So first we should check if FSLDIR is used anywhere else after install. Someone will have to do a grep of FSLDIR in /usr/libexec/fsl/.

**Comment by AbstractMethod** [comment]
For the record, the environment variable `FSLDIR` *is* set for my user. `FSLDIR` is essential for fsl to run correctly, and as I said other commands work fine (`Flirt`, `Susan`, etc.).  So I'm not sure it's just as simple as setting `FSLDIR` in `env.d` or wherever.

**Comment by kiwifb** [comment]
OK then it is strange. IF I am not mistaken `$env(FSLDIR)` is supposed to get the value from the environment. So something has to be interfering or resetting the environment before arriving there.

**Comment by kiwifb** [comment]
I have been digging that stuff again to remind myself of what has been done. Some of the sed rules need updating to for the html files that are spread all over the place.
We already have a file in env.d that defines a value for FSLDIR. So something very funky is going on and that error message could actually be misleading as to what is the real issue.

**Comment by kiwifb** [comment]
Bummer, I cannot install stuff to check what I think is happening because fslpy requires python 3.6 and I am a python 3.7+ shop right now.

Great pain has been taken to make sure locations for the various file are more sane than just under FSLDIR. Unfortunately there is quite a bit stuff left in a wrong state in tcl scripts. In `feat`
```
# the next line restarts using wish \
exec $FSLTCLSH "$0" "$@"

source $env(FSLDIR)/tcl/fslstart.tcl
proc firstLevelMaster { session } { 
```
FSLDIR is being given as `/usr/share/fsl` but tcl scripts are being installed under `/usr/libexec/fsl`. If `feat` is not touched to rectify this there would certainly be problem down the line. Can someone check an actual install?

**Comment by kiwifb** [comment]
@TheChymera I think I have missed some stuff in src_install. I think the following needs to be added at least
```
	sed -i "s:\$env(FSLDIR)/tcl:/usr/libexec/fsl:g" \
		$(grep -l "\$env(FSLDIR)/tcl" bin/*) || die
```
Not sure that is enough to fix the current issue but I am fairly sure it is needed.

**Comment by TheChymera** [comment]
> Bummer, I cannot install stuff to check what I think is happening because fslpy requires python 3.6 and I am a python 3.7+ shop right now.

That's not the case. I run fslpy with 3.7 no issues on multiple machines:

```
chymera@silenthost ~ $ eix fslpy
[I] dev-python/fslpy [1]
     Available versions:  (~)2.6.2^t (~)2.7.0^t (~)2.8.4^t {test PYTHON_TARGETS="python3_6 python3_7"}
     Installed versions:  2.8.4^t(08:09:55 AM 05/11/2020)(-test PYTHON_TARGETS="python3_7 -python3_6")
     Homepage:            https://git.fmrib.ox.ac.uk/fsl/fslpy
     Description:         The FSL Python Library

[1] "science" /var/db/repos/science
```

**Comment by kiwifb** [comment]
@TheChymera for some reason it wants to use fslpy-2.7.0, I'll have to check the dependencies. I will try to do a PR of the stuff that are important.

**Comment by AbstractMethod** [comment]
@kiwifb Made the change manually but still the same result (although I agree that it necessary):

    Error in startup script: can't read "env(FSLDIR)": no such variable
        while executing
    "set FSLDIR        $env(FSLDIR)"
        (file "/etc/fslconf/fslstart.tcl" line 1)
        invoked from within
    "source [ file dirname [ info script ] ]/fslstart.tcl"
        (file "/etc/fslconf/feat.tcl" line 70)
        invoked from within
    "source /etc/fslconf/feat.tcl"
        (procedure "feat5:setupdefaults" line 10)
        invoked from within
    "feat5:setupdefaults"
        (procedure "feat5" line 6)
        invoked from within
    "feat5 .r"
        (file "/usr/libexec/fsl/feat.tcl" line 524)
        invoked from within
    "source /usr/libexec/fsl/${origname}.tcl"
        (file "/usr/bin/Feat" line 22)

files affected: `feat`, `featquery`, and `featreapply`

**Comment by kiwifb** [comment]
I wonder if the first line is actually a syntax error. It looks like it tries to take `env(FSLDIR)` as a whole as a variable. I hope I can try to do an install today so I can examine things fully by myself.

**Comment by kiwifb** [comment]
Because I am on arch and not ~arch I had to keyword manually all the dependencies of fslpy-2.8.4. When trying to emerge fsl portage never gave me that option. Now installing.

**Comment by kiwifb** [comment]
I have a new separate issue :(
```
 * Detected file collision(s):
 * 
 *      /usr/bin/toast
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * media-sound/gsm-1.0.13-r1:0::gentoo
 *      /usr/bin/toast
 * 
 * Package 'sci-biology/fsl-6.0.2-r1' NOT merged due to file collisions.
 * If necessary, refer to your elog messages for the whole content of the
 * above message.
```

**Comment by TheChymera** [comment]
@kiwifb Paul has been pretty accommodating of this sort of thing in the past. Perhaps he could be convinced to rename it to fsl_toast instead. At any rate we can also do this independently for the time being.

**Comment by kiwifb** [comment]
Fortunately `toast` is not called by other scripts in fsl which makes changing the name relatively trivial. This is part of `oxford_asl` so technically those are the people who need to change the name.
```
# TOAST: TurbO quasar asl bayesian AnalySis Tool
```
What to call it? tqabat?

**Comment by TheChymera** [comment]
@kiwifb I do think fsl_toast would be more unambiguous, and easier for people who are looking for toast and not finding it to locate.

**Comment by kiwifb** [comment]
Just kidding. I am going to go for fsl_toast for now in any case.

**Comment by kiwifb** [comment]
OK let's look at `Feat`
```
#!/bin/sh

# Check for display being set \
if [ _$DISPLAY = _ ] ; then echo "DISPLAY is not set. Please set your DISPLAY environment variable!" ; exit 1 ; fi
# Check for FSLDIR being set \
if [ -z "$FSLDIR" ]; then echo "You need to set the FSLDIR environment variable to point to the FSL installation directory before you can run anything." ; exit 1; fi
# Check for FSLDIR being valid \
if [ ! -f /etc/fslconf/fsl.sh ]; then echo "You need to set the FSLDIR environment variable to point to the FSL installation directory before you can run anything." ; exit 1; fi

# the next line restarts using wish \
if [ _$FSLWISH = _ ] ; then echo "You need to source an FSL setup file - either fsl.sh or fsl.csh in \/etc/fslconf !" ; exit 1 ; else exec $FSLWISH "$0" -- "$@" ; fi

set FSLDIR $env(FSLDIR)

set origname [ string tolower [ file tail [ info script ] ] ]

set UNAME [ exec uname ]
if { $UNAME == "Darwin" || [ string compare CYGWIN [ string range $UNAME 0 5 ] ] == 0 } {
    regsub "_gui" $origname "" origname
}

source /usr/libexec/fsl/${origname}.tcl

exit
```
I have big problems with this. This is run as `/bin/sh` but `$env(FSLDIR)` is not shell syntax, it is tcl/tk syntax. `Melodic`? Same issue. In fact the whole line escaped from tcl/tk and even though some shell commands are very similar is not the same.

**Comment by TheChymera** [comment]
@kiwifb what can we do about this? :-/

Also, just a heads up, I have recently updated the PYTHON_COMPAT of fslpy, and until Rtree gets compat-bumped in the main tree it will only be available for 3.7. This shouldn't interfere with FSL, but just in case the prev issue pops up.

**Comment by kiwifb** [comment]
@TheChymera 

1. that's clearly a problem upstream need to fix
2. I think it is safe to just remove the line

I have a few odds that need to go in PR - for the overlay. I'll put it in.

**Comment by kiwifb** [comment]
It is safe for us to remove the line. Upstream may have to do some work :)

**Comment by TheChymera** [comment]
@kiwifb we can contact Paul again at the end of this with our suggestions.

**Comment by AbstractMethod** [comment]
FYI: I tried this change in my `/etc/fslconf/fslstart.tcl`:

```
--- /usr/libexec/fsl/fslstart.tcl	2020-09-26 17:17:23.299611074 -0400
+++ /root/fsl/fslstart.tcl	2020-09-21 13:16:08.754524640 -0400
@@ -1,16 +1,16 @@

-set FSLDIR        $env(FSLDIR)
-set FSLOUTPUTTYPE $env(FSLOUTPUTTYPE)
-set FSLTCLSH      $env(FSLTCLSH)
-set FSLWISH       $env(FSLWISH)
+set FSLDIR        $::env(FSLDIR)
+set FSLOUTPUTTYPE $::env(FSLOUTPUTTYPE)
+set FSLTCLSH      $::env(FSLTCLSH)
+set FSLWISH       $::env(FSLWISH)
 
-set USER       $env(USER)
+set USER       $::env(USER)
 set HOME       [ exec sh -c " cd ; pwd " ]
 set PWD        [ exec sh -c " pwd " ]
 set PROCID     [ pid ]
 set HOSTNAME   [ exec hostname ]
 set OS         [ exec uname ]

-set auto_path [ linsert $auto_path 0 /usr/libexec/fsl/ ]
+set auto_path [ linsert $::auto_path 0 /usr/libexec/fsl/ ]
 
 set MYEXEC    [ info nameofexecutable ]
 set MYSHELL   [ file tail $MYEXEC ]
```

and then ran `Feat`.  The result is that gets "past" the error listed above.  But it then runs into a problem of infinitely recursed evaluations:

```
Error in startup script: too many nested evaluations (infinite loop?)
    while executing
"info script "
    (file "/etc/fslconf/feat.tcl" line 70)
    invoked from within
"source /etc/fslconf/feat.tcl"
    (procedure "feat5:setupdefaults" line 10)
    invoked from within
"feat5:setupdefaults"
    (procedure "feat5" line 6)
    invoked from within
"feat5 .r"
    (file "/etc/fslconf/feat.tcl" line 524)
    invoked from within
"source /etc/fslconf/feat.tcl"
    (procedure "feat5:setupdefaults" line 10)
    invoked from within
"feat5:setupdefaults"
    (procedure "feat5" line 6)
    invoked from within
```

etc. I don't know if that helps or not, but clearly something is quite broken with how `Feat` is being invoked.

**Comment by kiwifb** [comment]
@AbstractMethod may need someone more knowledgeable in tcl/tk. I am feeling like if `Feat` is called like `wish Feat` it may work. But  not as straight `Feat` because it mixes `sh` and tcl/tk. I was looking more closely at scripts last night and quite a number of them are like that. Starting with `#!/bin/sh` and then using `$env()` which is not part of `sh` but tcl.

With that in mind what does doing `$::env` over `$env` achieve? Can you enlighten me?

**Comment by AbstractMethod** [comment]
Agree with you on the tcl/tk -- the scripts do seem to mix and match between that and `sh`.

Not at all an expert either on tcl/tk, but apparently environment variables can be accessed (as attempted in the script) by `$env(VAR)`, although *fully* qualified this is actually `$::env(VAR)`.  So make of that what you will? :-/

Looking at `Feat` and this line:

```
# the next line restarts using wish \
if [ _$FSLWISH = _ ] ; then echo "You need to source an FSL setup file - either fsl.sh or fsl.csh in \/etc/fslconf !" ; exit 1 ; else exec $FSLWISH "$0" -- "$@" ; fi
```

leads me to think that the script is doing what you sayL -- the `Feat` command calling itself via `fslwish` instead of `sh`.  In any case, this is all rather convoluted and weird -- seems to me there must be a more straightforward way of organizing the scripts and underlying tcl/tk code.

**Comment by kiwifb** [comment]
Right. Then from my fsl-on-gentoo point of view, these all need to be converted to tcl/tk. I note that may explain the looping. If the line you quote is interpreted in tcl/tk you get into a rinse/repeat cycle.

**Comment by pauldmccarthy** [comment]
Hi all, just catching up on this thread. Yes, this is how Feat (and various other FSL scripts) work - they are invoked as shell scripts, and then recursively re-invoked with a TCL/TK interpreter. Not my design.

To be honest though, I would recommend not spending too much time trying to fix this. There is an internal effort to replace all of the FSL guis with more modern wxPython-based alternatives, so some time in the future all of the TCL/TK code, and unpleasantries, such as this, will be removed from FSL.

**Comment by kiwifb** [comment]
Hi Paul, thanks for letting us know. I appreciate this doesn't have a future (thanks goodness), but I'll still have to figure out something for the current usage in Gentoo, but with keeping what you said in mind, I'll keep it quick and dirty.
