### ISSUE TITLE
sci-biology/sra_sdk is outdated to the point of source not being available any more

### ISSUE THREAD

**Issue by anton-molyboha** [gentoo/sci#982]
The ebuild's SRCURI points to http://ftp-private.ncbi.nlm.nih.gov, which consistently times out for me. The official [NIH](https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=software) website points to https://github.com/ncbi/sra-tools as the canonical source of the package's code.

It would be nice to fix the SRCURI and bump the package to the latest version (2.10.8)

**Comment by epsilon-0** [comment]
Would you be interested in managing the package?
A PR to update and take maintainership would be very welcome.

**Comment by anton-molyboha** [comment]
Yes, I will come up with a PR... eventually -- and will add myself as a maintainer.

Is there something I will need to know as a maintainer? Join a mailing list? Look through some "best practices" guidelines?

**Comment by epsilon-0** [comment]
Take a look at the proxy-maintainer guidelines - https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide

They should be a good starting point, if thats not enough, you can come ask us on #gentoo-science on freenode

**Comment by mmokrejs** [comment]
Hi @anton-molyboha Unfortunately I have no time to study the changes but seems sra-sdk was renamed to sra-tools. I tried to adjust the ebuild to current release but their home-grown configure script fails for me as it does not recognize the cmdline args Gentoo eclasses pass to a configure. Here is where I stopped:

[sra_sdk-2.10.8.ebuild.patch.txt](https://github.com/gentoo/sci/files/5411026/sra_sdk-2.10.8.ebuild.patch.txt)

**Comment by anton-molyboha** [comment]
Thanks @mmokrejs !

I think we'll have to call ./configure manually then.

**Comment by anton-molyboha** [comment]
Thanks for the comments in your patch re --with-XXX-prefix flags.
