### ISSUE TITLE
[QA wishlist] sci-biology/fastqc needs tests

### ISSUE THREAD

**Issue by anton-molyboha** [gentoo/sci#985]
A minimal test would feed in a .fastq file and check that there is some report in the output.

I'm not sure yet what's the best strategy to get the test data:
 1. Generate pseudo-random "garbage" data.
 2. Attach to the package.
 3. Download using sra-toolkit.

Ideas for other tests are also welcome!

**Comment by epsilon-0** [comment]
@anton-molyboha 
do you mean to say that upstream hasn't made any tests available and you want to add custom test cases?
If so, I am against this idea, as this is something that we will have added and is not guaranteed to not break over future updates.
A better solution would be to do these things and send them upstream, so it is properly vetted against their desires and recommendations.

**Comment by anton-molyboha** [comment]
I don't see any tests in the upstream's code (though I should bump to the latest version and check again).

I agree that working with upstream to create tests is the best route - I will try it first, but I might back up if it turns out to be more work than I am ready to put in...  My original interest in this package was because it would emerge without error, but, in fact, would not install some of the necessary files -- and so the program would not run. So, I want to test against that -- that we have installed all the necessary files, and the program runs, and finds all the libraries it needs. I think it may be appropriate to have a test on our side, if all we are testing is the ebuild itself, rather than the program.

Let's talk again after I (or whoever takes on this issue) actually start working on this, check the latest version of the package, and get in touch with the upstream?

**Comment by AndrewAmmerlaan** [comment]
No tests yet, but I did update the ebuild and add a desktop shortcut for this.

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
